<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php';
$apk=__DIR__.'/downloads/K-Education.apk';$available=is_file($apk);
$size=$available?number_format((float)filesize($apk)/1048576,2).' MB':'';$checksum=$available?strtoupper((string)hash_file('sha256',$apk)):'';
$supportEmail=defined('SUPPORT_EMAIL')?SUPPORT_EMAIL:'support@keducation.site';$pageTitle='Download Android app';include __DIR__.'/includes/header.php';
?>
<style>
.download-shell{max-width:900px;margin:auto}.download-hero{padding:34px;background:radial-gradient(circle at 88% 13%,rgba(255,182,56,.38),transparent 24%),linear-gradient(135deg,#21175f,#5842d5 54%,#168bb4);color:#fff}.download-hero h1{margin:15px 0 8px;color:#fff}.download-hero p{max-width:620px;color:rgba(255,255,255,.82)}.app-lockup{display:flex;align-items:center;gap:16px}.app-lockup img{width:88px;height:88px;object-fit:contain;border-radius:25px;background:#fff;box-shadow:0 15px 35px rgba(13,17,58,.3)}.download-button{margin-top:17px;background:linear-gradient(135deg,#ff9d2e,#ffbd38);color:#392600}.download-meta{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}.download-meta span{padding:6px 10px;border-radius:999px;background:rgba(255,255,255,.14);font-size:.75rem;font-weight:800}.install-grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.install-grid>.card{margin:0}.step-list{counter-reset:download-step}.download-step{display:grid;grid-template-columns:42px 1fr;gap:12px;padding:13px 0;border-bottom:1px solid var(--line)}.download-step:last-child{border:0}.download-step:before{counter-increment:download-step;content:counter(download-step);display:grid;place-items:center;width:40px;height:40px;border-radius:13px;background:#efedff;color:var(--violet);font-weight:900}.download-step b,.download-step small{display:block}.download-step small{margin-top:3px;color:var(--muted)}.checksum{display:block;padding:11px;border-radius:12px;background:#f3f5fa;overflow-wrap:anywhere;font:700 .68rem/1.5 ui-monospace,monospace}.safety{border:1px solid #c9eedf;background:#f5fffb}@media(max-width:700px){.download-hero{padding:24px}.app-lockup{align-items:flex-start}.app-lockup img{width:72px;height:72px}.install-grid{grid-template-columns:1fr}}
</style>
<div class="download-shell">
 <section class="card download-hero"><div class="app-lockup"><img src="<?=url('logo/k-transparent.png')?>" alt="K Education app icon"><div><span class="badge">Android app</span><h1>Download K Education</h1><p>Learn with Grade 6–11 textbook notes, quick challenges, quizzes, progress tools, parent monitoring and the AI Tutor.</p></div></div>
 <?php if($available):?><a class="btn download-button" href="<?=url('download-apk.php')?>">Download APK now ↓</a><div class="download-meta"><span>Version 1.0.0</span><span><?=e($size)?></span><span>Android 6.0 or newer</span><span>Signed by K Education</span></div><?php else:?><div class="alert warning" style="margin-top:17px">The Android package is being prepared. Please check again shortly.</div><?php endif;?></section>
 <section class="install-grid"><article class="card"><span class="badge">Installation</span><h2>Install in three steps</h2><div class="step-list"><div class="download-step"><div><b>Download the APK</b><small>Tap the download button above and keep the file.</small></div></div><div class="download-step"><div><b>Allow this one installation</b><small>If Android asks, allow your browser to “Install unknown apps”. This warning appears because the app is not yet distributed by Google Play.</small></div></div><div class="download-step"><div><b>Open K Education</b><small>Tap Install, then open the app and use your normal K Education login.</small></div></div></div></article>
 <article class="card safety"><span class="badge">Security check</span><h2>Official K Education build</h2><p>This APK is served directly from <strong>keducation.site</strong>, uses secure HTTPS connections, and is digitally signed. Do not install copies sent from unknown websites or messaging groups.</p><?php if($checksum):?><p class="muted" style="margin-bottom:6px">SHA-256 checksum</p><code class="checksum"><?=e($checksum)?></code><?php endif;?><p class="muted">The app loads current learning content from our live service, so new lessons and notes appear without reinstalling it.</p></article></section>
 <section class="card"><h2>Need help?</h2><p>Contact <a href="mailto:<?=e($supportEmail)?>"><?=e($supportEmail)?></a>. Google Play distribution is being prepared separately; this direct APK works while account verification and testing are completed.</p><p><a href="<?=url('home.php')?>">← Return to K Education</a></p></section>
</div>
<?php include __DIR__.'/includes/footer.php';
