<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../includes/ol_schema.php';
require_login();require_premium();if(!in_array(user_grade_number(),[10,11],true))redirect('student/dashboard.php');
ensure_ol_schema();$db=db();$medium=medium_language((string)user()['medium']);$uid=(int)user()['id'];
$stats=query_one("SELECT (SELECT COUNT(*) FROM ol_papers WHERE medium=? AND status=1) papers,(SELECT COUNT(DISTINCT subject_id) FROM ol_papers WHERE medium=? AND status=1) subjects,(SELECT COUNT(*) FROM ol_question_attempts WHERE user_id=?) answers",'ssi',[$medium,$medium,$uid])??[];
$s=$db->prepare("SELECT s.id,s.name_en,s.name_si,s.name_ta,COUNT(p.id) papers,MAX(p.year) latest_year FROM subjects s JOIN ol_papers p ON p.subject_id=s.id AND p.medium=? AND p.status=1 WHERE s.status='active' GROUP BY s.id ORDER BY papers DESC,s.name_en LIMIT 6");$s->bind_param('s',$medium);$s->execute();$subjects=$s->get_result()->fetch_all(MYSQLI_ASSOC);
$pageTitle='O/L Kuppiya';include __DIR__.'/../includes/header.php';
?>
<style>
.olk{max-width:1100px;margin:18px auto}.olk-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:1.2fr .8fr;gap:25px;padding:42px;border:0;border-radius:31px;background:radial-gradient(circle at 84% 18%,rgba(65,222,255,.26),transparent 24%),linear-gradient(135deg,#111543,#38247e 52%,#076b94);color:#fff;box-shadow:0 28px 70px rgba(26,30,103,.25)}.olk-hero h1{margin:13px 0 10px;color:#fff;font-size:clamp(2.3rem,6vw,4rem);line-height:1}.olk-hero p{max-width:620px;color:#c7d4f5;line-height:1.65}.olk-kicker{color:#82efff;font-size:.72rem;font-weight:950;letter-spacing:.13em;text-transform:uppercase}.olk-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.olk-actions a{text-decoration:none}.olk-primary{padding:13px 18px;border-radius:14px;background:linear-gradient(135deg,#ffe77a,#ffae43);color:#302100;font-weight:950}.olk-secondary{padding:13px 18px;border:1px solid rgba(255,255,255,.22);border-radius:14px;background:rgba(255,255,255,.09);color:#fff;font-weight:900}.olk-score{align-self:center;padding:23px;border:1px solid rgba(255,255,255,.18);border-radius:24px;background:rgba(255,255,255,.11);backdrop-filter:blur(10px)}.olk-score strong{display:block;font-size:2.7rem}.olk-score small{color:#c3d0ee}.olk-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:17px 0}.olk-stat{margin:0;text-align:center}.olk-stat b{display:block;color:#5544ca;font-size:1.65rem}.olk-subjects{display:grid;grid-template-columns:repeat(3,1fr);gap:13px}.olk-subject{position:relative;margin:0;padding:20px;text-decoration:none;color:inherit;transition:.22s}.olk-subject:hover{transform:translateY(-5px);border-color:#aaa0ef;box-shadow:0 18px 35px rgba(51,53,130,.12)}.olk-subject span{display:grid;place-items:center;width:45px;height:45px;border-radius:14px;background:linear-gradient(135deg,#ede9ff,#e2f7ff);color:#5544ca;font-weight:950}.olk-subject h3{margin:14px 0 5px}.olk-subject small{color:var(--muted)}.olk-empty{text-align:center;padding:35px}.olk-heading{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:28px 0 13px}.olk-heading h2{margin:0}.olk-heading a{font-weight:850}@media(max-width:760px){.olk-hero{grid-template-columns:1fr;padding:28px 22px}.olk-subjects{grid-template-columns:1fr 1fr}}@media(max-width:480px){.olk-stats,.olk-subjects{grid-template-columns:1fr}.olk-actions{display:grid}.olk-actions a{text-align:center}}
</style>
<main class="olk"><section class="olk-hero"><div><div class="olk-kicker">K Education - Premium exam studio</div><h1>Your O/L paper practice starts here.</h1><p>Choose your subject and practise real past papers in <?=e(ucfirst($medium))?> medium. Read the paper, write answers question by question and ask the O/L AI Tutor when you need guidance.</p><div class="olk-actions"><a class="olk-primary" href="subjects.php">Browse past papers &rarr;</a><a class="olk-secondary" href="subjects.php">Choose an exam question</a></div></div><aside class="olk-score"><span class="badge">Grade <?=user_grade_number()?> workspace</span><strong><?=intval($stats['answers']??0)?></strong><small>answers submitted so far</small></aside></section>
<section class="olk-stats"><article class="card olk-stat"><b><?=intval($stats['subjects']??0)?></b><small>Available subjects</small></article><article class="card olk-stat"><b><?=intval($stats['papers']??0)?></b><small>Past papers</small></article><article class="card olk-stat"><b><?=e(strtoupper($medium))?></b><small>Your medium</small></article></section>
<div class="olk-heading"><div><span class="badge">Paper library</span><h2>Choose a subject</h2></div><a href="subjects.php">View all &rarr;</a></div>
<?php if($subjects):?><section class="olk-subjects"><?php foreach($subjects as $subject):?><a class="card olk-subject" href="papers.php?subject_id=<?=(int)$subject['id']?>"><span>OL</span><h3><?=e(locale_value($subject,'name'))?></h3><small><?=intval($subject['papers'])?> paper<?=intval($subject['papers'])===1?'':'s'?> - latest <?=intval($subject['latest_year'])?></small></a><?php endforeach;?></section><?php else:?><section class="card olk-empty"><h2>No papers for your medium yet</h2><p class="muted">An administrator can upload the first <?=e(ucfirst($medium))?> paper from the O/L Kuppiya admin area.</p></section><?php endif;?>
</main>
<?php include __DIR__.'/../includes/footer.php';?>
