<?php
require_once __DIR__.'/../includes/auth.php';require_once __DIR__.'/../includes/ol_schema.php';require_once __DIR__.'/../includes/ol_pdf.php';require_login();require_premium();
if(!in_array(user_grade_number(),[10,11],true)){redirect('student/dashboard.php');}
$sid=filter_input(INPUT_GET,'subject_id',FILTER_VALIDATE_INT);$year=filter_input(INPUT_GET,'year',FILTER_VALIDATE_INT);$medium=medium_language((string)user()['medium']);
$paper=query_one('SELECT p.*,s.name_en,s.name_si,s.name_ta FROM ol_papers p JOIN subjects s ON s.id=p.subject_id WHERE p.subject_id=? AND p.year=? AND p.medium=? AND p.status=1','iis',[$sid,$year,$medium]);if(!$paper){flash('warning','This paper is not available.');redirect('ol-kuppiya/papers.php?subject_id='.$sid);}
ensure_ol_schema();$db=db();$st=$db->prepare('SELECT * FROM ol_paper_questions WHERE paper_id=? ORDER BY display_order,id');$st->bind_param('i',$paper['id']);$st->execute();$questions=$st->get_result()->fetch_all(MYSQLI_ASSOC);
if(!$questions){$pdf=realpath(__DIR__.'/../'.ltrim($paper['paper_file_path'],'/'));$text=$pdf?ol_pdf_text($pdf):'';$order=0;foreach($pdf?ol_read_questions($pdf):[] as $item){$ins=$db->prepare('INSERT IGNORE INTO ol_paper_questions(paper_id,question_number,question_text,display_order) VALUES(?,?,?,?)');$ins->bind_param('issi',$paper['id'],$item['number'],$item['text'],$order);$ins->execute();$order++;}$st=$db->prepare('SELECT * FROM ol_paper_questions WHERE paper_id=? ORDER BY display_order,id');$st->bind_param('i',$paper['id']);$st->execute();$questions=$st->get_result()->fetch_all(MYSQLI_ASSOC);}
$pageTitle='O/L paper';include __DIR__.'/../includes/header.php';?>
<style>.ol-paper-hero{padding:28px;background:linear-gradient(135deg,#21185e,#4d3bc5 52%,#168cc1);color:#fff;border:0}.ol-paper-hero .badge{background:rgba(255,255,255,.14);color:#fff}.ol-paper-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:22px}.ol-paper-actions a,.ol-paper-actions .locked{display:flex;align-items:center;gap:10px;min-height:58px;text-decoration:none}.action-icon{font-size:1.5rem}.ol-question{margin-top:14px}.ol-question textarea{min-height:130px}.ol-question p{line-height:1.7;white-space:pre-wrap}@media(max-width:560px){.ol-paper-actions{grid-template-columns:1fr}}</style>
<p><a href="papers.php?subject_id=<?=$sid?>">← Papers</a></p><section class="card ol-paper-hero"><span class="badge"><?=e(locale_value($paper,'name'))?> · <?=e(strtoupper($paper['medium']))?> medium</span><h1><?=intval($paper['year'])?> O/L paper</h1><p>Answer each question here. Official answers stay locked.</p><div class="ol-paper-actions"><a class="card" target="_blank" href="download.php?id=<?=$paper['id']?>&amp;type=paper"><span class="action-icon">📄</span><span><strong>View question paper</strong><small style="display:block;opacity:.72">Reference PDF</small></span></a><span class="card locked"><span class="action-icon">🔒</span><span><strong>Answer sheet locked</strong><small style="display:block;opacity:.72">Submit your answer first</small></span></span></div></section><section class="card" style="margin-top:16px"><div class="row" style="justify-content:space-between"><div><span class="badge">Exam workspace</span><h2><?=count($questions)?> extracted questions</h2></div><a class="btn good" href="<?=url('ol-kuppiya/discuss.php')?>?id=<?=$paper['id']?>">🤖 O/L AI Tutor</a></div></section>
<section><?php foreach($questions as $q):?><article class="card ol-question"><div class="row" style="justify-content:space-between"><span class="badge">Question <?=e($q['question_number'])?></span><a class="btn alt" href="<?=url('ol-kuppiya/discuss.php')?>?id=<?=$paper['id']?>&amp;q=<?=rawurlencode($q['question_number'])?>">Ask AI</a></div><p><?=e($q['question_text'])?></p><form method="post" action="submit_answer.php"><?=csrf_field()?><input type="hidden" name="question_id" value="<?=$q['id']?>"><textarea name="student_answer" required placeholder="Write your answer here..."></textarea><button class="good">Submit answer</button></form></article><?php endforeach;if(!$questions):?><article class="card muted">This PDF has no machine-readable text. Ask an administrator to enter the questions in the paper editor.</article><?php endif;?></section>
<?php include __DIR__.'/../includes/footer.php';
