<?php
declare(strict_types=1);

ini_set('session.save_path',__DIR__.'/../includes/runtime');set_time_limit(0);
require_once __DIR__.'/../includes/db.php';require_once __DIR__.'/../includes/helpers.php';
if(PHP_SAPI!=='cli'){http_response_code(403);exit("Run from the command line.\n");}
$requested=(int)($argv[1]??0);$grades=$requested?[$requested]:[6,7,9,10];foreach($grades as $grade)if(!in_array($grade,[6,7,9,10],true))throw new RuntimeException('Usage: php deploy_grades_quick_learning_local.php [6|7|9|10]');

function local_field(array $lesson):string{
 $subject=mb_strtolower((string)$lesson['subject']);if(str_contains($subject,'second language tamil'))return 'ta';if(str_contains($subject,'second language sinhala'))return 'si';return match($lesson['medium']){'Sinhala'=>'si','Tamil'=>'ta',default=>'en'};
}
function local_clean(string $text):string{
 $text=html_entity_decode($text,ENT_QUOTES|ENT_HTML5,'UTF-8');$text=str_replace(["\u{00AD}","\u{FFFD}",'For free distribution','For Free Distribution'],' ',$text);return trim(preg_replace('/\s+/u',' ',$text)??$text);
}
function local_sentences(string $text):array{
 $text=local_clean($text);$parts=preg_split('/(?<=[.!?\x{0964}])\s+|\s*[•▪]\s*/u',$text)?:[];$out=[];
 foreach($parts as $part){$part=trim(preg_replace('/^(?:[-–—✓]|\d+[.)])\s*/u','',$part)??$part);if(mb_strlen($part)<30||mb_strlen($part)>440||preg_match('/^(?:activity|exercise|figure|table|chapter|page)\b/iu',$part))continue;$key=mb_strtolower(preg_replace('/[^\p{L}\p{N}]+/u','',$part)??$part);if($key!==''&&!isset($out[$key]))$out[$key]=$part;if(count($out)>=18)break;}return array_values($out);
}
function local_terms(string $text):array{
 $stop=array_flip(explode(' ','about after again also because before being from have into more most other over same some such than that their them then there these they this those through under using very what when where which while will with would lesson grade activity figure correct answer question your'));$freq=[];preg_match_all('/[\p{L}][\p{L}\p{M}\-]{3,}/u',mb_strtolower($text),$matches);foreach($matches[0] as $word)if(!isset($stop[$word]))$freq[$word]=($freq[$word]??0)+1;arsort($freq);return array_slice(array_keys($freq),0,20);
}
function local_labels(string $field):array{return match($field){
 'si'=>['heading'=>'කෙටි සටහන්','intro'=>'මෙම පාඩමේ වැදගත් අදහස් සරලව නැවත බලමු.','points'=>'ප්‍රධාන කරුණු','terms'=>'වැදගත් පද','examples'=>'උදාහරණ සහ යෙදීම්','remember'=>'මතක තබා ගන්න','checks'=>['ප්‍රධාන අදහස ඔබේම වචනවලින් පැහැදිලි කරන්න.','වැදගත් පද සහ කරුණු නැවත මතක් කරන්න.','ඉක්මන් අභියෝගයේ ප්‍රශ්න පහට පිළිතුරු දෙන්න.'],'which'=>'පාඩම අනුව නිවැරදි ප්‍රකාශය කුමක්ද?','complete'=>'පාඩමේ අදහස සම්පූර්ණ කරන නිවැරදි පිළිතුර තෝරන්න: ','explain'=>'මෙම පිළිතුර පාඩමේ සඳහන් අදහසට ගැළපේ.'],
 'ta'=>['heading'=>'சுருக்கக் குறிப்புகள்','intro'=>'இந்தப் பாடத்தின் முக்கிய கருத்துகளை எளிமையாக மீளாய்வு செய்வோம்.','points'=>'முக்கிய கருத்துகள்','terms'=>'முக்கிய சொற்கள்','examples'=>'உதாரணங்களும் பயன்பாடுகளும்','remember'=>'நினைவில் கொள்ளுங்கள்','checks'=>['முக்கிய கருத்தை உங்கள் சொந்த வார்த்தைகளில் விளக்குங்கள்.','முக்கிய சொற்களையும் உண்மைகளையும் மீண்டும் படியுங்கள்.','ஐந்து விரைவு சவால் கேள்விகளுக்கும் பதிலளியுங்கள்.'],'which'=>'பாடத்தின்படி சரியான கூற்று எது?','complete'=>'பாடக் கருத்தை நிறைவு செய்யும் சரியான விடையைத் தேர்ந்தெடுக்கவும்: ','explain'=>'இந்த விடை பாடத்தில் உள்ள கருத்துடன் பொருந்துகிறது.'],
 default=>['heading'=>'SHORT NOTES','intro'=>'Let’s revise the most important ideas from this lesson in a simple way.','points'=>'KEY IDEAS','terms'=>'IMPORTANT TERMS','examples'=>'EXAMPLES AND APPLICATIONS','remember'=>'REMEMBER','checks'=>['Explain the main idea in your own words.','Review the important facts and vocabulary.','Answer all five Quick Challenge questions.'],'which'=>'Which statement is correct according to this lesson?','complete'=>'Choose the answer that correctly completes this lesson idea: ','explain'=>'This answer matches the idea explained in the lesson.']};}
function local_distractors(array $terms,string $correct,string $seed):array{$pool=array_values(array_filter($terms,fn($x)=>mb_strtolower($x)!==mb_strtolower($correct)&&mb_strlen($x)>=3));$out=[];$count=count($pool);if($count){$offset=abs(crc32($seed))%$count;for($i=0;$i<$count&&count($out)<3;$i++)if(!in_array($pool[($offset+$i)%$count],$out,true))$out[]=$pool[($offset+$i)%$count];}foreach(['None of these','All statements are incorrect','Not related to this lesson'] as $fallback)if(count($out)<3)$out[]=$fallback;return array_slice($out,0,3);}
function local_content(array $lesson,string $field):array{
 $title=trim((string)($lesson['title_'.$field]?:$lesson['title_en']?:('Lesson '.$lesson['display_order'])));$source=trim((string)($lesson['content_'.$field]?:$lesson['short_notes_'.$field]?:$lesson['content_en']?:''));$summary=trim((string)($lesson['summary_'.$field]?:$lesson['summary_en']?:''));$sentences=local_sentences($source."\n".$summary);if(count($sentences)<5)$sentences=local_sentences((string)$lesson['short_notes_'.$field]."\n".$source."\n".$summary);$points=array_slice($sentences,0,8);while(count($points)<5)$points[]=$title.' — '.($sentences[0]??$summary?:$source);$terms=local_terms($source.' '.(string)$lesson['key_terms_'.$field]);$labels=local_labels($field);
 $notes=$labels['heading']."\n\n".$labels['intro']."\n\n".$labels['points']."\n";foreach($points as $point)$notes.='• '.$point."\n";if($terms){$notes.="\n".$labels['terms']."\n";foreach(array_slice($terms,0,10) as $term)$notes.='• '.$term."\n";}$notes.="\n".$labels['examples']."\n";foreach(array_slice($points,-3) as $point)$notes.='• '.$point."\n";$notes.="\n".$labels['remember']."\n";foreach($labels['checks'] as $check)$notes.='✓ '.$check."\n";while(mb_strlen($notes)<350)$notes.='✓ '.$labels['intro']."\n";
 $questions=[];foreach($points as $index=>$sentence){if(count($questions)>=5)break;$correct='';foreach($terms as $term)if(mb_strlen($term)>=4&&preg_match('/(?<![\p{L}\p{M}])'.preg_quote($term,'/').'(?![\p{L}\p{M}])/iu',$sentence)){$correct=$term;break;}if($correct!==''){$blank=preg_replace('/(?<![\p{L}\p{M}])'.preg_quote($correct,'/').'(?![\p{L}\p{M}])/iu','_____',$sentence,1);$options=array_merge([$correct],local_distractors($terms,$correct,$title.$index));usort($options,fn($a,$b)=>strcmp(hash('sha256',$title.$index.$a),hash('sha256',$title.$index.$b)));$correctLetter=['a','b','c','d'][array_search($correct,$options,true)];$questions[]=['question'=>$labels['complete'].$blank,'options'=>$options,'correct'=>$correctLetter,'explanation'=>$sentence];}else{$other=array_values(array_filter($points,fn($x)=>$x!==$sentence));$options=array_merge([$sentence],array_slice($other,0,3));while(count($options)<4)$options[]=$labels['explain'].' '.count($options);usort($options,fn($a,$b)=>strcmp(hash('sha256',$title.$index.$a),hash('sha256',$title.$index.$b)));$questions[]=['question'=>$labels['which'],'options'=>$options,'correct'=>['a','b','c','d'][array_search($sentence,$options,true)],'explanation'=>$sentence];}}
 return ['title'=>$title,'description'=>$points[0],'notes'=>trim($notes),'objectives'=>implode("\n",array_slice($labels['checks'],0,3))."\n".$labels['intro'],'terms'=>implode(', ',array_slice($terms,0,12)),'examples'=>implode("\n",array_map(fn($x)=>'• '.$x,array_slice($points,-3))),'summary'=>implode("\n",array_map(fn($x)=>'• '.$x,array_slice($points,0,6))),'questions'=>$questions];
}

$db=db();foreach($grades as $gradeNumber){$grade=query_one('SELECT id FROM grades WHERE grade_number=?','i',[$gradeNumber]);if(!$grade)throw new RuntimeException("Grade $gradeNumber is missing.");$gradeId=(int)$grade['id'];$s=$db->prepare("SELECT l.*,s.name_en subject FROM lessons l JOIN subjects s ON s.id=l.subject_id WHERE l.grade_id=? AND l.status='active' AND l.content_source='textbook' ORDER BY l.medium,s.name_en,l.display_order,l.id");$s->bind_param('i',$gradeId);$s->execute();$lessons=$s->get_result()->fetch_all(MYSQLI_ASSOC);$lessonCount=$questionCount=0;$db->begin_transaction();try{foreach($lessons as $lesson){$field=local_field($lesson);$data=local_content($lesson,$field);if(count($data['questions'])!==5)throw new RuntimeException("Could not build five questions for lesson {$lesson['id']}");$id=(int)$lesson['id'];$update=$db->prepare("UPDATE lessons SET short_description_$field=?,short_notes_$field=?,learning_objectives_$field=?,key_terms_$field=?,examples_$field=?,summary_$field=? WHERE id=?");$update->bind_param('ssssssi',$data['description'],$data['notes'],$data['objectives'],$data['terms'],$data['examples'],$data['summary'],$id);if(!$update->execute())throw new RuntimeException($update->error);$quiz=query_one('SELECT id FROM quizzes WHERE lesson_id=? AND status="active" ORDER BY id LIMIT 1','i',[$id]);if($quiz)$quizId=(int)$quiz['id'];else{$add=$db->prepare('INSERT INTO quizzes(grade_id,subject_id,unit_id,lesson_id,timer_minutes,pass_mark,status) VALUES(?,?,?,?,10,50,"active")');$subjectId=(int)$lesson['subject_id'];$unitId=(int)$lesson['unit_id'];$add->bind_param('iiii',$gradeId,$subjectId,$unitId,$id);if(!$add->execute())throw new RuntimeException($add->error);$quizId=(int)$db->insert_id;}$db->query("DELETE qa FROM quiz_answers qa JOIN quiz_questions qq ON qq.id=qa.question_id WHERE qq.quiz_id=$quizId AND qq.activity_type='challenge'");$delete=$db->prepare("DELETE FROM quiz_questions WHERE quiz_id=? AND activity_type='challenge'");$delete->bind_param('i',$quizId);$delete->execute();$insert=$db->prepare("INSERT INTO quiz_questions(quiz_id,activity_type,question_$field,option_a_$field,option_b_$field,option_c_$field,option_d_$field,correct_option,explanation_$field,display_order,status) VALUES(?,'challenge',?,?,?,?,?,?,?,?,'active')");foreach($data['questions'] as $index=>$q){[$a,$b,$c,$d]=$q['options'];$order=$index+1;$insert->bind_param('isssssssi',$quizId,$q['question'],$a,$b,$c,$d,$q['correct'],$q['explanation'],$order);if(!$insert->execute())throw new RuntimeException($insert->error);$questionCount++;}$lessonCount++;}$db->commit();echo "Grade $gradeNumber completed: $lessonCount lessons, $questionCount Quick Challenge questions.\n";}catch(Throwable $error){$db->rollback();throw $error;}}
