CREATE DATABASE IF NOT EXISTS educhat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE educhat;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS app_downloads,student_activity_events,student_emblems,student_points,quiz_answers,quiz_attempts,quiz_questions,quizzes,chat_messages,chat_sessions,lesson_progress,student_progress,subscriptions,subscription_plans,parent_student_links,student_parent_codes,parents,lessons,units,subjects,media,admins,users,referral_promoters,grades,settings;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE grades(id INT AUTO_INCREMENT PRIMARY KEY,grade_number TINYINT NOT NULL UNIQUE,name VARCHAR(50) NOT NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE referral_promoters(id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(100) NOT NULL,email VARCHAR(190) NULL UNIQUE,phone VARCHAR(15) NULL UNIQUE,referral_code VARCHAR(24) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',last_login_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(100) NOT NULL,username VARCHAR(30) NOT NULL UNIQUE,email VARCHAR(190) NULL UNIQUE,phone VARCHAR(15) NULL UNIQUE,phone_verified_at DATETIME NULL,school_name VARCHAR(190) NULL,district VARCHAR(80) NULL,password_hash VARCHAR(255) NOT NULL,grade_id INT NOT NULL,medium ENUM('Sinhala','Tamil','English') NOT NULL,preferred_language ENUM('en','si','ta') NOT NULL DEFAULT 'en',profile_image VARCHAR(255),subscription_expires_at DATETIME NULL,referral_promoter_id INT NULL,referral_code_used VARCHAR(24) NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(grade_id),INDEX(school_name),INDEX users_referral_promoter_idx(referral_promoter_id),FOREIGN KEY(grade_id) REFERENCES grades(id),CONSTRAINT users_referral_promoter_fk FOREIGN KEY(referral_promoter_id) REFERENCES referral_promoters(id) ON DELETE RESTRICT);
CREATE TABLE admins(id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(100) NOT NULL,username VARCHAR(50) NOT NULL UNIQUE,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role ENUM('admin','super_admin') DEFAULT 'admin',status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE parents(id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE student_parent_codes(student_id INT PRIMARY KEY,link_code CHAR(8) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE parent_student_links(parent_id INT NOT NULL,student_id INT NOT NULL,linked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,last_seen_at DATETIME NULL,PRIMARY KEY(parent_id,student_id),INDEX(student_id),FOREIGN KEY(parent_id) REFERENCES parents(id) ON DELETE CASCADE,FOREIGN KEY(student_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE media(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(30) UNIQUE NOT NULL,label_en VARCHAR(30),label_si VARCHAR(30),label_ta VARCHAR(30),status ENUM('active','inactive') DEFAULT 'active');
CREATE TABLE subjects(id INT AUTO_INCREMENT PRIMARY KEY,grade_id INT NOT NULL,subject_code VARCHAR(30) NOT NULL,name_en VARCHAR(100) NOT NULL,name_si VARCHAR(100) NOT NULL,name_ta VARCHAR(100) NOT NULL,description_en TEXT,description_si TEXT,description_ta TEXT,icon VARCHAR(20) DEFAULT '📘',status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE(grade_id,subject_code),FOREIGN KEY(grade_id) REFERENCES grades(id));
CREATE TABLE units(id INT AUTO_INCREMENT PRIMARY KEY,grade_id INT NOT NULL,subject_id INT NOT NULL,unit_number INT NOT NULL,name_en VARCHAR(180),name_si VARCHAR(180),name_ta VARCHAR(180),description_en TEXT,description_si TEXT,description_ta TEXT,display_order INT DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE(subject_id,unit_number),INDEX(grade_id),FOREIGN KEY(grade_id) REFERENCES grades(id),FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE CASCADE);
CREATE TABLE lessons(id INT AUTO_INCREMENT PRIMARY KEY,grade_id INT NOT NULL,medium ENUM('All','Sinhala','Tamil','English') DEFAULT 'All',content_source VARCHAR(30) NOT NULL DEFAULT 'manual',subject_id INT NOT NULL,unit_id INT NOT NULL,title_en VARCHAR(200),title_si VARCHAR(200),title_ta VARCHAR(200),short_description_en TEXT,short_description_si TEXT,short_description_ta TEXT,content_en MEDIUMTEXT,content_si MEDIUMTEXT,content_ta MEDIUMTEXT,learning_objectives_en TEXT,learning_objectives_si TEXT,learning_objectives_ta TEXT,key_terms_en TEXT,key_terms_si TEXT,key_terms_ta TEXT,examples_en TEXT,examples_si TEXT,examples_ta TEXT,summary_en TEXT,summary_si TEXT,summary_ta TEXT,display_order INT DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(grade_id,subject_id,unit_id),FULLTEXT(title_en,summary_en,key_terms_en),FOREIGN KEY(grade_id) REFERENCES grades(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(unit_id) REFERENCES units(id));
CREATE TABLE lesson_source_pdfs(lesson_id INT PRIMARY KEY,local_file VARCHAR(500) NOT NULL,start_page INT NOT NULL DEFAULT 1,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE);
CREATE TABLE lesson_progress(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,lesson_id INT NOT NULL,opened_at DATETIME NOT NULL,last_opened_at DATETIME NOT NULL,completed_at DATETIME NULL,UNIQUE(user_id,lesson_id),INDEX(last_opened_at),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE);
CREATE TABLE quizzes(id INT AUTO_INCREMENT PRIMARY KEY,grade_id INT NOT NULL,subject_id INT NOT NULL,unit_id INT NULL,lesson_id INT NULL,title_en VARCHAR(200),title_si VARCHAR(200),title_ta VARCHAR(200),timer_minutes INT NULL,pass_mark INT DEFAULT 50,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(grade_id) REFERENCES grades(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE SET NULL,FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE SET NULL);
CREATE TABLE quiz_questions(id INT AUTO_INCREMENT PRIMARY KEY,quiz_id INT NOT NULL,activity_type ENUM('lesson_quiz','challenge','missing','matching') NOT NULL DEFAULT 'lesson_quiz',question_en TEXT,question_si TEXT,question_ta TEXT,option_a_en TEXT,option_a_si TEXT,option_a_ta TEXT,option_b_en TEXT,option_b_si TEXT,option_b_ta TEXT,option_c_en TEXT,option_c_si TEXT,option_c_ta TEXT,option_d_en TEXT,option_d_si TEXT,option_d_ta TEXT,correct_option ENUM('a','b','c','d') NOT NULL,explanation_en TEXT,explanation_si TEXT,explanation_ta TEXT,display_order INT DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active',FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE);
CREATE TABLE quiz_attempts(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,quiz_id INT NOT NULL,score INT NOT NULL,total_questions INT NOT NULL,percentage INT NOT NULL,passed TINYINT(1) NOT NULL,started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME,INDEX(user_id,completed_at),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(quiz_id) REFERENCES quizzes(id));
CREATE TABLE quiz_answers(id BIGINT AUTO_INCREMENT PRIMARY KEY,attempt_id BIGINT NOT NULL,question_id INT NOT NULL,selected_option ENUM('a','b','c','d') NULL,is_correct TINYINT(1) NOT NULL,UNIQUE(attempt_id,question_id),FOREIGN KEY(attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,FOREIGN KEY(question_id) REFERENCES quiz_questions(id));
CREATE TABLE chat_sessions(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,subject_id INT NULL,lesson_id INT NULL,title VARCHAR(200),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,last_activity_at DATETIME,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL,FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE SET NULL);
CREATE TABLE chat_messages(id BIGINT AUTO_INCREMENT PRIMARY KEY,session_id BIGINT NOT NULL,user_id INT NOT NULL,role ENUM('user','assistant') NOT NULL,message TEXT NOT NULL,language ENUM('en','si','ta') NOT NULL,subject_id INT NULL,lesson_id INT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id,created_at),FOREIGN KEY(session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE student_activity_events(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,event_type ENUM('search','lesson_opened','lesson_completed','quiz_completed') NOT NULL,subject_id INT NULL,lesson_id INT NULL,quiz_id INT NULL,detail VARCHAR(500) NOT NULL,event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(user_id,event_time),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(subject_id) REFERENCES subjects(id) ON DELETE SET NULL,FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE SET NULL,FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE SET NULL);
CREATE TABLE student_progress(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL UNIQUE,total_completed_lessons INT DEFAULT 0,learning_streak INT DEFAULT 0,last_activity DATE NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE student_points(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,grade_id INT NOT NULL,subject_id INT NULL,lesson_id INT NULL,quiz_id INT NULL,activity_type VARCHAR(40) NOT NULL,points INT NOT NULL,award_key VARCHAR(190) NOT NULL,description VARCHAR(255) NOT NULL,awarded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,award_key),INDEX(grade_id,user_id),INDEX(user_id,awarded_at),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(grade_id) REFERENCES grades(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE SET NULL,FOREIGN KEY(quiz_id) REFERENCES quizzes(id) ON DELETE SET NULL);
CREATE TABLE student_emblems(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,grade_id INT NOT NULL,subject_id INT NOT NULL,lesson_id INT NOT NULL,tier ENUM('bronze','silver','gold','master') NOT NULL,earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,lesson_id,tier),INDEX(grade_id,user_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(grade_id) REFERENCES grades(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE);
CREATE TABLE subscription_plans(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),price_lkr DECIMAL(10,2),duration_days INT,features TEXT,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE subscriptions(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,plan_id INT NOT NULL,amount_lkr DECIMAL(10,2),base_amount_lkr DECIMAL(10,2) NOT NULL,discount_lkr DECIMAL(10,2) NOT NULL DEFAULT 0,referral_promoter_id INT NULL,payment_method VARCHAR(30),payment_reference VARCHAR(100) UNIQUE,status ENUM('pending','active','rejected','expired') DEFAULT 'pending',starts_at DATETIME NULL,expires_at DATETIME NULL,reviewed_by INT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX subscriptions_referral_promoter_idx(referral_promoter_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(plan_id) REFERENCES subscription_plans(id),FOREIGN KEY(reviewed_by) REFERENCES admins(id) ON DELETE SET NULL,CONSTRAINT subscriptions_referral_promoter_fk FOREIGN KEY(referral_promoter_id) REFERENCES referral_promoters(id) ON DELETE RESTRICT);
CREATE TABLE settings(id INT AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(100) UNIQUE,setting_value TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE curriculum_sources(id INT AUTO_INCREMENT PRIMARY KEY,grade_id INT NOT NULL,subject_name VARCHAR(180) NOT NULL,language ENUM('en','si','ta','mixed') DEFAULT 'mixed',title VARCHAR(255) NOT NULL,source_url TEXT NOT NULL,local_file VARCHAR(255) NOT NULL,file_hash CHAR(64) NOT NULL UNIQUE,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(grade_id) REFERENCES grades(id));
CREATE TABLE curriculum_chunks(id BIGINT AUTO_INCREMENT PRIMARY KEY,source_id INT NOT NULL,page_number INT NULL,chunk_index INT NOT NULL,content MEDIUMTEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(source_id,page_number),FULLTEXT(content),FOREIGN KEY(source_id) REFERENCES curriculum_sources(id) ON DELETE CASCADE);
CREATE TABLE app_downloads(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,ip_address VARCHAR(45),user_agent VARCHAR(500),downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(downloaded_at),INDEX(user_id));
INSERT INTO grades(grade_number,name) VALUES(6,'Grade 6'),(7,'Grade 7'),(8,'Grade 8'),(9,'Grade 9'),(10,'Grade 10');
INSERT INTO media(name,label_en,label_si,label_ta) VALUES('Sinhala','Sinhala','සිංහල','சிங்களம்'),('Tamil','Tamil','දෙමළ','தமிழ்'),('English','English','ඉංග්‍රීසි','ஆங்கிலம்');
INSERT INTO subscription_plans(name,price_lkr,duration_days,features) VALUES('K Education Premium 30 Days',300,30,'Unlimited AI tutor; all quizzes; answer review; detailed progress');
INSERT INTO admins(full_name,username,email,password_hash,role,status) VALUES('K Education Administrator','admin','admin@keducation.local','$2y$10$TBoX5tlUwoQm/xG8.Q4Hxu4qXryj47xoXdlyEUgVZqiFZ3nRlwfOW','super_admin','active');
INSERT INTO settings(setting_key,setting_value) VALUES('curriculum_notice','Verified Grade 6 textbook learning content is active.'),('payment_instructions','Configure bank or payment instructions in the admin settings/database.');
INSERT INTO subjects(grade_id,subject_code,name_en,name_si,name_ta,description_en,description_si,description_ta,icon) VALUES
(1,'MATH','Mathematics','ගණිතය','கணிதம்','Numbers, shapes and measurement.','සංඛ්‍යා, හැඩ සහ මිනුම්.','எண்கள், வடிவங்கள் மற்றும் அளவீடு.','➗'),(1,'SCI','Science','විද්‍යාව','அறிவியல்','Living things, matter, energy and environment.','ජීවීන්, ද්‍රව්‍ය, ශක්තිය හා පරිසරය.','உயிரினங்கள், பொருள், ஆற்றல் மற்றும் சூழல்.','🔬'),(1,'ENG','English','ඉංග්‍රීසි','ஆங்கிலம்','Language and communication.','භාෂාව හා සන්නිවේදනය.','மொழி மற்றும் தொடர்பாடல்.','🔤'),(1,'SIN','Sinhala','සිංහල','சிங்களம்','Sinhala language learning.','සිංහල භාෂා අධ්‍යයනය.','சிங்கள மொழிக் கற்றல்.','📗'),(1,'TAM','Tamil','දෙමළ','தமிழ்','Tamil language learning.','දෙමළ භාෂා අධ්‍යයනය.','தமிழ் மொழிக் கற்றல்.','📕'),(1,'HIS','History','ඉතිහාසය','வரலாறு','People and the past.','මිනිසුන් හා අතීතය.','மக்களும் கடந்த காலமும்.','🏛️'),(1,'GEO','Geography','භූගෝල විද්‍යාව','புவியியல்','Places, maps and Earth.','ස්ථාන, සිතියම් හා පෘථිවිය.','இடங்கள், வரைபடங்கள் மற்றும் பூமி.','🌍'),(1,'ICT','ICT','තොරතුරු හා සන්නිවේදන තාක්ෂණය','தகவல் தொடர்பாடல் தொழில்நுட்பம்','Computers and safe digital skills.','පරිගණක හා ආරක්ෂිත ඩිජිටල් කුසලතා.','கணினி மற்றும் பாதுகாப்பான டிஜிட்டல் திறன்கள்.','💻'),(1,'HPE','Health and Physical Education','සෞඛ්‍ය හා ශාරීරික අධ්‍යාපනය','சுகாதாரமும் உடற்கல்வியும்','Healthy bodies and active living.','සෞඛ්‍ය සම්පන්න ක්‍රියාශීලී ජීවිතය.','ஆரோக்கியமும் சுறுசுறுப்பான வாழ்வும்.','🏃'),(1,'CIV','Civic Education','පුරවැසි අධ්‍යාපනය','குடியியல் கல்வி','Responsible citizenship.','වගකීම් සහිත පුරවැසිභාවය.','பொறுப்பான குடியுரிமை.','🤝'),(1,'REL','Religion','ආගම','சமயம்','Values and religious learning.','සාරධර්ම හා ආගමික ඉගෙනීම.','விழுமியங்களும் சமயக் கற்றலும்.','🕊️');
INSERT INTO units(grade_id,subject_id,unit_number,name_en,name_si,name_ta,description_en,description_si,description_ta,display_order) VALUES
(1,1,1,'Whole Numbers','පූර්ණ සංඛ්‍යා','முழு எண்கள்','Reading and using whole numbers.','පූර්ණ සංඛ්‍යා කියවීම හා භාවිතය.','முழு எண்களை வாசித்துப் பயன்படுத்தல்.',1),(1,1,2,'Fractions','භාග','பின்னங்கள்','Parts of a whole.','සමස්තයක කොටස්.','ஒரு முழுமையின் பகுதிகள்.',2),(1,1,3,'Basic Geometry','මූලික ජ්‍යාමිතිය','அடிப்படை வடிவியல்','Lines, angles and shapes.','රේඛා, කෝණ හා හැඩ.','கோடுகள், கோணங்கள் மற்றும் வடிவங்கள்.',3),(1,1,4,'Measurements','මිනුම්','அளவீடுகள்','Length, mass and capacity.','දිග, ස්කන්ධය හා ධාරිතාව.','நீளம், திணிவு மற்றும் கொள்ளளவு.',4),(1,2,1,'Living Things','ජීවී දේ','உயிருள்ளவை','Features and needs of life.','ජීවීන්ගේ ලක්ෂණ හා අවශ්‍යතා.','உயிர்களின் பண்புகளும் தேவைகளும்.',1),(1,2,2,'Matter','ද්‍රව්‍ය','பொருள்','Solids, liquids and gases.','ඝන, ද්‍රව හා වායු.','திண்மம், திரவம் மற்றும் வாயு.',2),(1,2,3,'Energy','ශක්තිය','ஆற்றல்','Forms and uses of energy.','ශක්ති ආකාර හා භාවිත.','ஆற்றலின் வடிவங்களும் பயன்களும்.',3),(1,2,4,'Environment','පරිසරය','சுற்றுச்சூழல்','Caring for ecosystems.','පරිසර පද්ධති රැකබලා ගැනීම.','சூழலமைப்புகளைப் பாதுகாத்தல்.',4),(1,8,1,'Introduction to Computers','පරිගණක හැඳින්වීම','கணினி அறிமுகம்','What computers do.','පරිගණක කරන දේ.','கணினிகள் செய்யும் பணிகள்.',1),(1,8,2,'Computer Components','පරිගණක කොටස්','கணினி கூறுகள்','Hardware components.','දෘඪාංග කොටස්.','வன்பொருள் கூறுகள்.',2),(1,8,3,'Safe Computer Use','ආරක්ෂිත පරිගණක භාවිතය','பாதுகாப்பான கணினிப் பயன்பாடு','Safety and wellbeing.','ආරක්ෂාව හා යහපැවැත්ම.','பாதுகாப்பும் நலனும்.',3),(1,8,4,'Basic Digital Skills','මූලික ඩිජිටල් කුසලතා','அடிப்படை டிஜிட்டல் திறன்கள்','Files, typing and applications.','ගොනු, ටයිප් කිරීම හා යෙදුම්.','கோப்புகள், தட்டச்சு மற்றும் செயலிகள்.',4);
INSERT INTO lessons(grade_id,medium,subject_id,unit_id,title_en,title_si,title_ta,short_description_en,short_description_si,short_description_ta,content_en,content_si,content_ta,learning_objectives_en,learning_objectives_si,learning_objectives_ta,key_terms_en,key_terms_si,key_terms_ta,examples_en,examples_si,examples_ta,summary_en,summary_si,summary_ta,display_order) SELECT 1,'All',subject_id,id,name_en,name_si,name_ta,description_en,description_si,description_ta,CONCAT(name_en,' helps us understand ',description_en,' This is short demonstration content.'),CONCAT(name_si,' මගින් ',description_si,' තේරුම් ගනිමු. මෙය කෙටි නියැදි අන්තර්ගතයකි.'),CONCAT(name_ta,' மூலம் ',description_ta,' புரிந்துகொள்வோம். இது சுருக்கமான மாதிரி உள்ளடக்கம்.'),CONCAT('Identify and explain ',LOWER(name_en),'.'),CONCAT(name_si,' හඳුනාගෙන පැහැදිලි කිරීම.'),CONCAT(name_ta,' அடையாளம் கண்டு விளக்குதல்.'),name_en,name_si,name_ta,CONCAT('Think of one everyday example of ',LOWER(name_en),'.'),CONCAT(name_si,' සඳහා දෛනික උදාහරණයක් සිතන්න.'),CONCAT(name_ta,' குறித்த நாளாந்த உதாரணம் ஒன்றை நினைக்கவும்.'),CONCAT(name_en,' is an important Grade 6 idea.'),CONCAT(name_si,' 6 ශ්‍රේණියේ වැදගත් අදහසකි.'),CONCAT(name_ta,' தரம் 6 இன் முக்கிய கருத்தாகும்.'),1 FROM units;
INSERT INTO quizzes(grade_id,subject_id,unit_id,lesson_id,title_en,title_si,title_ta,timer_minutes,pass_mark) VALUES(1,1,1,1,'Grade 6 Mathematics Sample Quiz','6 ශ්‍රේණිය ගණිත නියැදි ප්‍රශ්නාවලිය','தரம் 6 கணித மாதிரி வினாடி வினா',10,60),(1,2,5,5,'Grade 6 Science Sample Quiz','6 ශ්‍රේණිය විද්‍යා නියැදි ප්‍රශ්නාවලිය','தரம் 6 அறிவியல் மாதிரி வினாடி வினா',10,60),(1,8,9,9,'Grade 6 ICT Sample Quiz','6 ශ්‍රේණිය ICT නියැදි ප්‍රශ්නාවලිය','தரம் 6 ICT மாதிரி வினாடி வினா',10,60);
INSERT INTO quiz_questions(quiz_id,question_en,question_si,question_ta,option_a_en,option_a_si,option_a_ta,option_b_en,option_b_si,option_b_ta,option_c_en,option_c_si,option_c_ta,option_d_en,option_d_si,option_d_ta,correct_option,explanation_en,explanation_si,explanation_ta,display_order) VALUES
(1,'What is 25 + 17?','25 + 17 කීයද?','25 + 17 எவ்வளவு?','42','42','42','32','32','32','52','52','52','41','41','41','a','Add ones, then tens.','එකස්ථාන හා දසස්ථාන එකතු කරන්න.','ஒன்றுகள், பத்துகளை கூட்டுக.',1),(1,'Half of 10 is?','10 හි අඩක්?','10 இன் பாதி?','2','2','2','5','5','5','10','10','10','20','20','20','b','10 divided by 2 is 5.','10 දෙකෙන් බෙදූ විට 5යි.','10 ஐ 2 ஆல் வகுத்தால் 5.',2),(1,'A triangle has how many sides?','ත්‍රිකෝණයක පැති කීයද?','முக்கோணத்திற்கு எத்தனை பக்கங்கள்?','2','2','2','3','3','3','4','4','4','5','5','5','b','A triangle has three sides.','ත්‍රිකෝණයට පැති තුනකි.','முக்கோணத்திற்கு மூன்று பக்கங்கள்.',3),(1,'100 cm equals?','100 cm සමාන වන්නේ?','100 cm என்பது?','1 m','1 m','1 m','10 m','10 m','10 m','1 km','1 km','1 km','10 cm','10 cm','10 cm','a','100 centimetres make one metre.','සෙන්ටිමීටර 100ක් මීටරයකි.','100 செ.மீ ஒரு மீட்டர்.',4),(1,'Which is largest?','විශාලතම සංඛ්‍යාව කුමක්ද?','பெரிய எண் எது?','9','9','9','19','19','19','91','91','91','29','29','29','c','91 has nine tens.','91 හි දහයේ ඒවා නවයකි.','91 இல் ஒன்பது பத்துகள் உள்ளன.',5),
(2,'Which is living?','ජීවී දෙය කුමක්ද?','உயிருள்ளது எது?','Rock','ගල','கல்','Plant','ශාකය','தாவரம்','Water','ජලය','நீர்','Air','වාතය','காற்று','b','Plants grow and reproduce.','ශාක වර්ධනය වී ප්‍රජනනය කරයි.','தாவரங்கள் வளர்ந்து இனப்பெருக்கம் செய்கின்றன.',1),(2,'Ice is a?','අයිස් යනු?','பனி என்பது?','Solid','ඝනයක්','திண்மம்','Liquid','ද්‍රවයක්','திரவம்','Gas','වායුවක්','வாயு','Light','ආලෝකය','ஒளி','a','Ice has a fixed shape.','අයිස්ට නියත හැඩයක් ඇත.','பனிக்கு நிலையான வடிவம் உண்டு.',2),(2,'The Sun gives us?','සූර්යයා අපට ලබා දෙන්නේ?','சூரியன் தருவது?','Sound only','ශබ්දය පමණි','ஒலி மட்டும்','Light and heat','ආලෝකය හා තාපය','ஒளியும் வெப்பமும்','Water','ජලය','நீர்','Soil','පස','மண்','b','The Sun provides light and heat energy.','සූර්යයා ආලෝක හා තාප ශක්තිය ලබා දෙයි.','சூரியன் ஒளி மற்றும் வெப்ப ஆற்றலை தருகிறது.',3),(2,'Which action protects nature?','පරිසරය රකින්නේ කුමක්ද?','இயற்கையைப் பாதுகாப்பது எது?','Littering','කසළ දැමීම','குப்பை போடுதல்','Planting trees','ගස් සිටුවීම','மரம் நடுதல்','Wasting water','ජලය නාස්ති කිරීම','நீரை வீணாக்குதல்','Burning plastic','ප්ලාස්ටික් පිළිස්සීම','பிளாஸ்டிக் எரித்தல்','b','Trees support habitats.','ගස් වාසස්ථාන සඳහා උපකාරී වේ.','மரங்கள் வாழிடங்களுக்கு உதவுகின்றன.',4),(2,'Water at room temperature is usually?','කාමර උෂ්ණත්වයේ ජලය සාමාන්‍යයෙන්?','அறை வெப்பநிலையில் நீர்?','Solid','ඝන','திண்மம்','Liquid','ද්‍රව','திரவம்','Gas','වායු','வாயு','Energy','ශක්තිය','ஆற்றல்','b','Water flows as a liquid.','ජලය ද්‍රවයක් ලෙස ගලා යයි.','நீர் திரவமாக ஓடுகிறது.',5),
(3,'Which device shows output?','ප්‍රතිදානය පෙන්වන්නේ කුමක්ද?','வெளியீட்டைக் காட்டுவது எது?','Keyboard','යතුරුපුවරුව','விசைப்பலகை','Monitor','මොනිටරය','திரை','Mouse','මූසිකය','சுட்டி','Microphone','මයික්‍රොෆෝනය','ஒலிவாங்கி','b','A monitor displays visual output.','මොනිටරය දෘශ්‍ය ප්‍රතිදානය පෙන්වයි.','திரை காட்சி வெளியீட்டைக் காட்டும்.',1),(3,'Which is an input device?','ආදාන උපාංගයක් කුමක්ද?','உள்ளீட்டு சாதனம் எது?','Printer','මුද්‍රකය','அச்சுப்பொறி','Speaker','ස්පීකරය','ஒலிபெருக்கி','Keyboard','යතුරුපුවරුව','விசைப்பலகை','Monitor','මොනිටරය','திரை','c','A keyboard sends typed input.','යතුරුපුවරුව ටයිප් කළ ආදානය යවයි.','விசைப்பலகை தட்டச்சு உள்ளீட்டை அனுப்பும்.',2),(3,'A strong password should be?','ශක්තිමත් මුරපදයක් විය යුත්තේ?','வலுவான கடவுச்சொல் எப்படி?','Easy to guess','අනුමාන කිරීමට පහසු','ஊகிக்க எளிதானது','Shared publicly','ප්‍රසිද්ධියේ බෙදාගත්','பகிரங்கமாக பகிர்ந்தது','Long and unique','දිගු හා සුවිශේෂී','நீளமானதும் தனித்துவமானதும்','Your name','ඔබේ නම','உங்கள் பெயர்','c','Long unique passwords are safer.','දිගු සුවිශේෂී මුරපද වඩා ආරක්ෂිතය.','நீளமான தனித்துவமான கடவுச்சொற்கள் பாதுகாப்பானவை.',3),(3,'What stores a file?','ගොනුවක් ගබඩා කරන්නේ කුමක්ද?','கோப்பைச் சேமிப்பது எது?','Storage device','ගබඩා උපාංගය','சேமிப்புச் சாதனம்','Chair','පුටුව','நாற்காலி','Desk','මේසය','மேசை','Cable only','කේබලයක් පමණි','கம்பி மட்டும்','a','Storage keeps digital files.','ගබඩාව ඩිජිටල් ගොනු තබා ගනී.','சேமிப்பு டிஜிட்டல் கோப்புகளை வைத்திருக்கும்.',4),(3,'For safe use, take regular?','ආරක්ෂිත භාවිතයට නිතර ගත යුත්තේ?','பாதுகாப்பான பயன்பாட்டிற்கு எடுக்க வேண்டியது?','Breaks','විවේක','இடைவேளைகள்','Passwords from friends','මිතුරන්ගේ මුරපද','நண்பர்களின் கடவுச்சொற்கள்','Unknown downloads','නොදන්නා බාගැනීම්','தெரியாத பதிவிறக்கங்கள்','Personal data requests','පුද්ගලික දත්ත ඉල්ලීම්','தனிப்பட்ட தரவு கோரல்கள்','a','Breaks protect eyes and posture.','විවේක ඇස් හා ඉරියව් රකියි.','இடைவேளைகள் கண்களையும் உடல்நிலையையும் பாதுகாக்கும்.',5);
-- Create the first admin safely: generate a hash with PHP, then run:
-- C:\xampp\php\php.exe -r "echo password_hash('Choose-A-Strong-Password', PASSWORD_DEFAULT), PHP_EOL;"
-- INSERT INTO admins(full_name,username,email,password_hash,role) VALUES('Administrator','admin','admin@example.com','PASTE_HASH_HERE','super_admin');
