<?php
declare(strict_types=1);define('TEXTBOOK_IMPORT_LIBRARY_ONLY',true);require_once __DIR__.'/import_textbook_learning.php';$db=db();
$db->query("INSERT INTO grades(grade_number,name,status) SELECT 7,'Grade 7','active' WHERE NOT EXISTS(SELECT 1 FROM grades WHERE grade_number=7)");
$grade=(int)query_one('SELECT id FROM grades WHERE grade_number=7')['id'];
$needed=['Mathematics','Science','History','ICT','Health and Physical Education','Civic Education'];
foreach($needed as $name){$source=query_one('SELECT * FROM subjects WHERE grade_id=1 AND name_en=?','s',[$name]);if(!$source)throw new RuntimeException("Missing subject template: $name");if(!query_one('SELECT id FROM subjects WHERE grade_id=? AND name_en=?','is',[$grade,$name])){$s=$db->prepare('INSERT INTO subjects(grade_id,subject_code,name_en,name_si,name_ta,description_en,description_si,description_ta,icon,status) VALUES(?,?,?,?,?,?,?,?,?,"active")');$code=$source['subject_code'].'7';$s->bind_param('issssssss',$grade,$code,$source['name_en'],$source['name_si'],$source['name_ta'],$source['description_en'],$source['description_si'],$source['description_ta'],$source['icon']);$s->execute();}}
$subjects=[];foreach($db->query("SELECT id,name_en FROM subjects WHERE grade_id=$grade") as $r)$subjects[mb_strtolower($r['name_en'])]=(int)$r['id'];
$catalog=json_decode((string)file_get_contents(__DIR__.'/../uploads/syllabus/textbook-cache/grade-7/en/catalog.json'),true,512,JSON_THROW_ON_ERROR);$lessonCount=$quizCount=$questionCount=0;$db->begin_transaction();
try{foreach($catalog as $slug=>$book){$subjectId=$subjects[mb_strtolower((string)$book['subject'])]??0;if(!$subjectId)throw new RuntimeException('Missing Grade 7 subject '.$book['subject']);foreach($book['lessons'] as $entry){$number=(int)$entry['number'];$title=(string)$entry['title'];$file=__DIR__.'/../uploads/syllabus/textbook-cache/grade-7/en/'.$slug.'/lesson-'.$number.'.json';$study=notes_and_quiz(json_decode((string)file_get_contents($file),true,512,JSON_THROW_ON_ERROR),$title,'en');
 $unit=query_one('SELECT id FROM units WHERE grade_id=? AND subject_id=? AND unit_number=?','iii',[$grade,$subjectId,$number]);if(!$unit){$s=$db->prepare('INSERT INTO units(grade_id,subject_id,unit_number,name_en,name_si,name_ta,description_en,display_order,status) VALUES(?,?,?,?,?,?,?,?,"active")');$s->bind_param('iiissssi',$grade,$subjectId,$number,$title,$title,$title,$study['description'],$number);$s->execute();$unitId=(int)$db->insert_id;}else{$unitId=(int)$unit['id'];$s=$db->prepare('UPDATE units SET name_en=?,description_en=?,display_order=?,status="active" WHERE id=?');$s->bind_param('ssii',$title,$study['description'],$number,$unitId);$s->execute();}
 $lesson=query_one("SELECT id FROM lessons WHERE grade_id=? AND unit_id=? AND medium='English' ORDER BY id LIMIT 1",'ii',[$grade,$unitId]);if($lesson)$lessonId=(int)$lesson['id'];else{$s=$db->prepare('INSERT INTO lessons(grade_id,medium,subject_id,unit_id,display_order,status) VALUES(?,"English",?,?,?,"active")');$s->bind_param('iiii',$grade,$subjectId,$unitId,$number);$s->execute();$lessonId=(int)$db->insert_id;}
 $objectives="Understand $title.\nExplain its main ideas.\nUse the lesson knowledge in revision activities.";$s=$db->prepare("UPDATE lessons SET content_source='textbook',title_en=?,short_description_en=?,content_en=?,learning_objectives_en=?,key_terms_en=?,examples_en=?,summary_en=?,display_order=?,status='active' WHERE id=?");$s->bind_param('sssssssii',$title,$study['description'],$study['content'],$objectives,$study['terms'],$study['examples'],$study['summary'],$number,$lessonId);$s->execute();$lessonCount++;
 $quiz=query_one('SELECT id FROM quizzes WHERE lesson_id=? ORDER BY id LIMIT 1','i',[$lessonId]);if($quiz)$quizId=(int)$quiz['id'];else{$s=$db->prepare('INSERT INTO quizzes(grade_id,subject_id,unit_id,lesson_id,timer_minutes,pass_mark,status) VALUES(?,?,?,?,10,50,"active")');$s->bind_param('iiii',$grade,$subjectId,$unitId,$lessonId);$s->execute();$quizId=(int)$db->insert_id;}$quizTitle=$title.' Revision Quiz';$s=$db->prepare('UPDATE quizzes SET title_en=?,status="active" WHERE id=?');$s->bind_param('si',$quizTitle,$quizId);$s->execute();$quizCount++;
 $existing=[];$qs=$db->prepare('SELECT id FROM quiz_questions WHERE quiz_id=? ORDER BY display_order,id');$qs->bind_param('i',$quizId);$qs->execute();foreach($qs->get_result() as $r)$existing[]=(int)$r['id'];foreach($study['questions'] as $i=>$q){$o=$q['options'];$pos=$i+1;if(isset($existing[$i])){$id=$existing[$i];$s=$db->prepare('UPDATE quiz_questions SET question_en=?,option_a_en=?,option_b_en=?,option_c_en=?,option_d_en=?,correct_option=?,explanation_en=?,display_order=?,status="active" WHERE id=?');$s->bind_param('sssssssii',$q['question'],$o[0],$o[1],$o[2],$o[3],$q['correct'],$q['explanation'],$pos,$id);}else{$s=$db->prepare('INSERT INTO quiz_questions(quiz_id,question_en,option_a_en,option_b_en,option_c_en,option_d_en,correct_option,explanation_en,display_order,status) VALUES(?,?,?,?,?,?,?,?,?,"active")');$s->bind_param('isssssssi',$quizId,$q['question'],$o[0],$o[1],$o[2],$o[3],$q['correct'],$q['explanation'],$pos);}$s->execute();$questionCount++;}
 }}$db->commit();echo "Grade 7 imported $lessonCount lessons, $quizCount quizzes and $questionCount questions.\n";}catch(Throwable $e){$db->rollback();throw $e;}
