<?php
declare(strict_types=1);define('TEXTBOOK_IMPORT_LIBRARY_ONLY',true);require_once __DIR__.'/import_textbook_learning.php';$db=db();$lessonCount=$quizCount=$questionCount=0;
foreach([[7,'si','Sinhala'],[8,'en','English'],[9,'en','English']] as [$gradeNumber,$language,$medium]){
 $catalogFile=__DIR__."/../uploads/syllabus/textbook-cache/grade-$gradeNumber/$language/catalog.json";if(!is_file($catalogFile))throw new RuntimeException("Missing catalog for Grade $gradeNumber $medium");
 $db->query("INSERT INTO grades(grade_number,name,status) SELECT $gradeNumber,'Grade $gradeNumber','active' WHERE NOT EXISTS(SELECT 1 FROM grades WHERE grade_number=$gradeNumber)");$grade=(int)query_one('SELECT id FROM grades WHERE grade_number=?','i',[$gradeNumber])['id'];$catalog=json_decode((string)file_get_contents($catalogFile),true,512,JSON_THROW_ON_ERROR);
 foreach($catalog as $slug=>$book){$name=(string)$book['subject'];$subject=query_one('SELECT id FROM subjects WHERE grade_id=? AND name_en=?','is',[$grade,$name]);
  if(!$subject){$template=query_one('SELECT * FROM subjects WHERE name_en=? ORDER BY grade_id LIMIT 1','s',[$name]);$code=strtoupper(substr(preg_replace('/[^A-Za-z]/','',$slug),0,5)).$gradeNumber;$nameSi=$template['name_si']??$name;$nameTa=$template['name_ta']??$name;$descEn=$template['description_en']??("Grade $gradeNumber $name textbook learning.");$descSi=$template['description_si']??$descEn;$descTa=$template['description_ta']??$descEn;$icon=$template['icon']??'📘';$s=$db->prepare('INSERT INTO subjects(grade_id,subject_code,name_en,name_si,name_ta,description_en,description_si,description_ta,icon,status) VALUES(?,?,?,?,?,?,?,?,?,"active")');$s->bind_param('issssssss',$grade,$code,$name,$nameSi,$nameTa,$descEn,$descSi,$descTa,$icon);$s->execute();$subjectId=(int)$db->insert_id;}else $subjectId=(int)$subject['id'];
  foreach($book['lessons'] as $entry){$number=(int)$entry['number'];$title=(string)$entry['title'];$file=__DIR__."/../uploads/syllabus/textbook-cache/grade-$gradeNumber/$language/$slug/lesson-$number.json";$study=notes_and_quiz(json_decode((string)file_get_contents($file),true,512,JSON_THROW_ON_ERROR),$title,$language);
   $unit=query_one('SELECT id FROM units WHERE grade_id=? AND subject_id=? AND unit_number=?','iii',[$grade,$subjectId,$number]);if($unit)$unitId=(int)$unit['id'];else{$s=$db->prepare('INSERT INTO units(grade_id,subject_id,unit_number,name_en,name_si,name_ta,description_en,display_order,status) VALUES(?,?,?,?,?,?,?,?,"active")');$s->bind_param('iiissssi',$grade,$subjectId,$number,$title,$title,$title,$study['description'],$number);$s->execute();$unitId=(int)$db->insert_id;}
   $lesson=query_one('SELECT id FROM lessons WHERE grade_id=? AND unit_id=? AND medium=? LIMIT 1','iis',[$grade,$unitId,$medium]);if($lesson)$lessonId=(int)$lesson['id'];else{$s=$db->prepare('INSERT INTO lessons(grade_id,medium,subject_id,unit_id,display_order,status) VALUES(?,?,?,?,?,"active")');$s->bind_param('isiii',$grade,$medium,$subjectId,$unitId,$number);$s->execute();$lessonId=(int)$db->insert_id;}
   $field=$language==='si'?'si':'en';$objectives=$language==='si'?'මෙම පෙළපොතේ ප්‍රධාන අදහස් තේරුම් ගෙන පුනරීක්ෂණයේදී භාවිත කරන්න.':"Understand the main ideas in $title and use them in revision.";$sql="UPDATE lessons SET content_source='textbook',title_$field=?,short_description_$field=?,content_$field=?,learning_objectives_$field=?,key_terms_$field=?,examples_$field=?,summary_$field=?,display_order=?,status='active' WHERE id=?";$s=$db->prepare($sql);$s->bind_param('sssssssii',$title,$study['description'],$study['content'],$objectives,$study['terms'],$study['examples'],$study['summary'],$number,$lessonId);$s->execute();$lessonCount++;
   $quiz=query_one('SELECT id FROM quizzes WHERE lesson_id=? LIMIT 1','i',[$lessonId]);if($quiz)$quizId=(int)$quiz['id'];else{$s=$db->prepare('INSERT INTO quizzes(grade_id,subject_id,unit_id,lesson_id,timer_minutes,pass_mark,status) VALUES(?,?,?,?,10,50,"active")');$s->bind_param('iiii',$grade,$subjectId,$unitId,$lessonId);$s->execute();$quizId=(int)$db->insert_id;}$quizTitle=$title.' Revision Quiz';$s=$db->prepare("UPDATE quizzes SET title_$field=?,status='active' WHERE id=?");$s->bind_param('si',$quizTitle,$quizId);$s->execute();$quizCount++;
   $db->query("DELETE FROM quiz_questions WHERE quiz_id=$quizId");foreach($study['questions'] as $i=>$q){$o=$q['options'];$pos=$i+1;$sql="INSERT INTO quiz_questions(quiz_id,question_$field,option_a_$field,option_b_$field,option_c_$field,option_d_$field,correct_option,explanation_$field,display_order,status) VALUES(?,?,?,?,?,?,?,?,?,\"active\")";$s=$db->prepare($sql);$s->bind_param('isssssssi',$quizId,$q['question'],$o[0],$o[1],$o[2],$o[3],$q['correct'],$q['explanation'],$pos);$s->execute();$questionCount++;}
  }
 }
}
echo "Imported $lessonCount textbook units, $quizCount quizzes and $questionCount questions for the added grades.\n";
