<?php
declare(strict_types=1);
ini_set('session.save_path',__DIR__.'/../includes/runtime');require_once __DIR__.'/../includes/db.php';
$sets=json_decode((string)file_get_contents(__DIR__.'/data/grade6-sinhala-lessons1-7.json'),true,512,JSON_THROW_ON_ERROR);
if(count($sets)!==7)throw new RuntimeException('Expected seven lesson sets.');$db=db();$db->begin_transaction();
try{
 $lesson=$db->prepare("SELECT l.id FROM lessons l JOIN grades g ON g.id=l.grade_id JOIN subjects s ON s.id=l.subject_id WHERE g.grade_number=6 AND s.name_en='Sinhala' AND l.medium='Sinhala' AND l.display_order=? AND l.status='active' LIMIT 1");
 $quiz=$db->prepare("SELECT id FROM quizzes WHERE lesson_id=? AND status='active' LIMIT 1");$ids=$db->prepare("SELECT id FROM quiz_questions WHERE quiz_id=? AND activity_type='challenge'");$delAnswers=$db->prepare('DELETE FROM quiz_answers WHERE question_id=?');$del=$db->prepare("DELETE FROM quiz_questions WHERE quiz_id=? AND activity_type='challenge'");
 $add=$db->prepare("INSERT INTO quiz_questions(quiz_id,activity_type,question_si,option_a_si,option_b_si,option_c_si,option_d_si,correct_option,explanation_si,display_order,status) VALUES(?,'challenge',?,?,?,?,?,?,?,?,'active')");$update=$db->prepare('UPDATE quizzes SET title_si=?,timer_minutes=30,pass_mark=50 WHERE id=?');
 foreach(range(1,7) as $order){$questions=$sets[(string)$order]['questions']??[];if(count($questions)!==30)throw new RuntimeException("Lesson $order does not contain 30 questions.");$lesson->bind_param('i',$order);$lesson->execute();$lr=$lesson->get_result()->fetch_assoc();if(!$lr)throw new RuntimeException("Sinhala lesson $order missing.");$lid=(int)$lr['id'];$quiz->bind_param('i',$lid);$quiz->execute();$qr=$quiz->get_result()->fetch_assoc();if(!$qr)throw new RuntimeException("Quiz for lesson $order missing.");$qid=(int)$qr['id'];$ids->bind_param('i',$qid);$ids->execute();$old=$ids->get_result();while($row=$old->fetch_assoc()){$questionId=(int)$row['id'];$delAnswers->bind_param('i',$questionId);$delAnswers->execute();}$del->bind_param('i',$qid);$del->execute();foreach($questions as $i=>$q){$position=$i+1;$explanation='නිවැරදි පිළිතුර: '.strtoupper($q['correct']);$add->bind_param('isssssssi',$qid,$q['question'],$q['a'],$q['b'],$q['c'],$q['d'],$q['correct'],$explanation,$position);$add->execute();}$title='6 ශ්‍රේණිය සිංහල – '.$order.' වන පාඩම – බහුවරණ ප්‍රශ්න 30ක්';$update->bind_param('si',$title,$qid);$update->execute();echo "Lesson $order: 30 questions updated.\n";}
 $db->commit();
}catch(Throwable $e){$db->rollback();fwrite(STDERR,$e->getMessage()."\n");exit(1);}
