<?php
declare(strict_types=1);require_once __DIR__.'/../includes/db.php';$db=db();$fail=[];
$progressSql="SELECT qa.id,qa.score,qa.total_questions,qa.percentage,qa.passed,qa.completed_at,q.title_en,q.title_si,q.title_ta FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id JOIN lessons l ON l.id=q.lesson_id WHERE qa.user_id=? AND l.content_source='textbook' ORDER BY qa.completed_at DESC LIMIT 8";
if(!$db->prepare($progressSql))$fail[]='progress recent attempts query: '.$db->error;
$expected=['English'=>72,'Sinhala'=>99,'Tamil'=>86];
foreach($expected as $medium=>$count){$s=$db->prepare("SELECT COUNT(*) n FROM lessons WHERE grade_id=1 AND medium=? AND content_source='textbook' AND status='active'");$s->bind_param('s',$medium);$s->execute();$actual=(int)$s->get_result()->fetch_assoc()['n'];if($actual!==$count)$fail[]="$medium lessons: expected $count, found $actual";}
$notes=(int)$db->query("SELECT COUNT(*) n FROM lessons WHERE content_source='textbook' AND status='active' AND ((medium='English' AND COALESCE(content_en,'')='') OR (medium='Sinhala' AND COALESCE(content_si,'')='') OR (medium='Tamil' AND COALESCE(content_ta,'')=''))")->fetch_assoc()['n'];
if($notes)$fail[]="lessons without notes: $notes";
$quizGroups=$db->query("SELECT l.id FROM lessons l LEFT JOIN quizzes q ON q.lesson_id=l.id AND q.status='active' WHERE l.content_source='textbook' AND l.status='active' GROUP BY l.id HAVING COUNT(q.id)<>1")->num_rows;if($quizGroups)$fail[]="lessons without one active quiz: $quizGroups";
$questionGroups=$db->query("SELECT q.id FROM quizzes q JOIN lessons l ON l.id=q.lesson_id LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id AND qq.status='active' WHERE l.content_source='textbook' AND q.status='active' GROUP BY q.id HAVING COUNT(qq.id)<>5")->num_rows;if($questionGroups)$fail[]="quizzes without five active questions: $questionGroups";
foreach(['English'=>7,'Sinhala'=>10,'Tamil'=>7] as $medium=>$expectedSubjects){$safe=$db->real_escape_string($medium);$actual=(int)$db->query("SELECT COUNT(DISTINCT subject_id) n FROM lessons WHERE grade_id=1 AND medium='$safe' AND content_source='textbook' AND status='active'")->fetch_assoc()['n'];if($actual!==$expectedSubjects)$fail[]="$medium textbook subjects: expected $expectedSubjects, found $actual";}
$sinhalaRows=$db->query("SELECT l.title_si,l.content_si,qq.question_si FROM lessons l JOIN quizzes q ON q.lesson_id=l.id AND q.status='active' JOIN quiz_questions qq ON qq.quiz_id=q.id AND qq.status='active' WHERE l.medium='Sinhala' AND l.content_source='textbook'");while($row=$sinhalaRows->fetch_assoc()){foreach(['title_si','content_si','question_si'] as $field)if(!preg_match('/[\x{0D80}-\x{0DFF}]/u',(string)$row[$field])){$fail[]="Sinhala Unicode missing in $field";break 2;}}
$tamilRows=$db->query("SELECT l.title_ta,l.content_ta,qq.question_ta FROM lessons l JOIN quizzes q ON q.lesson_id=l.id AND q.status='active' JOIN quiz_questions qq ON qq.quiz_id=q.id AND qq.status='active' WHERE l.medium='Tamil' AND l.content_source='textbook'");while($row=$tamilRows->fetch_assoc()){foreach(['title_ta','content_ta','question_ta'] as $field)if(!preg_match('/[\x{0B80}-\x{0BFF}\x{0D80}-\x{0DFF}]/u',(string)$row[$field])){$fail[]="Tamil-medium Unicode missing in $field";break 2;}}
if($fail){fwrite(STDERR,"FAILED\n- ".implode("\n- ",$fail)."\n");exit(1);}echo "PASS: 257 textbook lessons, 257 quizzes, 1285 active questions, and all notes are present.\n";
