<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';
require_login();
$lessonId=filter_input(INPUT_GET,'lesson_id',FILTER_VALIDATE_INT);$mode=(string)($_GET['mode']??'');$allowed=['challenge','missing','matching'];$names=['challenge'=>'Quick Challenge','missing'=>'Fill the Missing Answer','matching'=>'Matching Mission'];
$lesson=$lessonId?query_one("SELECT l.*,s.name_en,s.name_si,s.name_ta FROM lessons l JOIN subjects s ON s.id=l.subject_id WHERE l.id=? AND l.grade_id=? AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)",'iis',[$lessonId,user()['grade_id'],user()['medium']]):null;
if(!$lesson){flash('error','Choose a valid textbook lesson.');redirect('student/subjects.php');}
$quiz=query_one("SELECT id FROM quizzes WHERE lesson_id=? AND status='active' ORDER BY id LIMIT 1",'i',[$lessonId]);$questions=[];
if($quiz&&in_array($mode,$allowed,true)){$s=db()->prepare("SELECT * FROM quiz_questions WHERE quiz_id=? AND activity_type=? AND status='active' ORDER BY display_order,id");$s->bind_param('is',$quiz['id'],$mode);$s->execute();$questions=$s->get_result()->fetch_all(MYSQLI_ASSOC);}
if(in_array($mode,$allowed,true)&&!$questions){flash('warning',$names[$mode].' questions are not available for this lesson yet.');redirect('student/activities.php?lesson_id='.$lessonId);}
if(!in_array($mode,$allowed,true)){$pageTitle='Practice Lab';include __DIR__.'/../includes/header.php';?>
<p><a href="lesson.php?id=<?=$lessonId?>">&larr; <?=e(locale_value($lesson,'title'))?></a></p><section class="card"><span class="badge"><?=e(locale_value($lesson,'name'))?></span><h1>🎮 Practice Lab</h1><p class="muted">Choose an activity. Each one uses this lesson's textbook revision content and gives immediate feedback.</p></section>
<div class="grid activity-grid"><a class="card activity-choice" href="?lesson_id=<?=$lessonId?>&amp;mode=challenge"><b>⚡</b><h2>Quick Challenge</h2><p>Answer five questions and see your score.</p></a><a class="card activity-choice" href="?lesson_id=<?=$lessonId?>&amp;mode=missing"><b>✍️</b><h2>Missing Answer</h2><p>Complete each idea with the correct answer.</p></a><a class="card activity-choice" href="?lesson_id=<?=$lessonId?>&amp;mode=matching"><b>🧩</b><h2>Matching Mission</h2><p>Match each lesson question to its answer.</p></a></div><style>.activity-choice{text-decoration:none;color:inherit}.activity-choice>b{font-size:2.5rem}.activity-choice h2{margin:.35rem 0}.activity-choice p{color:var(--muted)}</style>
<?php include __DIR__.'/../includes/footer.php';exit;}
$lang=['Sinhala'=>'si','Tamil'=>'ta','English'=>'en'][user()['medium']]??'en';
function activity_text(array $r,string $base,string $lang):string{$v=trim((string)($r[$base.'_'.$lang]??''));return $v!==''?$v:trim((string)($r[$base.'_en']??''));}
$result=null;if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$answers=$_POST['answers']??[];$score=0;foreach($questions as $q)if(($answers[(string)$q['id']]??'')===(string)$q['correct_option'])$score++;$result=['score'=>$score,'total'=>count($questions),'percentage'=>(int)round($score*100/count($questions))];record_student_activity((int)user()['id'],'quiz_completed',$names[$mode].' - '.$result['percentage'].'%',(int)$lesson['subject_id'],$lessonId,(int)$quiz['id']);}
$answerPool=[];foreach($questions as $q){$o=(string)$q['correct_option'];$answerPool[]=activity_text($q,'option_'.$o,$lang);}shuffle($answerPool);
$pageTitle=$names[$mode];include __DIR__.'/../includes/header.php';?>
<p><a href="activities.php?lesson_id=<?=$lessonId?>">&larr; Practice Lab</a></p><section class="card"><span class="badge"><?=e(locale_value($lesson,'name'))?></span><h1><?=$mode==='challenge'?'⚡':($mode==='missing'?'✍️':'🧩')?> <?=e($names[$mode])?></h1><p><?=e(locale_value($lesson,'title'))?></p><div class="progress"><span id="activityProgress" style="width:0"></span></div></section>
<?php if($result):?><section class="card result-card"><h2><?=$result['percentage']>=60?'Great work! 🎉':'Keep practising 💪'?></h2><div class="activity-score"><?=$result['score']?> / <?=$result['total']?></div><p>You scored <?=$result['percentage']?>%.</p><div class="row"><a class="btn" href="?lesson_id=<?=$lessonId?>&amp;mode=<?=e($mode)?>">Try again</a><a class="btn alt" href="lesson.php?id=<?=$lessonId?>">Back to lesson</a></div></section><?php endif;?>
<form method="post" class="card" id="activityForm"><?=csrf_field()?><?php foreach($questions as $i=>$q):$qid=(string)$q['id'];$prompt=activity_text($q,'question',$lang);?><fieldset class="activity-question"><legend><span><?=($i+1)?></span> <?=e($mode==='missing'?'Choose the missing answer: '.$prompt:$prompt)?></legend>
<?php if($mode==='matching'):$correctAnswer=activity_text($q,'option_'.(string)$q['correct_option'],$lang);?><label for="answer<?=$qid?>">Matching answer</label><select id="answer<?=$qid?>" name="answers[<?=$qid?>]" required><option value="">Select the matching answer...</option><?php foreach($answerPool as $poolIndex=>$answer):$value=$answer===$correctAnswer?(string)$q['correct_option']:'wrong_'.$poolIndex;?><option value="<?=e($value)?>"><?=e($answer)?></option><?php endforeach;?></select>
<?php else:foreach(['a','b','c','d'] as $o):?><label class="answer-tile"><input type="radio" name="answers[<?=$qid?>]" value="<?=$o?>" required><span><?=e(activity_text($q,'option_'.$o,$lang))?></span></label><?php endforeach;endif;?></fieldset><?php endforeach;?><button type="submit">Check my answers</button></form>
<style>.activity-question{border:0;border-bottom:1px solid var(--line);padding:18px 0;margin:0}.activity-question legend{font-weight:900;font-size:1.05rem}.activity-question legend span{display:inline-grid;place-items:center;width:31px;height:31px;border-radius:10px;background:#efedff;color:var(--violet);margin-right:7px}.answer-tile{display:flex;align-items:center;gap:10px;padding:12px 14px;margin:8px 0;border:1.5px solid var(--line);border-radius:15px;cursor:pointer}.answer-tile:has(input:checked){border-color:var(--violet);background:#f3f1ff}.answer-tile input{width:auto;min-height:auto;margin:0}.activity-score{font-size:3.2rem;font-weight:950;color:var(--violet)}</style><script>const f=document.getElementById('activityForm'),bar=document.getElementById('activityProgress');function progress(){const groups=new Set([...f.querySelectorAll('input:checked,select')].filter(x=>x.value).map(x=>x.name));bar.style.width=Math.round(groups.size/<?=count($questions)?>*100)+'%'}f.addEventListener('change',progress);progress();</script>
<?php include __DIR__.'/../includes/footer.php';
