<?php
require_once __DIR__ . '/../includes/auth.php';
require_login();
refresh_user();
$uid=(int)user()['id'];
$medium=(string)user()['medium'];$gradeNumber=user_grade_number();
$stats=query_one("SELECT COUNT(*) opened,SUM(lp.completed_at IS NOT NULL) completed FROM lesson_progress lp JOIN lessons l ON l.id=lp.lesson_id WHERE lp.user_id=? AND l.content_source='textbook' AND l.status='active' AND (l.medium='All' OR l.medium=?)",'is',[$uid,user()['medium']])??['opened'=>0,'completed'=>0];
$total=(int)(query_one("SELECT COUNT(*) n FROM lessons WHERE grade_id=? AND status='active' AND content_source='textbook' AND (medium='All' OR medium=?)",'is',[(int)user()['grade_id'],user()['medium']])['n']??0);
$completed=(int)($stats['completed']??0);$pct=$total?min(100,round(100*$completed/$total)):0;
$last=query_one('SELECT qa.score,qa.total_questions,qa.percentage FROM quiz_attempts qa WHERE qa.user_id=? ORDER BY qa.completed_at DESC LIMIT 1','i',[$uid]);
$points=(int)(query_one('SELECT COALESCE(SUM(points),0) total FROM student_points WHERE user_id=?','i',[$uid])['total']??0);
$recentStatement=db()->prepare("SELECT l.id,l.title_en,l.title_si,l.title_ta,s.name_en,s.name_si,s.name_ta FROM lesson_progress lp JOIN lessons l ON l.id=lp.lesson_id JOIN subjects s ON s.id=l.subject_id WHERE lp.user_id=? AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?) ORDER BY lp.last_opened_at DESC LIMIT 3");
$recentRows=[];if($recentStatement){$recentStatement->bind_param('is',$uid,$medium);$recentStatement->execute();$recentRows=$recentStatement->get_result()->fetch_all(MYSQLI_ASSOC);}
$pageTitle=tr('dashboard');include __DIR__.'/../includes/header.php';
$showOnboarding=!empty($_SESSION['new_student_onboarding'])||filter_input(INPUT_GET,'tour',FILTER_VALIDATE_INT)===1;unset($_SESSION['new_student_onboarding']);
?>
<style>
.hero{color:#fff;background:linear-gradient(135deg,#5545d5 0%,#6e55ec 43%,#2588f6 100%);padding:25px;min-height:245px}.hero:before{content:"";position:absolute;width:240px;height:240px;border-radius:50%;right:-75px;top:-95px;background:rgba(255,255,255,.11)}.hero:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:85px;bottom:-105px;background:rgba(255,255,255,.08)}.hero .badge{background:rgba(255,255,255,.16);color:#fff;border:1px solid rgba(255,255,255,.22)}.hero h1{margin:13px 0 5px;max-width:650px}.hero p{color:rgba(255,255,255,.82)}.hero-search{position:relative;z-index:2;margin-top:19px}.hero-search input{margin:0;background:#fff;border:0;padding-left:48px;box-shadow:0 12px 30px rgba(28,30,80,.2)}.hero-search span{position:absolute;left:16px;top:12px;font-size:1.25rem}.statbar{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:18px}.stat{padding:12px 8px;border-radius:17px;background:rgba(255,255,255,.13);text-align:center;backdrop-filter:blur(7px)}.stat strong{display:block;font-size:1.25rem}.stat small{color:rgba(255,255,255,.75)}.section-head{display:flex;justify-content:space-between;align-items:end;gap:10px;margin:25px 3px 14px}.section-head h2{margin:0}.quick-card{display:flex;flex-direction:column;justify-content:space-between;text-decoration:none;color:inherit;isolation:isolate}.quick-card:before{content:"";position:absolute;inset:auto -35px -45px auto;width:105px;height:105px;border-radius:50%;background:var(--tint,#eee);opacity:.45;z-index:-1}.quick-icon{display:grid;place-items:center;width:57px;height:57px;border-radius:18px;background:var(--tint,#eeefff);font-size:1.8rem;box-shadow:inset 0 0 0 1px rgba(255,255,255,.75);transition:.25s}.quick-card:hover .quick-icon{transform:rotate(-6deg) scale(1.1)}.quick-card h3{margin:17px 0 4px}.quick-card p{margin:0;font-size:.83rem;color:var(--muted)}.continue-item{display:flex;gap:13px;align-items:center;padding:13px 0;border-bottom:1px solid var(--line);text-decoration:none;color:inherit}.continue-item:last-child{border:0}.continue-icon{display:grid;place-items:center;flex:0 0 45px;height:45px;border-radius:14px;background:#efedff}.continue-item strong{display:block}.continue-item small{color:var(--muted)}.continue-item i{margin-left:auto;font-style:normal;color:var(--violet);font-size:1.2rem}@media(min-width:720px){.hero{padding:34px}.statbar{max-width:540px}.quick-card{min-height:190px}}
.statbar{grid-template-columns:repeat(2,1fr)}@media(min-width:720px){.statbar{grid-template-columns:repeat(4,1fr);max-width:720px}}
.tour-overlay{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;padding:18px;background:rgba(15,20,48,.67);backdrop-filter:blur(9px)}.tour-box{position:relative;width:min(560px,100%);overflow:hidden;border-radius:30px;background:#fff;box-shadow:0 35px 100px rgba(8,13,43,.42)}.tour-top{height:155px;display:grid;place-items:center;background:radial-gradient(circle at 75% 20%,rgba(255,182,56,.42),transparent 30%),linear-gradient(135deg,#25206d,#6554e8 58%,#178bc1);color:#fff}.tour-emoji{font-size:4rem;filter:drop-shadow(0 10px 15px rgba(0,0,0,.2));animation:tourFloat 1.8s ease-in-out infinite}.tour-body{padding:27px;text-align:center}.tour-step{display:none}.tour-step.active{display:block;animation:reveal .35s both}.tour-step h2{font-size:1.75rem;margin:0 0 9px}.tour-step p{max-width:440px;margin:0 auto;color:var(--muted)}.tour-dots{display:flex;justify-content:center;gap:7px;margin:24px 0 18px}.tour-dot{width:9px;height:9px;border-radius:50%;background:#d9deea;transition:.25s}.tour-dot.active{width:28px;border-radius:99px;background:var(--violet)}.tour-controls{display:flex;justify-content:space-between;gap:10px}.tour-skip{background:transparent;color:var(--muted);box-shadow:none}.tour-skip:hover{box-shadow:none;background:#f3f4f8}.tour-next{margin-left:auto}.tour-progress{position:absolute;left:0;top:0;height:5px;background:linear-gradient(90deg,var(--gold),#ff7b2c);transition:width .3s}.tour-welcome{display:inline-block;margin-bottom:10px;color:var(--violet);font-size:.78rem;font-weight:900;text-transform:uppercase;letter-spacing:.08em}@keyframes tourFloat{50%{transform:translateY(-9px) rotate(4deg)}}@media(max-width:520px){.tour-top{height:125px}.tour-body{padding:22px 18px}.tour-step h2{font-size:1.45rem}.tour-controls button{min-height:45px;padding:9px 13px}}
.tour-overlay.coach{display:block;padding:0;background:rgba(12,17,42,.7);backdrop-filter:none}.tour-overlay.coach .tour-box{position:fixed;z-index:1003;width:min(390px,calc(100vw - 24px));overflow:visible;border-radius:23px;transition:left .28s ease,top .28s ease}.tour-overlay.coach .tour-top{display:none}.tour-overlay.coach .tour-body{padding:21px}.tour-overlay.coach .tour-step h2{font-size:1.35rem}.tour-target{position:relative!important;z-index:1002!important;border-radius:22px!important;box-shadow:0 0 0 5px #ffb638,0 0 0 9999px rgba(12,17,42,.62),0 18px 50px rgba(0,0,0,.35)!important;transform:scale(1.025)!important}.tour-pointer{position:fixed;z-index:1004;font-size:2.5rem;filter:drop-shadow(0 5px 6px rgba(0,0,0,.35));animation:pointerBounce .7s ease-in-out infinite alternate;pointer-events:none}@keyframes pointerBounce{to{transform:translateY(8px)}}@media(max-width:520px){.tour-overlay.coach .tour-box{width:calc(100vw - 18px)}.tour-target{transform:none!important}}
.tour-controls{flex-wrap:wrap}.tour-controls #tourVoice{background:#eef7ff;color:#315b83}.tour-controls #tourVoice[aria-pressed="false"]{background:#f3f4f8;color:var(--muted)}@media(max-width:520px){.tour-controls #tourSkip{order:3}.tour-controls #tourVoice{order:4;flex:1 1 100%}.tour-controls #tourBack{order:1}.tour-controls #tourNext{order:2}}
</style>
<section class="card hero">
<span class="sparkle" style="right:12%;top:22%"></span><span class="sparkle" style="right:29%;top:14%;animation-delay:.8s"></span>
<div class="row" style="justify-content:space-between;position:relative;z-index:2"><div><span class="badge">🎒 Grade <?=$gradeNumber?> · <?=e(user()['medium'])?></span><h1><?=tr('welcome')?>, <?=e(user()['full_name'])?>! 👋</h1><p>Your next little win starts right here.</p></div><a class="btn warn" href="<?=url('subscription.php')?>"><?=is_premium()?'⭐ Premium active':'✨ Unlock Premium · Rs. 250 / 30 days'?></a></div>
<form class="hero-search" action="lessons.php" data-tour="search"><span>🔎</span><input name="q" placeholder="<?=e(tr('search'))?>"></form>
<div class="statbar"><div class="stat"><strong><?=$pct?>%</strong><small><?=tr('progress')?></small></div><div class="stat"><strong><?=$completed?></strong><small>Completed</small></div><div class="stat"><strong><?=$points?></strong><small>Points</small></div><div class="stat"><strong><?=$last?(int)$last['percentage'].'%':'—'?></strong><small>Latest quiz</small></div></div>
</section>
<div class="section-head"><div><span class="badge">⚡ Quick access</span><h2>What will you learn today?</h2></div></div>
<section class="grid">
<?php $cards=[['🤖',tr('chat'),'Ask questions and learn together','chatbot/chat.php','#e8e4ff'],['📚',tr('subjects'),'Explore every Grade '.$gradeNumber.' subject','student/subjects.php','#e1f4ff'],['📖',tr('lessons'),'Continue your learning journey','student/lessons.php','#e5fbf4'],['🧠',tr('quizzes'),'Challenge yourself and improve','student/quiz.php','#fff2d8'],['🏆','Leaderboard','Earn points and lesson emblems','student/leaderboard.php','#fff0c9'],['📈',tr('progress'),'Watch your knowledge grow','student/progress.php','#ffe8ee'],['👤',tr('profile'),'Languages, photo and account','profile.php','#eeeaff']];foreach($cards as $c):?>
<a class="card quick-card" data-tour="<?=e(pathinfo($c[3],PATHINFO_FILENAME))?>" style="--tint:<?=$c[4]?>" href="<?=url($c[3])?>"><div class="quick-icon"><?=$c[0]?></div><div><h3><?=e($c[1])?></h3><p><?=e($c[2])?></p></div></a>
<?php endforeach;?>
<a class="card quick-card" data-tour="parent_access" style="--tint:#e5fbf4" href="<?=url('student/parent_access.php')?>"><div class="quick-icon">👪</div><div><h3>Parent access</h3><p>Safely link a parent or guardian</p></div></a>
</section>
<div class="section-head"><h2>🚀 Continue learning</h2><a href="lessons.php">View all →</a></div>
<section class="card">
<?php if(!$recentRows):?><div style="text-align:center;padding:18px"><div style="font-size:3rem">🌱</div><h3>Your journey is ready</h3><p class="muted">Open your first lesson and it will appear here.</p><a class="btn" href="subjects.php">Explore subjects</a></div><?php endif;?>
<?php foreach($recentRows as $r):?><a class="continue-item" href="lesson.php?id=<?=(int)$r['id']?>"><span class="continue-icon">📘</span><span><strong><?=e(locale_value($r,'title'))?></strong><small><?=e(locale_value($r,'name'))?></small></span><i>›</i></a><?php endforeach;?>
</section>
<?php if($showOnboarding):$tourLanguage=medium_language($medium);$tourCopy=$tourLanguage==='si'?
 ['welcome'=>'K Education වෙත සාදරයෙන් පිළිගනිමු','skip'=>'මඟ පෙන්වීම මඟ හරින්න','back'=>'← ආපසු','next'=>'ඊළඟ →','start'=>'විෂයයන් බලන්න →','sound'=>'🔊 හඬ සක්‍රියයි','muted'=>'🔇 හඬ අක්‍රියයි']:
 ['welcome'=>'Welcome to K Education','skip'=>'Skip guide','back'=>'← Back','next'=>'Next →','start'=>'Explore subjects →','sound'=>'🔊 Voice on','muted'=>'🔇 Voice off'];
$tourSteps=$tourLanguage==='si'?[
 ['සාදරයෙන් පිළිගනිමු, '.user()['full_name'].'!','වැදගත් සෑම කොටසක්ම අපි ඔබට පෙන්වන්නෙමු. එක් එක් කොටසෙන් කළ හැකි දේ දැනගැනීමට ඊතලය අනුගමනය කරන්න.','👋',''],
 ['ඕනෑම පාඩමක් සොයන්න','මෙහි පාඩමේ නමක් හෝ මාතෘකාවක් ලියා Enter ඔබා ඔබේ පෙළපොත් පාඩම් සොයන්න.','🔎','search'],
 ['විෂයක් තෝරන්න','ඔබේ ශ්‍රේණියට සහ මාධ්‍යයට ඇති සියලුම විෂයන් බැලීමට විෂයයන් මත ක්ලික් කරන්න.','📚','subjects'],
 ['පාඩම් දිගටම ඉගෙන ගන්න','සියලු පාඩම් බැලීමට පාඩම් මත ක්ලික් කරන්න. සෑම පාඩමකම කෙටි සටහන්, සම්පූර්ණ පාඩම, ක්‍රියාකාරකම්, ප්‍රශ්නාවලිය සහ ත්‍යාග ඇත.','📖','lessons'],
 ['අලුත් සර් සමඟ කතා කරන්න','ඕනෑම අධ්‍යාපනික ප්‍රශ්නයක් ඇසීමට අලුත් සර් මත ක්ලික් කරන්න. විෂයක් හෝ පාඩමක් තේරීම අනිවාර්ය නොවේ.','🤖','chat'],
 ['ප්‍රශ්නාවලියක් කරන්න','ඔබේ දැනුම පරීක්ෂා කිරීමට ප්‍රශ්නාවලි මත ක්ලික් කරන්න. ඔබට දියුණු වීමට ප්‍රතිඵල සුරැකේ.','📝','quiz'],
 ['ප්‍රමුඛතා පුවරුව බලන්න','ඔබේ ලකුණු, ශ්‍රේණිගත කිරීම සහ ලබාගත් ලාංඡන බැලීමට ප්‍රමුඛතා පුවරුව මත ක්ලික් කරන්න.','🏆','leaderboard'],
 ['ඔබේ ප්‍රගතිය බලන්න','සම්පූර්ණ කළ පාඩම්, ප්‍රශ්නාවලි ලකුණු සහ විෂය අනුව දියුණුව බැලීමට ප්‍රගතිය මත ක්ලික් කරන්න.','📈','progress'],
 ['දෙමාපියෙකු ආරක්ෂිතව සම්බන්ධ කරන්න','ආරක්ෂිත කේතයක් සාදා ගැනීමට දෙමාපිය ප්‍රවේශය මත ක්ලික් කරන්න. එය ඔබේ දෙමාපියාට හෝ භාරකරුට පමණක් ලබා දෙන්න.','👪','parent_access'],
 ['ඔබේ පැතිකඩ කළමනාකරණය කරන්න','ඡායාරූපය හෝ මුරපදය වෙනස් කිරීමට සහ මෙම මඟ පෙන්වීම නැවත බැලීමට පැතිකඩ මත ක්ලික් කරන්න.','👤','profile'],
 ['ඔබ සූදානම්!','ඔබේ පළමු පාඩම ආරම්භ කිරීමට විෂයයන් තෝරන්න. K Education ඔබේ ඉගෙනුම් ගමන පුරා මඟ පෙන්වයි.','🚀','subjects']
]:[
 ['Welcome, '.user()['full_name'].'!','We will point to every important control. Follow the arrow to see what each part does.','👋',''],
 ['Find any lesson','Type a lesson name or topic here and press Enter to search your textbook lessons.','🔎','search'],
 ['Choose a subject','Click Subjects to see every subject available for your grade and learning medium.','📚','subjects'],
 ['Continue your lessons','Click Lessons to find all lessons. Each lesson includes short notes, full content, activities, a quiz, and rewards.','📖','lessons'],
 ['Chat with K Education','Click AI Tutor to ask any educational question. Choosing a subject and lesson is optional.','🤖','chat'],
 ['Try a quiz','Click Quizzes to test your knowledge. Your results are saved so you can improve.','📝','quiz'],
 ['See the leaderboard','Click Leaderboard to view points, ranking, and the emblems you have earned.','🏆','leaderboard'],
 ['Check your progress','Click Progress to see completed lessons, quiz scores, and subject-by-subject growth.','📈','progress'],
 ['Connect a parent safely','Click Parent access to create a secure code. Give it only to your parent or guardian so they can follow your learning.','👪','parent_access'],
 ['Manage your profile','Click Profile to update your photo and password, or replay this welcome guide later.','👤','profile'],
 ['You are ready!','Choose Subjects to begin your first lesson. K Education will guide you as you learn.','🚀','subjects']
];?><div class="tour-overlay" id="studentTour" role="dialog" aria-modal="true" aria-labelledby="tourTitle"><div class="tour-box"><div class="tour-progress" id="tourProgress"></div><div class="tour-top"><span class="tour-emoji" id="tourEmoji">👋</span></div><div class="tour-body"><span class="tour-welcome"><?=e($tourCopy['welcome'])?></span>
<?php foreach($tourSteps as $i=>$step):?><section class="tour-step<?=$i===0?' active':''?>" data-emoji="<?=$step[2]?>" data-target="<?=e($step[3])?>"><h2 id="<?=$i===0?'tourTitle':''?>"><?=e($step[0])?></h2><p><?=e($step[1])?></p></section><?php endforeach;?>
<div class="tour-dots"><?php foreach($tourSteps as $i=>$step):?><i class="tour-dot<?=$i===0?' active':''?>"></i><?php endforeach;?></div><div class="tour-controls"><button class="tour-skip" id="tourSkip" type="button"><?=e($tourCopy['skip'])?></button><button class="tour-skip" id="tourVoice" type="button" aria-pressed="true"><?=e($tourCopy['sound'])?></button><button class="tour-skip" id="tourBack" type="button" hidden><?=e($tourCopy['back'])?></button><button class="tour-next" id="tourNext" type="button"><?=e($tourCopy['next'])?></button></div></div></div></div>
<script>window.kEducationTourCopy=<?=json_encode($tourCopy,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const localizedNext=document.getElementById('tourNext'),localizedSteps=[...document.querySelectorAll('.tour-step')];new MutationObserver(()=>{const copy=window.kEducationTourCopy,wanted=localizedSteps.at(-1).classList.contains('active')?copy.start:copy.next;if(localizedNext.textContent!==wanted)localizedNext.textContent=wanted}).observe(localizedNext,{childList:true,characterData:true,subtree:true});</script>
<script>(()=>{const steps=[...document.querySelectorAll('.tour-step')],voiceButton=document.getElementById('tourVoice'),nextButton=document.getElementById('tourNext'),backButton=document.getElementById('tourBack'),language=<?=json_encode($tourLanguage==='si'?'si-LK':'en-GB')?>;let voiceOn=true,timer=null,run=0;const activeIndex=()=>steps.findIndex(step=>step.classList.contains('active'));const advance=index=>{if(index>=0&&index<steps.length-1&&activeIndex()===index)nextButton.click()};const narrate=()=>{clearTimeout(timer);run++;const token=run,index=activeIndex();if(index<0)return;window.speechSynthesis?.cancel();const text=(steps[index].querySelector('h2')?.textContent||'')+'. '+(steps[index].querySelector('p')?.textContent||'');const fallback=Math.min(18000,Math.max(6500,text.length*65));if(index<steps.length-1)timer=setTimeout(()=>{if(token===run)advance(index)},fallback);if(!voiceOn||!('speechSynthesis'in window))return;const speech=new SpeechSynthesisUtterance(text);speech.lang=language;speech.rate=language==='si-LK'?.86:.92;speech.pitch=1.03;speech.onend=()=>{if(token===run){clearTimeout(timer);setTimeout(()=>advance(index),700)}};speech.onerror=()=>{};speechSynthesis.speak(speech)};let debounce;new MutationObserver(()=>{clearTimeout(debounce);debounce=setTimeout(narrate,450)}).observe(document.getElementById('studentTour'),{attributes:true,subtree:true,attributeFilter:['class']});voiceButton.addEventListener('click',()=>{voiceOn=!voiceOn;voiceButton.setAttribute('aria-pressed',String(voiceOn));voiceButton.textContent=voiceOn?window.kEducationTourCopy.sound:window.kEducationTourCopy.muted;if(voiceOn)narrate();else speechSynthesis?.cancel()});backButton.addEventListener('click',()=>{run++;speechSynthesis?.cancel()});nextButton.addEventListener('click',()=>{run++;speechSynthesis?.cancel()});document.getElementById('tourSkip').addEventListener('click',()=>{run++;clearTimeout(timer);speechSynthesis?.cancel()});setTimeout(narrate,800)})();</script>
<script>document.body.style.overflow='hidden';(()=>{const overlay=document.getElementById('studentTour'),box=overlay.querySelector('.tour-box'),steps=[...overlay.querySelectorAll('.tour-step')],dots=[...overlay.querySelectorAll('.tour-dot')],emoji=document.getElementById('tourEmoji'),progress=document.getElementById('tourProgress'),back=document.getElementById('tourBack'),next=document.getElementById('tourNext'),pointer=document.createElement('span');pointer.className='tour-pointer';pointer.textContent='👇';document.body.appendChild(pointer);let current=0,target=null;const place=()=>{if(!target)return;const r=target.getBoundingClientRect(),gap=14,bw=Math.min(390,innerWidth-24),bh=box.offsetHeight;let left=Math.max(12,Math.min(innerWidth-bw-12,r.left+r.width/2-bw/2)),top=r.bottom+gap;if(top+bh>innerHeight-10)top=Math.max(10,r.top-bh-gap);box.style.left=left+'px';box.style.top=top+'px';pointer.style.left=Math.max(8,Math.min(innerWidth-50,r.left+r.width/2-20))+'px';pointer.style.top=Math.max(5,r.top-49)+'px'};const show=()=>{target?.classList.remove('tour-target');steps.forEach((x,i)=>x.classList.toggle('active',i===current));dots.forEach((x,i)=>x.classList.toggle('active',i===current));emoji.textContent=steps[current].dataset.emoji;progress.style.width=((current+1)/steps.length*100)+'%';back.hidden=current===0;next.textContent=current===steps.length-1?'Explore subjects →':'Next →';const key=steps[current].dataset.target;target=key?document.querySelector('[data-tour="'+key+'"]'):null;overlay.classList.toggle('coach',!!target);pointer.hidden=!target;if(target){document.body.style.overflow='auto';target.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{target.classList.add('tour-target');place()},380)}else{document.body.style.overflow='hidden';box.removeAttribute('style')}};const close=()=>{target?.classList.remove('tour-target');pointer.remove();document.body.style.overflow='';overlay.remove();history.replaceState({},'',location.pathname)};next.onclick=()=>{if(current===steps.length-1){location.href='subjects.php';return}current++;show()};back.onclick=()=>{current--;show()};document.getElementById('tourSkip').onclick=close;addEventListener('resize',place);addEventListener('keydown',e=>{if(e.key==='Escape')close()});show()})();</script><?php endif;?>
<?php include __DIR__.'/../includes/footer.php';?>
