<?php
require_once __DIR__.'/../includes/auth.php';require_login();$qid=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$lesson=filter_input(INPUT_GET,'lesson_id',FILTER_VALIDATE_INT);$grade=(int)user()['grade_id'];$gradeNumber=user_grade_number();$medium=(string)user()['medium'];$questionType=$gradeNumber===8?'challenge':'lesson_quiz';$quizLabel=$gradeNumber===8?'Quick Challenge':'Lesson Quiz';
if(!$qid){
 $sql="SELECT q.*,s.name_en,s.name_si,s.name_ta,l.display_order,(SELECT COUNT(*) FROM quiz_questions qq WHERE qq.quiz_id=q.id AND qq.activity_type='$questionType' AND qq.status='active') question_count FROM quizzes q JOIN subjects s ON s.id=q.subject_id JOIN lessons l ON l.id=q.lesson_id WHERE q.grade_id=? AND q.status='active' AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)";$types='is';$args=[$grade,$medium];
 if($lesson){$sql.=' AND q.lesson_id=?';$types.='i';$args[]=$lesson;}$sql.=' ORDER BY s.name_en,l.display_order';$s=db()->prepare($sql);$s->bind_param($types,...$args);$s->execute();$res=$s->get_result();$pageTitle=tr('quizzes');include __DIR__.'/../includes/header.php';?>
 <section class="card"><span class="badge">Grade <?=$gradeNumber?> · <?=e($medium)?> medium</span><h1>📝 <?=tr('quizzes')?></h1><p class="muted"><?=$gradeNumber===8?'Five-question Quick Challenges for every textbook lesson.':'Textbook revision quizzes and complete imported papers.'?></p><a class="btn alt" href="papers.php">📄 Open Paper Practice</a></section>
 <?php if(!$res->num_rows):?><div class="card muted">No textbook quiz is available for this selection.</div><?php endif;while($q=$res->fetch_assoc()):?><section class="card"><span class="badge"><?=e(locale_value($q,'name'))?> · Lesson <?=intval($q['display_order'])?></span><h2><?=e(locale_value($q,'title'))?></h2><p><?=intval($q['question_count'])?> questions · Pass mark <?=intval($q['pass_mark'])?>%<?php if($q['timer_minutes']):?> · <?=intval($q['timer_minutes'])?> minutes<?php endif;?></p><a class="btn" href="?id=<?=intval($q['id'])?>">Start quiz</a></section><?php endwhile;include __DIR__.'/../includes/footer.php';exit;
}
$q=query_one("SELECT q.* FROM quizzes q JOIN lessons l ON l.id=q.lesson_id WHERE q.id=? AND q.grade_id=? AND q.status='active' AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)",'iis',[$qid,$grade,$medium]);if(!$q){flash('error','No textbook quiz is available for your medium.');redirect('student/quiz.php');}
$s=db()->prepare("SELECT id,question_en,question_si,question_ta,option_a_en,option_a_si,option_a_ta,option_b_en,option_b_si,option_b_ta,option_c_en,option_c_si,option_c_ta,option_d_en,option_d_si,option_d_ta FROM quiz_questions WHERE quiz_id=? AND activity_type=? AND status='active' ORDER BY display_order,id");$s->bind_param('is',$qid,$questionType);$s->execute();$questions=$s->get_result()->fetch_all(MYSQLI_ASSOC);if(!$questions){flash('warning','No '.$quizLabel.' questions are available.');redirect('student/quiz.php');}
$pageTitle=locale_value($q,'title');include __DIR__.'/../includes/header.php';?>
<style>.quiz-shell{max-width:820px;margin:auto}.quiz-head{display:flex;align-items:center;justify-content:space-between;gap:15px}.quiz-head h1{margin-bottom:4px}.quiz-progress{height:9px;background:#e7edf4;border-radius:99px;overflow:hidden;margin:18px 0 12px}.quiz-progress span{display:block;height:100%;width:0;background:linear-gradient(90deg,#0878ce,#00a1a7);transition:width .25s}.quiz-dots{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:24px}.quiz-dot{width:36px;height:36px;min-height:0;padding:0;border-radius:50%;background:#edf3f8;color:#445;box-shadow:none}.quiz-dot.current{outline:3px solid #a9d8f5;background:#0878ce;color:#fff}.quiz-dot.answered{background:#daf5e9;color:#087652}.quiz-dot.current.answered{background:#0878ce;color:#fff}.quiz-question{border:0;margin:0;padding:0}.quiz-question legend{font-size:1.12rem;line-height:1.65;margin-bottom:18px}.quiz-choice{display:flex!important;align-items:center;gap:13px;padding:14px 16px!important;margin:10px 0;cursor:pointer;border:2px solid var(--line);transition:.15s}.quiz-choice:hover{border-color:#75bdeb;transform:translateY(-1px)}.quiz-choice:has(input:checked){border-color:#0878ce;background:#edf7ff;box-shadow:0 0 0 2px #c8e8fb}.quiz-choice input{width:20px!important;height:20px;margin:0!important;flex:0 0 auto}.choice-letter{display:grid;place-items:center;width:31px;height:31px;border-radius:8px;background:#e8eef5;font-weight:800;text-transform:uppercase}.quiz-choice:has(input:checked) .choice-letter{background:#0878ce;color:#fff}.quiz-actions{display:flex;justify-content:space-between;gap:10px;margin-top:24px}.quiz-actions button{min-width:125px}.quiz-message{color:#b42318;font-weight:700;min-height:24px;margin-top:10px}@media(max-width:600px){.quiz-head{align-items:flex-start}.quiz-dot{width:32px;height:32px}.quiz-actions button{min-width:0;flex:1}}</style>
<form method="post" action="quiz_submit.php" class="card quiz-shell" id="quizForm"><?=csrf_field()?><input type="hidden" name="quiz_id" value="<?=$qid?>"><header class="quiz-head"><div><span class="badge"><?=e($quizLabel)?></span><h1><?=e(locale_value($q,'title'))?></h1><small id="quizCounter">Question 1 of <?=count($questions)?></small></div><?php if($q['timer_minutes']):?><div id="timer" data-minutes="<?=intval($q['timer_minutes'])?>"></div><?php endif;?></header><div class="quiz-progress"><span id="quizProgress"></span></div><nav class="quiz-dots" aria-label="Quiz questions"><?php foreach($questions as $i=>$x):?><button type="button" class="quiz-dot<?=$i===0?' current':''?>" data-go="<?=$i?>" aria-label="Question <?=$i+1?>"><?=$i+1?></button><?php endforeach;?></nav><?php foreach($questions as $i=>$x):?><fieldset class="quiz-question" data-question="<?=$i?>"<?=$i?' hidden':''?>><legend><strong><?=($i+1)?>. <?=e(locale_value($x,'question'))?></strong></legend><?php foreach(['a','b','c','d'] as $o):?><label class="card quiz-choice"><input type="radio" name="answers[<?=$x['id']?>]" value="<?=$o?>"><span class="choice-letter"><?=$o?></span><span><?=e(locale_value($x,'option_'.$o))?></span></label><?php endforeach;?></fieldset><?php endforeach;?><p class="quiz-message" id="quizMessage" role="alert"></p><div class="quiz-actions"><button type="button" class="secondary" id="quizPrevious">Previous</button><button type="button" id="quizNext">Next question</button><button type="submit" class="good" id="quizSubmit" hidden><?=tr('submit')?> <?=e(strtolower($quizLabel))?></button></div></form><script src="<?=url('assets/js/quiz.js')?>"></script>
<?php include __DIR__.'/../includes/footer.php';
