<?php
require_once __DIR__.'/../includes/auth.php';require_login();$qid=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$lesson=filter_input(INPUT_GET,'lesson_id',FILTER_VALIDATE_INT);$grade=(int)user()['grade_id'];$gradeNumber=user_grade_number();$medium=(string)user()['medium'];
if(!$qid){
 $sql="SELECT q.*,s.name_en,s.name_si,s.name_ta,l.display_order FROM quizzes q JOIN subjects s ON s.id=q.subject_id JOIN lessons l ON l.id=q.lesson_id WHERE q.grade_id=? AND q.status='active' AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)";$types='is';$args=[$grade,$medium];
 if($lesson){$sql.=' AND q.lesson_id=?';$types.='i';$args[]=$lesson;}$sql.=' ORDER BY s.name_en,l.display_order';$s=db()->prepare($sql);$s->bind_param($types,...$args);$s->execute();$res=$s->get_result();$pageTitle=tr('quizzes');include __DIR__.'/../includes/header.php';?>
 <section class="card"><span class="badge">Grade <?=$gradeNumber?> · <?=e($medium)?> medium</span><h1>📝 <?=tr('quizzes')?></h1><p class="muted">Textbook revision quizzes and complete imported papers.</p><a class="btn alt" href="papers.php">📄 Open Paper Practice</a></section>
 <?php if(!$res->num_rows):?><div class="card muted">No textbook quiz is available for this selection.</div><?php endif;while($q=$res->fetch_assoc()):?><section class="card"><span class="badge"><?=e(locale_value($q,'name'))?> · Lesson <?=intval($q['display_order'])?></span><h2><?=e(locale_value($q,'title'))?></h2><p>5 questions · Pass mark <?=intval($q['pass_mark'])?>%<?php if($q['timer_minutes']):?> · <?=intval($q['timer_minutes'])?> minutes<?php endif;?></p><a class="btn" href="?id=<?=intval($q['id'])?>">Start quiz</a></section><?php endwhile;include __DIR__.'/../includes/footer.php';exit;
}
$q=query_one("SELECT q.* FROM quizzes q JOIN lessons l ON l.id=q.lesson_id WHERE q.id=? AND q.grade_id=? AND q.status='active' AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)",'iis',[$qid,$grade,$medium]);if(!$q){flash('error','No textbook quiz is available for your medium.');redirect('student/quiz.php');}
if(!is_premium()){$used=query_one('SELECT COUNT(*) n FROM quiz_attempts WHERE user_id=?','i',[user()['id']]);if(($used['n']??0)>=1)require_premium();}
$s=db()->prepare("SELECT id,question_en,question_si,question_ta,option_a_en,option_a_si,option_a_ta,option_b_en,option_b_si,option_b_ta,option_c_en,option_c_si,option_c_ta,option_d_en,option_d_si,option_d_ta FROM quiz_questions WHERE quiz_id=? AND activity_type='lesson_quiz' AND status='active' ORDER BY display_order,id");$s->bind_param('i',$qid);$s->execute();$questions=$s->get_result()->fetch_all(MYSQLI_ASSOC);if(!$questions){flash('warning','No Lesson Quiz questions are available.');redirect('student/quiz.php');}
$pageTitle=locale_value($q,'title');include __DIR__.'/../includes/header.php';?>
<form method="post" action="quiz_submit.php" class="card" id="quizForm"><?=csrf_field()?><input type="hidden" name="quiz_id" value="<?=$qid?>"><h1><?=e(locale_value($q,'title'))?></h1><?php if($q['timer_minutes']):?><div id="timer" data-minutes="<?=intval($q['timer_minutes'])?>"></div><?php endif;?><?php foreach($questions as $i=>$x):?><fieldset style="border:0;margin:22px 0;padding:0"><legend><strong><?=($i+1)?>. <?=e(locale_value($x,'question'))?></strong></legend><?php foreach(['a','b','c','d'] as $o):?><label class="card" style="padding:10px"><input style="width:auto;margin:0 8px" type="radio" name="answers[<?=$x['id']?>]" value="<?=$o?>" required><?=e(locale_value($x,'option_'.$o))?></label><?php endforeach;?></fieldset><?php endforeach;?><button><?=tr('submit')?></button></form><script src="<?=url('assets/js/quiz.js')?>"></script>
<?php include __DIR__.'/../includes/footer.php';
