<?php
require_once __DIR__.'/../includes/auth.php';require_login();
$current=user();$uid=(int)$current['id'];$grade=(int)$current['grade_id'];$gradeNumber=user_grade_number();$medium=(string)$current['medium'];$lang=medium_language($medium);
$s=db()->prepare("SELECT s.*,(SELECT COUNT(*) FROM lessons l WHERE l.subject_id=s.id AND l.grade_id=? AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)) lesson_count,(SELECT COUNT(DISTINCT lp.lesson_id) FROM lesson_progress lp JOIN lessons l ON l.id=lp.lesson_id WHERE lp.user_id=? AND lp.completed_at IS NOT NULL AND l.subject_id=s.id AND l.grade_id=? AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?)) completed_count FROM subjects s WHERE s.grade_id=? AND s.status='active' HAVING lesson_count>0 ORDER BY s.name_en");
if(!$s){flash('error','Subjects could not be loaded. Please try again.');redirect('student/dashboard.php');}$s->bind_param('isiisi',$grade,$medium,$uid,$grade,$medium,$grade);$s->execute();$res=$s->get_result();
$copy=[
'en'=>['badge'=>'Official Grade '.$gradeNumber.' textbooks','title'=>'English medium','intro'=>'Choose a subject to access textbook lessons, short notes, AI help and revision quizzes.','lessons'=>'lessons','complete'=>'complete','empty'=>'No textbooks are available for Grade '.$gradeNumber.' in this medium yet.'],
'si'=>['badge'=>$gradeNumber.' ශ්‍රේණිය නිල පෙළපොත්','title'=>'සිංහල මාධ්‍ය','intro'=>'පෙළපොත් පාඩම්, කෙටි සටහන්, AI උපකාර සහ පුනරීක්ෂණ ප්‍රශ්න සඳහා විෂයක් තෝරන්න.','lessons'=>'පාඩම්','complete'=>'සම්පූර්ණයි','empty'=>$gradeNumber.' ශ්‍රේණියේ මෙම මාධ්‍යය සඳහා පෙළපොත් තවම ඇතුළත් කර නැත.'],
'ta'=>['badge'=>'தரம் '.$gradeNumber.' அதிகாரப்பூர்வ பாடநூல்கள்','title'=>'தமிழ் மூலம்','intro'=>'பாடங்கள், சுருக்கக் குறிப்புகள், AI உதவி மற்றும் வினாடி வினாக்களுக்கு ஒரு பாடத்தைத் தேர்ந்தெடுக்கவும்.','lessons'=>'பாடங்கள்','complete'=>'நிறைவு','empty'=>'தரம் '.$gradeNumber.' தமிழ் மொழிமூல பாடநூல்கள் இன்னும் சேர்க்கப்படவில்லை.']][$lang];
$pageTitle=tr('subjects');include __DIR__.'/../includes/header.php';?>
<style>.learn-hero{background:linear-gradient(135deg,#4637b8,#6554e8 50%,#168fc1);color:#fff}.learn-hero .muted{color:rgba(255,255,255,.8)}.subject-card{display:flex;flex-direction:column;text-decoration:none;color:inherit}.subject-icon{display:grid;place-items:center;width:62px;height:62px;border-radius:19px;background:linear-gradient(135deg,#efedff,#e4f7ff);font-size:2rem}.subject-card h2{margin:17px 0 6px}.subject-meta{display:flex;justify-content:space-between;gap:8px;margin-top:auto;padding-top:15px;font-size:.83rem;font-weight:800;color:var(--muted)}</style>
<section class="card learn-hero"><span class="badge"><?=e($copy['badge'])?></span><h1><?=tr('learn')?> · <?=e($copy['title'])?></h1><p class="muted"><?=e($copy['intro'])?></p></section>
<?php if($res->num_rows===0):?><section class="card"><p><?=e($copy['empty'])?></p></section><?php else:?><section class="grid"><?php while($r=$res->fetch_assoc()):$pct=$r['lesson_count']?(int)round(100*$r['completed_count']/$r['lesson_count']):0;?><a class="card subject-card" href="units.php?subject_id=<?=intval($r['id'])?>"><div class="subject-icon"><?=e($r['icon'])?></div><h2><?=e(locale_value($r,'name'))?></h2><p class="muted"><?=e(locale_value($r,'description'))?></p><div class="progress"><span style="width:<?=$pct?>%"></span></div><div class="subject-meta"><span><?=intval($r['lesson_count'])?> <?=e($copy['lessons'])?></span><span><?=$pct?>% <?=e($copy['complete'])?></span></div></a><?php endwhile;?></section><?php endif;?>
<?php include __DIR__.'/../includes/footer.php';
