<?php
require_once __DIR__.'/../includes/auth.php';require_login();$sid=filter_input(INPUT_GET,'subject_id',FILTER_VALIDATE_INT);$grade=(int)user()['grade_id'];$gradeNumber=user_grade_number();$medium=(string)user()['medium'];$uid=(int)user()['id'];
$subject=$sid?query_one("SELECT s.* FROM subjects s WHERE s.id=? AND s.grade_id=? AND s.status='active' AND EXISTS(SELECT 1 FROM lessons l WHERE l.subject_id=s.id AND l.content_source='textbook' AND l.status='active' AND (l.medium='All' OR l.medium=?))",'iis',[$sid,$grade,$medium]):null;if(!$subject){flash('error','No verified textbook lessons are available for this subject and medium.');redirect('student/subjects.php');}
$s=db()->prepare("SELECT l.id,l.display_order,l.title_en,l.title_si,l.title_ta,l.short_description_en,l.short_description_si,l.short_description_ta,u.unit_number,lp.opened_at,COALESCE(lp.completed_at,(SELECT MIN(sp.awarded_at) FROM student_points sp WHERE sp.user_id=? AND sp.lesson_id=l.id AND sp.activity_type='lesson_complete'),(SELECT MIN(se.earned_at) FROM student_emblems se WHERE se.user_id=? AND se.lesson_id=l.id)) completed_at,(SELECT q.id FROM quizzes q WHERE q.lesson_id=l.id AND q.status='active' LIMIT 1) quiz_id FROM lessons l JOIN units u ON u.id=l.unit_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE l.subject_id=? AND l.grade_id=? AND l.content_source='textbook' AND l.status='active' AND (l.medium='All' OR l.medium=?) ORDER BY l.display_order,u.unit_number");$s->bind_param('iiiiis',$uid,$uid,$uid,$sid,$grade,$medium);$s->execute();$res=$s->get_result();$pageTitle=locale_value($subject,'name');include __DIR__.'/../includes/header.php';?>
<style>.lesson-row{display:grid;grid-template-columns:54px 1fr auto;gap:15px;align-items:center;text-decoration:none;color:inherit}.lesson-number{display:grid;place-items:center;width:52px;height:52px;border-radius:17px;background:#efedff;color:var(--violet);font-size:1.2rem;font-weight:900}.lesson-row h2{margin:0 0 5px}.lesson-row p{margin:0}.lesson-state{text-align:right}@media(max-width:600px){.lesson-row{grid-template-columns:48px 1fr}.lesson-state{grid-column:2;text-align:left}}</style>
<p><a href="subjects.php">← <?=tr('subjects')?></a></p><section class="card"><span class="badge"><?=e($subject['icon'])?> Grade <?=$gradeNumber?> textbook</span><h1><?=e(locale_value($subject,'name'))?></h1><p class="muted">Select a lesson for short notes, examples, a summary, AI tutoring and its quiz.</p></section>
<?php while($r=$res->fetch_assoc()):?><a class="card lesson-row" href="lesson.php?id=<?=intval($r['id'])?>"><span class="lesson-number"><?=intval($r['display_order'])?></span><span><h2><?=e(locale_value($r,'title'))?></h2><p class="muted"><?=e(locale_value($r,'short_description'))?></p></span><span class="lesson-state"><?php if($r['completed_at']):?><span class="badge">✓ Completed</span><?php elseif($r['opened_at']):?><span class="badge">Continue</span><?php else:?><span class="badge">Start</span><?php endif;?><small style="display:block;margin-top:7px"><?=$r['quiz_id']?'5-question quiz':'Notes'?></small></span></a><?php endwhile;?>
<style>
.lesson-row{position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.92);background:linear-gradient(135deg,rgba(255,255,255,.97),rgba(246,247,255,.96));transition:transform .22s,box-shadow .22s,border-color .22s}.lesson-row:before{content:"";position:absolute;inset:0 auto 0 0;width:4px;background:linear-gradient(180deg,#6554e8,#21c59b);opacity:.3}.lesson-row:hover{transform:translateY(-5px) scale(1.006);box-shadow:0 22px 48px rgba(55,65,135,.16);border-color:#d9d4ff}.lesson-row.completed{background:linear-gradient(135deg,#f3fffb,#fff 48%,#f1efff);border-color:#bdebdc}.lesson-row.completed:before{opacity:1}.completed .lesson-number{background:linear-gradient(145deg,#21c59b,#087f77);color:#fff;box-shadow:0 10px 23px rgba(15,158,129,.28)}.completion-label{color:#078369!important;background:#ddfaef;border-color:#bcefdc}.lesson-crown{display:block;margin-bottom:4px;color:#d89910;font-size:.72rem;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.units-hero{position:relative;overflow:hidden;background:radial-gradient(circle at 83% 15%,rgba(255,202,84,.3),transparent 18%),linear-gradient(130deg,#28206d,#6352dc 55%,#148cae);color:#fff;box-shadow:0 25px 60px rgba(64,49,165,.2)}.units-hero h1{color:#fff}.units-hero .muted{color:rgba(255,255,255,.82)}.units-hero:after{content:"✦";position:absolute;right:8%;top:19px;color:rgba(255,255,255,.4);font-size:4rem;animation:unitSpark 3s ease-in-out infinite}@keyframes unitSpark{50%{transform:translateY(10px) rotate(15deg);opacity:.6}}@media(max-width:600px){.lesson-row{grid-template-columns:48px 1fr;gap:12px;padding:16px}.lesson-number{width:48px;height:48px;border-radius:16px}.lesson-state{grid-column:2;text-align:left;min-width:0}.lesson-state small{display:inline!important;margin-left:6px!important}.lesson-row h2{font-size:1rem}.lesson-row p{font-size:.82rem}}
</style>
<script>(()=>{document.querySelector('.lesson-row')?.parentElement?.previousElementSibling?.classList.add('units-hero');document.querySelectorAll('.lesson-row').forEach(row=>{if(/completed/i.test(row.textContent)){row.classList.add('completed');const badge=row.querySelector('.lesson-state .badge');if(badge){badge.classList.add('completion-label');const crown=document.createElement('span');crown.className='lesson-crown';crown.textContent='✦ Mastered';badge.before(crown)}}})})();</script>
<?php include __DIR__.'/../includes/footer.php';
