<?php
$pageTitle='Admin dashboard';include __DIR__.'/_top.php';$db=db();
$db->query("CREATE TABLE IF NOT EXISTS app_downloads(id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,ip_address VARCHAR(45),user_agent VARCHAR(500),downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(downloaded_at),INDEX(user_id))");
$overview=query_one("SELECT (SELECT COUNT(*) FROM users) students,(SELECT COUNT(DISTINCT NULLIF(school_name,'')) FROM users) schools,(SELECT COUNT(*) FROM users WHERE created_at>=CURDATE()) joined_today,(SELECT COUNT(*) FROM users WHERE subscription_expires_at>NOW()) premium,(SELECT COUNT(*) FROM subscriptions WHERE status='pending') pending,(SELECT COUNT(*) FROM lessons WHERE status='active' AND content_source='textbook') lessons,(SELECT COUNT(*) FROM quiz_attempts) attempts,(SELECT COALESCE(ROUND(AVG(percentage)),0) FROM quiz_attempts) average_score,(SELECT COUNT(*) FROM app_downloads) downloads,(SELECT COUNT(*) FROM student_activity_events WHERE event_time>=NOW()-INTERVAL 24 HOUR) activity_today")??[];
$mediums=$db->query("SELECT medium,COUNT(*) total FROM users GROUP BY medium ORDER BY total DESC")->fetch_all(MYSQLI_ASSOC);
$grades=$db->query("SELECT g.grade_number,COUNT(u.id) total FROM grades g LEFT JOIN users u ON u.grade_id=g.id GROUP BY g.id ORDER BY g.grade_number")->fetch_all(MYSQLI_ASSOC);
$recent=$db->query("SELECT u.id,u.full_name,u.username,u.email,u.school_name,u.medium,u.created_at,g.grade_number,(SELECT COALESCE(SUM(points),0) FROM student_points WHERE user_id=u.id) points,(SELECT COUNT(*) FROM lesson_progress WHERE user_id=u.id AND completed_at IS NOT NULL) completed FROM users u JOIN grades g ON g.id=u.grade_id ORDER BY u.id DESC LIMIT 8")->fetch_all(MYSQLI_ASSOC);
$schools=$db->query("SELECT COALESCE(NULLIF(school_name,''),'Not provided') school,COUNT(*) students,SUM(subscription_expires_at>NOW()) premium FROM users GROUP BY school_name ORDER BY students DESC,school LIMIT 8")->fetch_all(MYSQLI_ASSOC);
$events=$db->query("SELECT e.event_type,e.detail,e.event_time,u.full_name FROM student_activity_events e JOIN users u ON u.id=e.user_id ORDER BY e.id DESC LIMIT 7")->fetch_all(MYSQLI_ASSOC);
$maxMedium=max(1,...array_map(fn($x)=>(int)$x['total'],$mediums));$maxGrade=max(1,...array_map(fn($x)=>(int)$x['total'],$grades));
?>
<style>
.admin-hero{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:29px;background:radial-gradient(circle at 88% 14%,rgba(255,183,57,.38),transparent 27%),linear-gradient(135deg,#1b2550,#394fa0 57%,#087a9f);color:#fff}.admin-hero h1{margin:8px 0 5px}.admin-hero p{margin:0;color:rgba(255,255,255,.72)}.admin-date{padding:10px 13px;border-radius:14px;background:rgba(255,255,255,.12);font-weight:800;white-space:nowrap}.metric-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:18px}.metric-card{margin:0;padding:17px;border-left:4px solid var(--metric,#6554e8)}.metric-icon{font-size:1.45rem}.metric-card b{display:block;margin-top:7px;font-size:1.65rem}.metric-card small{color:var(--muted);font-weight:750}.admin-layout{display:grid;grid-template-columns:1.25fr .75fr;gap:17px;margin-bottom:17px}.admin-layout>.card{margin:0}.dashboard-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:14px}.dashboard-title h2{margin:0}.chart-row{display:grid;grid-template-columns:100px 1fr 34px;gap:9px;align-items:center;margin:12px 0;font-size:.82rem;font-weight:750}.chart-track{height:10px;border-radius:99px;background:#edf0f6;overflow:hidden}.chart-track i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,var(--violet),var(--blue))}.activity-item{display:flex;gap:11px;padding:11px 0;border-bottom:1px solid var(--line)}.activity-item:last-child{border:0}.activity-dot{flex:0 0 10px;width:10px;height:10px;margin-top:7px;border-radius:50%;background:var(--mint)}.activity-item b{display:block}.activity-item small{color:var(--muted)}.admin-table td{vertical-align:middle}.student-cell{display:flex;gap:9px;align-items:center}.mini-avatar{display:grid;place-items:center;flex:0 0 37px;height:37px;border-radius:12px;background:#efedff;color:var(--violet);font-weight:900}.school-list{display:grid;gap:9px}.school-row{display:flex;justify-content:space-between;gap:14px;padding:11px 13px;border-radius:14px;background:#f7f8fc}.download-card{background:linear-gradient(135deg,#fff8e9,#fff);border:1px solid #ffe0a2}.download-count{font-size:2rem;font-weight:950;color:#c96a00}@media(max-width:950px){.metric-grid{grid-template-columns:repeat(3,1fr)}.admin-layout{grid-template-columns:1fr}}@media(max-width:600px){.metric-grid{grid-template-columns:repeat(2,1fr)}.admin-hero{display:block}.admin-date{display:inline-block;margin-top:14px}.admin-table th:nth-child(3),.admin-table td:nth-child(3){display:none}}
</style>
<section class="card admin-hero"><div><span class="badge">Administration overview</span><h1>Welcome back, <?=e($_SESSION['admin']['full_name']??'Administrator')?> 👋</h1><p>Monitor K Education students, schools, learning, payments, and application reach.</p></div><span class="admin-date">📅 <?=e(date('D, d M Y'))?></span></section>
<section class="metric-grid"><?php foreach([
 ['🎓',$overview['students']??0,'Students','#6554e8'],['🏫',$overview['schools']??0,'Schools','#2588f6'],['✨',$overview['joined_today']??0,'Joined today','#21c59b'],['⭐',$overview['premium']??0,'Premium','#ff9d2e'],['💳',$overview['pending']??0,'Payments pending','#ff6584'],['📖',$overview['lessons']??0,'Active lessons','#6554e8'],['📝',$overview['attempts']??0,'Quiz attempts','#2588f6'],['🎯',($overview['average_score']??0).'%','Average score','#21c59b'],['⬇️',$overview['downloads']??0,'App downloads','#ff9d2e'],['⚡',$overview['activity_today']??0,'Activities today','#ff6584']
] as $m):?><article class="card metric-card" style="--metric:<?=$m[3]?>"><span class="metric-icon"><?=$m[0]?></span><b><?=e($m[1])?></b><small><?=e($m[2])?></small></article><?php endforeach;?></section>
<section class="admin-layout"><article class="card"><div class="dashboard-title"><h2>📊 Students by medium</h2><a href="students.php">All students →</a></div><?php foreach($mediums as $row):?><div class="chart-row"><span><?=e($row['medium'])?></span><span class="chart-track"><i style="width:<?=round(100*$row['total']/$maxMedium)?>%"></i></span><b><?=intval($row['total'])?></b></div><?php endforeach;?><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><h2>Students by grade</h2><?php foreach($grades as $row):?><div class="chart-row"><span>Grade <?=intval($row['grade_number'])?></span><span class="chart-track"><i style="width:<?=round(100*$row['total']/$maxGrade)?>%"></i></span><b><?=intval($row['total'])?></b></div><?php endforeach;?></article><article class="card"><div class="dashboard-title"><h2>⚡ Latest activity</h2><a href="chatbot_logs.php">Logs →</a></div><?php if(!$events):?><p class="muted">No student activity yet.</p><?php endif;foreach($events as $event):?><div class="activity-item"><i class="activity-dot"></i><span><b><?=e($event['full_name'])?></b><span><?=e(ucwords(str_replace('_',' ',$event['event_type'])))?> · <?=e(mb_strimwidth((string)$event['detail'],0,65,'…'))?></span><small><?=e(date('d M, g:i A',strtotime($event['event_time'])))?></small></span></div><?php endforeach;?></article></section>
<section class="card"><div class="dashboard-title"><h2>🎓 Recently registered students</h2><a class="btn alt" href="students.php">Manage all students</a></div><div class="scroll"><table class="admin-table"><tr><th>Student</th><th>School</th><th>Grade / Medium</th><th>Learning</th><th>Joined</th><th></th></tr><?php foreach($recent as $student):?><tr><td><span class="student-cell"><i class="mini-avatar"><?=e(mb_strtoupper(mb_substr($student['full_name'],0,1)))?></i><span><strong><?=e($student['full_name'])?></strong><small style="display:block;color:var(--muted)">@<?=e($student['username'])?></small></span></span></td><td><?=e($student['school_name']?:'Not provided')?></td><td>Grade <?=intval($student['grade_number'])?><br><small><?=e($student['medium'])?></small></td><td><?=intval($student['points'])?> pts · <?=intval($student['completed'])?> lessons</td><td><?=e(date('d M Y',strtotime($student['created_at'])))?></td><td><a href="student.php?id=<?=intval($student['id'])?>">View →</a></td></tr><?php endforeach;?></table></div></section>
<section class="admin-layout"><article class="card"><div class="dashboard-title"><h2>🏫 Schools</h2><span class="badge"><?=intval($overview['schools']??0)?> total</span></div><div class="school-list"><?php foreach($schools as $school):?><div class="school-row"><span><strong><?=e($school['school'])?></strong><small style="display:block;color:var(--muted)"><?=intval($school['premium'])?> premium</small></span><b><?=intval($school['students'])?> students</b></div><?php endforeach;?></div></article><article class="card download-card"><span class="badge">Application distribution</span><h2>⬇️ K Education download</h2><div class="download-count"><?=intval($overview['downloads']??0)?> downloads</div><p class="muted">Share the tracked download link or download the current application package.</p><div class="row"><a class="btn warn" href="<?=url('download.php')?>">Download package</a><button class="btn alt" type="button" id="copyDownload">Copy link</button></div></article></section>
<script>document.getElementById('copyDownload').onclick=async()=>{const link=<?=json_encode((isset($_SERVER['HTTPS'])?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').url('download.php'))?>;await navigator.clipboard.writeText(link);document.getElementById('copyDownload').textContent='✓ Link copied'}</script>
<?php include __DIR__.'/../includes/footer.php';
