<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_admin();$db=db();
$mediums=['English'=>'en','Sinhala'=>'si','Tamil'=>'ta'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$lessonId=filter_input(INPUT_POST,'lesson_id',FILTER_VALIDATE_INT);$medium=(string)($_POST['medium']??'');$field=$mediums[$medium]??null;$lesson=$lessonId?query_one('SELECT id,medium FROM lessons WHERE id=?','i',[$lessonId]):null;
 if(!$lesson||!$field||!in_array($lesson['medium'],[$medium,'All'],true)){flash('error','Choose a valid lesson and medium.');redirect('admin/lesson_editor.php');}
 $title=trim((string)($_POST['title']??''));$description=trim((string)($_POST['description']??''));$content=trim((string)($_POST['content']??''));$shortNotes=trim((string)($_POST['short_notes']??''));$summary=trim((string)($_POST['summary']??''));$status=in_array($_POST['status']??'active',['active','inactive'],true)?$_POST['status']:'active';
 if($title===''){flash('error','The lesson title is required.');redirect('admin/lesson_editor.php?lesson_id='.$lessonId.'&medium='.urlencode($medium));}
 $q=$db->prepare("UPDATE lessons SET title_$field=?,short_description_$field=?,content_$field=?,short_notes_$field=?,summary_$field=?,status=? WHERE id=?");if(!$q)throw new RuntimeException($db->error);$q->bind_param('ssssssi',$title,$description,$content,$shortNotes,$summary,$status,$lessonId);$q->execute();
 flash('success','Lesson content saved successfully.');redirect('admin/lesson_editor.php?lesson_id='.$lessonId.'&medium='.urlencode($medium));
}
$grades=$db->query("SELECT id,grade_number FROM grades WHERE status='active' ORDER BY grade_number")->fetch_all(MYSQLI_ASSOC);
$subjects=$db->query("SELECT id,grade_id,name_en,name_si,name_ta FROM subjects WHERE status='active' ORDER BY grade_id,name_en")->fetch_all(MYSQLI_ASSOC);
$lessons=$db->query("SELECT id,grade_id,subject_id,medium,display_order,status,title_en,title_si,title_ta FROM lessons WHERE content_source='textbook' ORDER BY grade_id,medium,subject_id,display_order,id")->fetch_all(MYSQLI_ASSOC);
$selectedId=filter_input(INPUT_GET,'lesson_id',FILTER_VALIDATE_INT)?:0;$selectedMedium=(string)($_GET['medium']??'');$selected=$selectedId?query_one('SELECT * FROM lessons WHERE id=? AND content_source=\'textbook\'','i',[$selectedId]):null;$source=$selectedId?query_one('SELECT start_page FROM lesson_source_pdfs WHERE lesson_id=?','i',[$selectedId]):null;if($selected&&!isset($mediums[$selectedMedium]))$selectedMedium=$selected['medium']==='All'?'English':$selected['medium'];
$pageTitle='Lesson Content';include __DIR__.'/_top.php';
?>
<style>.le-filters{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.le-editor{display:grid;grid-template-columns:1fr 1fr;gap:14px}.le-editor .wide{grid-column:1/-1}.le-editor textarea{min-height:130px;resize:vertical}.le-editor textarea.large{min-height:360px}.le-empty{text-align:center;padding:34px}.le-meta{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:14px}.le-meta span{padding:6px 10px;border-radius:999px;background:#eef3ff;font-size:.78rem;font-weight:800}.le-preview{display:none;margin:10px 0 18px}.le-preview.show{display:block}.le-preview iframe{width:100%;height:75vh;min-height:600px;border:1px solid #ccd5eb;border-radius:16px;background:#eef2f8}@media(max-width:800px){.le-filters,.le-editor{grid-template-columns:1fr}.le-editor .wide{grid-column:auto}.le-preview iframe{height:68vh;min-height:480px}}</style>
<h1>Lesson Content Editor</h1><p class="muted">Choose a grade, medium, subject and lesson. Add or change lesson text and short notes without uploading a PDF.</p>
<section class="card"><div class="le-filters"><label>Grade<select id="leGrade"><option value="">Choose grade</option><?php foreach($grades as $g):?><option value="<?=$g['id']?>">Grade <?=$g['grade_number']?></option><?php endforeach;?></select></label><label>Medium<select id="leMedium"><option value="">Choose medium</option><?php foreach($mediums as $name=>$code):?><option value="<?=e($name)?>"><?=e($name)?></option><?php endforeach;?></select></label><label>Subject<select id="leSubject"><option value="">Choose subject</option><?php foreach($subjects as $s):?><option value="<?=$s['id']?>" data-grade="<?=$s['grade_id']?>"><?=e($s['name_en'])?></option><?php endforeach;?></select></label><label>Lesson<select id="leLesson"><option value="">Choose lesson</option><?php foreach($lessons as $l):?><option value="<?=$l['id']?>" data-grade="<?=$l['grade_id']?>" data-medium="<?=e($l['medium'])?>" data-subject="<?=$l['subject_id']?>">Lesson <?=$l['display_order']?> · <?=e($l['title_en']?:$l['title_si']?:$l['title_ta']?:'Untitled')?></option><?php endforeach;?></select></label></div></section>
<?php if($selected):$field=$mediums[$selectedMedium]??'en';?>
<section class="card"><div class="le-meta"><span>Lesson <?=$selected['display_order']?></span><span><?=e($selectedMedium)?></span><span><?=e(ucfirst($selected['status']))?></span><?php if($source):?><button type="button" id="lePreviewButton">Preview syllabus book here · page <?=(int)$source['start_page']?></button><a class="btn alt" target="_blank" rel="noopener" href="lesson_pdf.php?id=<?=$selected['id']?>#page=<?=(int)$source['start_page']?>">Open in new tab</a><?php else:?><span>No matching PDF found in the syllabus folder</span><?php endif;?></div><?php if($source):?><div class="le-preview" id="lePreview"><iframe title="Syllabus book preview" loading="lazy" data-src="lesson_pdf.php?id=<?=$selected['id']?>#page=<?=(int)$source['start_page']?>"></iframe></div><?php endif;?><form method="post" class="le-editor"><?=csrf_field()?><input type="hidden" name="lesson_id" value="<?=$selected['id']?>"><input type="hidden" name="medium" value="<?=e($selectedMedium)?>"><label class="wide">Lesson title<input name="title" value="<?=e($selected['title_'.$field]??'')?>" required></label><label class="wide">Short description<textarea name="description"><?=e($selected['short_description_'.$field]??'')?></textarea></label><label class="wide">Full lesson content<textarea class="large" name="content"><?=e($selected['content_'.$field]??'')?></textarea></label><label>Short notes<textarea class="large" name="short_notes"><?=e($selected['short_notes_'.$field]??'')?></textarea></label><label>Lesson summary<textarea class="large" name="summary"><?=e($selected['summary_'.$field]??'')?></textarea></label><label>Status<select name="status"><option value="active"<?=selected($selected['status'],'active')?>>Active</option><option value="inactive"<?=selected($selected['status'],'inactive')?>>Inactive</option></select></label><div style="align-self:end"><button type="submit">Save lesson content</button></div></form></section>
<?php else:?><section class="card le-empty"><h2>Select a lesson to start editing</h2><p class="muted">Choose all four filters above. After selecting the lesson, the orange “Preview syllabus book” button appears above the Full lesson content field.</p></section><?php endif;?>
<script>(()=>{const grade=document.querySelector('#leGrade'),medium=document.querySelector('#leMedium'),subject=document.querySelector('#leSubject'),lesson=document.querySelector('#leLesson'),selected={grade:'<?=e((string)($selected['grade_id']??''))?>',medium:'<?=e($selectedMedium)?>',subject:'<?=e((string)($selected['subject_id']??''))?>',lesson:'<?=e((string)$selectedId)?>'};function show(o,v){o.hidden=!v;o.disabled=!v}function filterSubjects(){[...subject.options].slice(1).forEach(o=>show(o,!grade.value||o.dataset.grade===grade.value));if(subject.selectedOptions[0]?.disabled)subject.value='';filterLessons()}function filterLessons(){[...lesson.options].slice(1).forEach(o=>show(o,(!grade.value||o.dataset.grade===grade.value)&&(!medium.value||o.dataset.medium===medium.value||o.dataset.medium==='All')&&(!subject.value||o.dataset.subject===subject.value)));if(lesson.selectedOptions[0]?.disabled)lesson.value=''}grade.addEventListener('change',filterSubjects);medium.addEventListener('change',filterLessons);subject.addEventListener('change',filterLessons);lesson.addEventListener('change',()=>{if(lesson.value)location.href='lesson_editor.php?lesson_id='+encodeURIComponent(lesson.value)+'&medium='+encodeURIComponent(medium.value||lesson.selectedOptions[0].dataset.medium)});grade.value=selected.grade;medium.value=selected.medium;filterSubjects();subject.value=selected.subject;filterLessons();lesson.value=selected.lesson;const previewButton=document.querySelector('#lePreviewButton'),preview=document.querySelector('#lePreview');previewButton?.addEventListener('click',()=>{const frame=preview.querySelector('iframe');if(!frame.src)frame.src=frame.dataset.src;preview.classList.toggle('show');previewButton.textContent=preview.classList.contains('show')?'Hide syllabus book preview':'Preview syllabus book here'})})();</script>
<?php include __DIR__.'/../includes/footer.php';
