<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_admin();$db=db();

function parse_mcqs(string $text):array{
 $text=trim(str_replace(["\r\n","\r"],"\n",$text));$json=json_decode($text,true);
 if(is_array($json)){
  if(isset($json['questions']))$json=$json['questions'];if(!array_is_list($json))$json=[$json];$out=[];
  foreach($json as $x){if(!is_array($x))continue;$opts=$x['options']??[];$answer=strtolower((string)($x['correct_option']??$x['correct']??$x['answer']??''));preg_match('/[a-d1-4]/i',$answer,$m);$answer=strtolower($m[0]??'');if(ctype_digit($answer))$answer=chr(96+(int)$answer);$out[]=['question'=>trim((string)($x['question']??'')),'a'=>trim((string)($x['option_a']??$x['a']??$opts['a']??$opts[0]??'')),'b'=>trim((string)($x['option_b']??$x['b']??$opts['b']??$opts[1]??'')),'c'=>trim((string)($x['option_c']??$x['c']??$opts['c']??$opts[2]??'')),'d'=>trim((string)($x['option_d']??$x['d']??$opts['d']??$opts[3]??'')),'correct'=>$answer,'explanation'=>trim((string)($x['explanation']??''))];}return $out;
 }
 $items=[];$cur=null;$field='question';$push=function()use(&$cur,&$items){if($cur!==null){foreach($cur as &$v)$v=trim($v);unset($v);$items[]=$cur;}$cur=null;};
 foreach(explode("\n",$text) as $raw){$line=trim($raw);if($line==='')continue;
  if(preg_match('/^(?:(?:q(?:uestion)?)[ .#-]*)?(\d+)[.)：:]\s*(.+)$/iu',$line,$m)||preg_match('/^(?:question|q)\s*[:：-]\s*(.+)$/iu',$line,$m)&&($m[2]=$m[1])){$push();$cur=['question'=>$m[2],'a'=>'','b'=>'','c'=>'','d'=>'','correct'=>'','explanation'=>''];$field='question';continue;}
  if($cur===null)$cur=['question'=>'','a'=>'','b'=>'','c'=>'','d'=>'','correct'=>'','explanation'=>''];
  if(preg_match('/^(?:option\s*)?([a-d])[.)：:]\s*(.+)$/iu',$line,$m)){$field=strtolower($m[1]);$cur[$field]=$m[2];continue;}
  if(preg_match('/^(?:correct\s*)?(?:answer|ans|පිළිතුර|விடை)\s*[:：-]\s*(?:option\s*)?([a-d1-4])/iu',$line,$m)){$v=strtolower($m[1]);$cur['correct']=ctype_digit($v)?chr(96+(int)$v):$v;$field='correct';continue;}
  if(preg_match('/^(?:explanation|reason)\s*[:：-]\s*(.*)$/iu',$line,$m)){$cur['explanation']=$m[1];$field='explanation';continue;}
  if($field!=='correct')$cur[$field].=($cur[$field]?' ':'').$line;
 }$push();return $items;
}

$old='';if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$old=(string)($_POST['questions']??'');try{
 $grade=filter_input(INPUT_POST,'grade_id',FILTER_VALIDATE_INT);$subject=filter_input(INPUT_POST,'subject_id',FILTER_VALIDATE_INT);$lessonId=filter_input(INPUT_POST,'lesson_id',FILTER_VALIDATE_INT);$medium=(string)($_POST['medium']??'');$lang=['English'=>'en','Sinhala'=>'si','Tamil'=>'ta'][$medium]??null;
 $lesson=($grade&&$subject&&$lessonId&&$lang)?query_one("SELECT * FROM lessons WHERE id=? AND grade_id=? AND subject_id=? AND status='active' AND content_source='textbook' AND (medium=? OR medium='All')",'iiis',[$lessonId,$grade,$subject,$medium]):null;if(!$lesson)throw new RuntimeException('Choose a valid grade, medium, subject and lesson.');
 $items=parse_mcqs($old);if(!$items)throw new RuntimeException('No questions were recognized. Use the paste format shown below.');if(count($items)>30)throw new RuntimeException('Maximum 30 MCQs per lesson. Your paste contains '.count($items).'.');
 foreach($items as $i=>$x){$missing=[];foreach(['question','a','b','c','d','correct'] as $k)if(empty($x[$k]))$missing[]=$k;if(!in_array($x['correct'],['a','b','c','d'],true))$missing[]='answer A-D';if($missing)throw new RuntimeException('Question '.($i+1).' is incomplete: '.implode(', ',array_unique($missing)).'. Nothing was imported.');}
 $db->begin_transaction();$quiz=query_one('SELECT id FROM quizzes WHERE lesson_id=? ORDER BY id LIMIT 1','i',[$lessonId]);if($quiz)$quizId=(int)$quiz['id'];else{$s=$db->prepare('INSERT INTO quizzes(grade_id,subject_id,unit_id,lesson_id,title_en,title_si,title_ta,timer_minutes,pass_mark,status) VALUES(?,?,?,?,?,?,?,15,50,"active")');$s->bind_param('iiiisss',$grade,$subject,$lesson['unit_id'],$lessonId,$lesson['title_en'],$lesson['title_si'],$lesson['title_ta']);$s->execute();$quizId=(int)$db->insert_id;}
 if(!empty($_POST['replace_existing'])){$s=$db->prepare("DELETE qa FROM quiz_answers qa JOIN quiz_questions qq ON qq.id=qa.question_id WHERE qq.quiz_id=? AND qq.activity_type='lesson_quiz'");$s->bind_param('i',$quizId);$s->execute();$s=$db->prepare("DELETE FROM quiz_questions WHERE quiz_id=? AND activity_type='lesson_quiz'");$s->bind_param('i',$quizId);$s->execute();$start=0;}else{$r=query_one("SELECT COUNT(*) total,COALESCE(MAX(display_order),0) last_order FROM quiz_questions WHERE quiz_id=? AND activity_type='lesson_quiz'",'i',[$quizId]);if((int)$r['total']+count($items)>30)throw new RuntimeException('This lesson already has '.$r['total'].' MCQs. Use Replace existing MCQs to keep the 30-question limit.');$start=(int)$r['last_order'];}
 $s=$db->prepare("INSERT INTO quiz_questions(quiz_id,activity_type,question_$lang,option_a_$lang,option_b_$lang,option_c_$lang,option_d_$lang,correct_option,explanation_$lang,display_order,status) VALUES(?,'lesson_quiz',?,?,?,?,?,?,?,?,?,'active')");foreach($items as $i=>$x){$order=$start+$i+1;$s->bind_param('isssssssi',$quizId,$x['question'],$x['a'],$x['b'],$x['c'],$x['d'],$x['correct'],$x['explanation'],$order);$s->execute();}$db->commit();flash('success',count($items).' MCQs added to the selected lesson.');redirect('admin/mcq.php?lesson_id='.$lessonId.'&medium='.urlencode($medium));
 }catch(Throwable $e){@$db->rollback();flash('error',$e->getMessage());}}
$grades=$db->query("SELECT id,grade_number FROM grades WHERE status='active' ORDER BY grade_number")->fetch_all(MYSQLI_ASSOC);$subjects=$db->query("SELECT id,grade_id,name_en FROM subjects WHERE status='active' ORDER BY grade_id,name_en")->fetch_all(MYSQLI_ASSOC);$lessons=$db->query("SELECT l.id,l.grade_id,l.subject_id,l.medium,l.display_order,l.title_en,l.title_si,l.title_ta,(SELECT COUNT(*) FROM quiz_questions x JOIN quizzes q ON q.id=x.quiz_id WHERE q.lesson_id=l.id AND x.activity_type='lesson_quiz' AND x.status='active') mcqs FROM lessons l WHERE l.status='active' AND l.content_source='textbook' ORDER BY l.grade_id,l.medium,l.subject_id,l.display_order")->fetch_all(MYSQLI_ASSOC);$selectedId=filter_input(INPUT_GET,'lesson_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'lesson_id',FILTER_VALIDATE_INT)?:0;$selectedMedium=(string)($_GET['medium']??$_POST['medium']??'');$pageTitle='MCQ Bulk Import';include __DIR__.'/_top.php';
?>
<style>.mcq-hero{background:linear-gradient(135deg,#172554,#4338ca 58%,#0891b2);color:#fff}.mcq-hero p{color:#dbeafe}.mcq-filters{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:12px}.mcq-form textarea{min-height:430px;line-height:1.55;resize:vertical}.mcq-actions{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.mcq-actions label{display:flex;flex-direction:row;align-items:center;gap:8px}.mcq-actions input{width:auto;min-height:auto}.format-example{white-space:pre-wrap;background:#f4f7fc;border:1px solid var(--line);padding:15px;border-radius:14px}@media(max-width:760px){.mcq-filters{grid-template-columns:1fr}}</style>
<section class="card mcq-hero"><span class="badge">Admin MCQ workspace</span><h1>Paste MCQs into the correct lesson</h1><p>Select the grade, medium, subject and lesson, then paste up to 30 questions with their answers.</p></section>
<section class="card"><div class="mcq-filters"><label>Grade<select id="mcqGrade" name="grade_id" form="mcqForm" required><option value="">Choose grade</option><?php foreach($grades as $g):?><option value="<?=$g['id']?>">Grade <?=$g['grade_number']?></option><?php endforeach;?></select></label><label>Medium<select id="mcqMedium" name="medium" form="mcqForm" required><option value="">Choose medium</option><option>English</option><option>Sinhala</option><option>Tamil</option></select></label><label>Subject<select id="mcqSubject" name="subject_id" form="mcqForm" required><option value="">Choose subject</option><?php foreach($subjects as $s):?><option value="<?=$s['id']?>" data-grade="<?=$s['grade_id']?>"><?=e($s['name_en'])?></option><?php endforeach;?></select></label><label>Lesson<select id="mcqLesson" name="lesson_id" form="mcqForm" required><option value="">Choose lesson</option><?php foreach($lessons as $l):?><option value="<?=$l['id']?>" data-grade="<?=$l['grade_id']?>" data-medium="<?=e($l['medium'])?>" data-subject="<?=$l['subject_id']?>">Lesson <?=$l['display_order']?> · <?=e($l['title_en']?:$l['title_si']?:$l['title_ta']?:'Untitled')?> (<?=$l['mcqs']?>/30)</option><?php endforeach;?></select></label></div></section>
<section class="card"><form method="post" id="mcqForm" class="mcq-form"><?=csrf_field()?><label>Paste all questions, options and answers<textarea name="questions" required placeholder="Paste your 30 MCQs here..."><?=e($old)?></textarea></label><div class="mcq-actions"><label><input type="checkbox" name="replace_existing" value="1" checked> Replace existing MCQs in this lesson</label><button>Parse and add MCQs</button></div></form></section>
<details class="card"><summary><strong>Accepted paste format</strong></summary><div class="format-example">1. What is the capital of Sri Lanka?
A. Colombo
B. Kandy
C. Sri Jayawardenepura Kotte
D. Galle
Answer: C
Explanation: Sri Jayawardenepura Kotte is the administrative capital.

2. Your next question...
A. First option
B. Second option
C. Third option
D. Fourth option
Answer: A</div><p class="muted">Number every question and use A, B, C, D and “Answer: A”. A JSON array is also accepted.</p></details>
<script>(()=>{const g=document.querySelector('#mcqGrade'),m=document.querySelector('#mcqMedium'),s=document.querySelector('#mcqSubject'),l=document.querySelector('#mcqLesson');const show=(o,v)=>{o.hidden=!v;o.disabled=!v};function subjects(){[...s.options].slice(1).forEach(o=>show(o,!g.value||o.dataset.grade===g.value));if(s.selectedOptions[0]?.disabled)s.value='';lessons()}function lessons(){[...l.options].slice(1).forEach(o=>show(o,(!g.value||o.dataset.grade===g.value)&&(!s.value||o.dataset.subject===s.value)&&(!m.value||o.dataset.medium===m.value||o.dataset.medium==='All')));if(l.selectedOptions[0]?.disabled)l.value=''}g.onchange=subjects;m.onchange=s.onchange=lessons;subjects();const selected=<?=json_encode(['id'=>(string)$selectedId,'medium'=>$selectedMedium])?>,o=[...l.options].find(x=>x.value===selected.id);if(o){g.value=o.dataset.grade;m.value=selected.medium;subjects();s.value=o.dataset.subject;lessons();l.value=selected.id}})();</script>
<?php include __DIR__.'/../includes/footer.php';
