<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_admin();$errors=[];$generated=(array)($_SESSION['new_referral_credentials']??[]);unset($_SESSION['new_referral_credentials']);$generatedPassword=(string)($generated['password']??'');$generatedCode=(string)($generated['code']??'');
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'');
 if($action==='create'){
  $name=trim((string)($_POST['full_name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$phone=trim((string)($_POST['phone']??''));$code=normalize_referral_code((string)($_POST['referral_code']??''));$password=(string)($_POST['password']??'');$limit=filter_var($_POST['registration_limit']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>100000]]);
  if(mb_strlen($name)<2)$errors[]='Enter the promoter name.';if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Enter a valid email address or leave it empty.';if($phone!==''&&!preg_match('/^[0-9+]{9,15}$/',$phone))$errors[]='Enter a valid phone number or leave it empty.';if(!referral_code_is_valid_format($code))$errors[]='The code must be 4–24 letters, numbers or hyphens.';if(strlen($password)<8)$errors[]='The portal password must contain at least 8 characters.';
  if($limit===false)$errors[]='Enter a registration limit between 1 and 100,000.';
  if(!$errors){$hash=password_hash($password,PASSWORD_DEFAULT);$s=db()->prepare("INSERT INTO referral_promoters(full_name,email,phone,referral_code,password_hash,registration_limit,status) VALUES(?,?,?,?,?,?,'active')");$emailValue=$email?:null;$phoneValue=$phone?:null;$s->bind_param('sssssi',$name,$emailValue,$phoneValue,$code,$hash,$limit);if($s->execute()){$_SESSION['new_referral_credentials']=['code'=>$code,'password'=>$password];flash('success','Referral promoter created. Share the QR code and portal login details securely.');redirect('admin/referral_promoters.php');}else$errors[]=$s->errno===1062?'That email, phone number or referral code is already in use.':'The promoter account could not be created.';}
 }elseif($action==='limit'){$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);$limit=filter_var($_POST['registration_limit']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>100000]]);if(!$id||$limit===false)$errors[]='Enter a valid registration limit.';else{$s=db()->prepare('UPDATE referral_promoters SET registration_limit=? WHERE id=?');$s->bind_param('ii',$limit,$id);$s->execute();flash('success','Promoter registration limit updated.');redirect('admin/referral_promoters.php');}}
 elseif($action==='toggle'){$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);$status=(string)($_POST['status']??'');if($id&&in_array($status,['active','inactive'],true)){$s=db()->prepare('UPDATE referral_promoters SET status=? WHERE id=?');$s->bind_param('si',$status,$id);$s->execute();flash('success','Referral promoter status updated.');redirect('admin/referral_promoters.php');}}
 elseif($action==='delete'){$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);if(!$id){flash('error','Invalid referral promoter.');redirect('admin/referral_promoters.php');}$linked=query_one('SELECT (SELECT COUNT(*) FROM users WHERE referral_promoter_id=?) registrations,(SELECT COUNT(*) FROM subscriptions WHERE referral_promoter_id=?) subscriptions','ii',[$id,$id]);if((int)($linked['registrations']??0)>0||(int)($linked['subscriptions']??0)>0){flash('error','This promoter has linked students or payments and cannot be deleted. Disable the account to preserve its history.');redirect('admin/referral_promoters.php');}$s=db()->prepare('DELETE FROM referral_promoters WHERE id=?');$s->bind_param('i',$id);$s->execute();flash($s->affected_rows===1?'success':'error',$s->affected_rows===1?'Referral promoter permanently deleted.':'Referral promoter was not found.');redirect('admin/referral_promoters.php');}
}
$rows=db()->query("SELECT r.*,(SELECT COUNT(*) FROM users u WHERE u.referral_promoter_id=r.id) registrations,(SELECT COUNT(*) FROM subscriptions s WHERE s.referral_promoter_id=r.id AND s.status='active') purchases,(SELECT COALESCE(SUM(s.amount_lkr),0) FROM subscriptions s WHERE s.referral_promoter_id=r.id AND s.status='active') revenue FROM referral_promoters r ORDER BY r.id DESC");$pageTitle='Referral promoters';include __DIR__.'/_top.php';
?>
<style>.ref-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:17px}.ref-grid>.card{margin:0}.code-cell{font-weight:950;letter-spacing:.08em;color:var(--violet)}.limit-form{display:flex;gap:6px;align-items:center}.limit-form input{width:88px;min-height:38px;margin:0}.limit-form button{white-space:nowrap}@media(max-width:800px){.ref-grid{grid-template-columns:1fr}}</style>
<h1>Referral promoters</h1><p class="muted">Create a private portal for each teacher or promoter, then give them their referral code and password.</p>
<?php foreach($errors as $error):?><div class="alert error"><?=e($error)?></div><?php endforeach;?>
<?php if($generatedCode):?><div class="alert"><strong>Portal account ready.</strong> Code: <strong><?=e($generatedCode)?></strong> · Password: <strong><?=e($generatedPassword)?></strong> · Login: <a href="<?=url('referral/login.php')?>"><?=e(url('referral/login.php'))?></a></div><?php endif;?>
<section class="ref-grid"><article class="card"><h2>Add a promoter</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="create"><label>Full name<input name="full_name" maxlength="100" required></label><label>Email <small class="muted">optional, can be used to log in</small><input type="email" name="email" maxlength="190"></label><label>Phone <small class="muted">optional, can be used to log in</small><input name="phone" maxlength="15"></label><label>Referral code<input name="referral_code" minlength="4" maxlength="24" pattern="[A-Za-z0-9-]{4,24}" placeholder="Example: SIR-NIMAL" autocapitalize="characters" required></label><label>Maximum student registrations <small class="muted">the code expires when this number is reached</small><input type="number" name="registration_limit" min="1" max="100000" value="50" required></label><label>Portal password<input type="password" name="password" minlength="8" autocomplete="new-password" required></label><button>Create promoter portal</button></form></article>
<article class="card scroll"><h2>Promoter accounts</h2><table><tr><th>Promoter</th><th>Code</th><th>Usage / limit</th><th>Paid</th><th>Status</th><th>Actions</th></tr><?php while($r=$rows->fetch_assoc()):$full=(int)$r['registrations']>=(int)$r['registration_limit'];?><tr><td><strong><?=e($r['full_name'])?></strong><br><small><?=e($r['email']?:$r['phone']?:'Code login only')?></small></td><td class="code-cell"><?=e($r['referral_code'])?></td><td><strong><?=intval($r['registrations'])?> / <?=intval($r['registration_limit'])?></strong><br><small><?=$full?'Limit reached':'Available: '.max(0,(int)$r['registration_limit']-(int)$r['registrations'])?></small></td><td><?=intval($r['purchases'])?><br><small>Rs. <?=e(number_format((float)$r['revenue'],0))?></small></td><td><?=e(ucfirst($r['status']))?></td><td><form method="post" class="limit-form"><?=csrf_field()?><input type="hidden" name="action" value="limit"><input type="hidden" name="id" value="<?=intval($r['id'])?>"><input type="number" name="registration_limit" min="1" max="100000" value="<?=intval($r['registration_limit'])?>" aria-label="Registration limit"><button class="alt" type="submit">Save</button></form><form method="post" style="margin-top:7px"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=intval($r['id'])?>"><input type="hidden" name="status" value="<?=$r['status']==='active'?'inactive':'active'?>"><button class="<?=$r['status']==='active'?'danger':'good'?>" type="submit"><?=$r['status']==='active'?'Disable':'Enable'?></button></form><form method="post" style="margin-top:7px" onsubmit="return confirm('Permanently delete this referral promoter? This action cannot be undone.')"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=intval($r['id'])?>"><button class="danger" type="submit">Delete permanently</button></form></td></tr><?php endwhile;?></table></article></section>
<?php include __DIR__.'/../includes/footer.php';?>
