<?php
$pageTitle='Student details';include __DIR__.'/_top.php';$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);$student=$id?query_one("SELECT u.*,g.grade_number FROM users u JOIN grades g ON g.id=u.grade_id WHERE u.id=?",'i',[$id]):null;if(!$student){flash('error','Student not found.');redirect('admin/students.php');}
$summary=query_one("SELECT (SELECT COALESCE(SUM(points),0) FROM student_points WHERE user_id=?) points,(SELECT COUNT(*) FROM lesson_progress WHERE user_id=? AND completed_at IS NOT NULL) lessons,(SELECT COUNT(*) FROM quiz_attempts WHERE user_id=?) quizzes,(SELECT COALESCE(ROUND(AVG(percentage)),0) FROM quiz_attempts WHERE user_id=?) average,(SELECT COUNT(*) FROM student_emblems WHERE user_id=?) emblems,(SELECT COUNT(*) FROM chat_messages WHERE user_id=? AND role='user') questions",'iiiiii',[$id,$id,$id,$id,$id,$id])??[];
$attempts=db()->prepare("SELECT qa.percentage,qa.score,qa.total_questions,qa.passed,qa.completed_at,q.title_en FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.user_id=? ORDER BY qa.id DESC LIMIT 10");$attempts->bind_param('i',$id);$attempts->execute();$quizRows=$attempts->get_result()->fetch_all(MYSQLI_ASSOC);
$activities=db()->prepare("SELECT event_type,detail,event_time FROM student_activity_events WHERE user_id=? ORDER BY id DESC LIMIT 12");$activities->bind_param('i',$id);$activities->execute();$events=$activities->get_result()->fetch_all(MYSQLI_ASSOC);
$subjects=db()->prepare("SELECT s.name_en,COUNT(DISTINCT l.id) total,COUNT(DISTINCT CASE WHEN lp.completed_at IS NOT NULL THEN l.id END) completed FROM subjects s JOIN lessons l ON l.subject_id=s.id AND l.grade_id=? AND l.status='active' LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=? WHERE s.grade_id=? GROUP BY s.id ORDER BY s.name_en");$subjects->bind_param('iii',$student['grade_id'],$id,$student['grade_id']);$subjects->execute();$subjectRows=$subjects->get_result()->fetch_all(MYSQLI_ASSOC);
?>
<style>.student-profile{display:flex;align-items:center;gap:18px;padding:27px;color:#fff;background:linear-gradient(135deg,#222d62,#5547d0 58%,#168bb0)}.detail-avatar{display:grid;place-items:center;flex:0 0 85px;height:85px;border:4px solid rgba(255,255,255,.75);border-radius:27px;background:#fff;color:var(--violet);font-size:2rem;font-weight:950}.student-profile h1{color:#fff;margin:5px 0}.student-profile p{margin:0;color:rgba(255,255,255,.75)}.detail-stats{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.detail-stat{margin:0;text-align:center}.detail-stat b{display:block;color:var(--violet);font-size:1.5rem}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.detail-grid>.card{margin:0}.detail-row{display:flex;justify-content:space-between;gap:15px;padding:11px 0;border-bottom:1px solid var(--line)}.detail-row span{color:var(--muted)}.subject-progress{margin:14px 0}.subject-progress header{display:flex;justify-content:space-between;margin-bottom:6px}.timeline-item{display:flex;gap:10px;padding:10px 0;border-bottom:1px solid var(--line)}.timeline-item i{width:9px;height:9px;flex:0 0 9px;margin-top:7px;border-radius:50%;background:var(--mint)}.timeline-item small{display:block;color:var(--muted)}@media(max-width:800px){.detail-stats{grid-template-columns:repeat(3,1fr)}.detail-grid{grid-template-columns:1fr}}@media(max-width:480px){.student-profile{display:block}.detail-avatar{margin-bottom:13px}.detail-stats{grid-template-columns:repeat(2,1fr)}}</style>
<p><a href="students.php">← All students</a></p><section class="card student-profile"><div class="detail-avatar"><?=e(mb_strtoupper(mb_substr($student['full_name'],0,1)))?></div><div><span class="badge"><?=e(ucfirst($student['status']))?> student</span><h1><?=e($student['full_name'])?></h1><p>@<?=e($student['username'])?> · Grade <?=intval($student['grade_number'])?> · <?=e($student['medium'])?> Medium</p></div></section>
<section class="detail-stats"><?php foreach([['Points',$summary['points']??0],['Lessons',$summary['lessons']??0],['Quizzes',$summary['quizzes']??0],['Average',($summary['average']??0).'%'],['Emblems',$summary['emblems']??0],['AI questions',$summary['questions']??0]] as $x):?><article class="card detail-stat"><b><?=e($x[1])?></b><small><?=e($x[0])?></small></article><?php endforeach;?></section>
<section class="detail-grid"><article class="card"><h2>👤 Account information</h2><?php foreach(['Email'=>$student['email'],'School'=>$student['school_name']?:'Not provided','Grade'=>'Grade '.$student['grade_number'],'Medium'=>$student['medium'],'Joined'=>date('d M Y, g:i A',strtotime($student['created_at'])),'Subscription'=>$student['subscription_expires_at']?'Until '.date('d M Y',strtotime($student['subscription_expires_at'])):'Free plan'] as $label=>$value):?><div class="detail-row"><span><?=e($label)?></span><strong><?=e($value)?></strong></div><?php endforeach;?></article><article class="card"><h2>📚 Subject completion</h2><?php foreach($subjectRows as $row):$pct=$row['total']?(int)round(100*$row['completed']/$row['total']):0;?><div class="subject-progress"><header><strong><?=e($row['name_en'])?></strong><span><?=$row['completed']?> / <?=$row['total']?> · <?=$pct?>%</span></header><div class="progress"><span style="width:<?=$pct?>%"></span></div></div><?php endforeach;?></article><article class="card"><h2>📝 Recent quiz results</h2><?php if(!$quizRows):?><p class="muted">No quiz attempts yet.</p><?php endif;foreach($quizRows as $quiz):?><div class="detail-row"><span><?=e($quiz['title_en'])?><small style="display:block"><?=e(date('d M Y',strtotime($quiz['completed_at'])))?></small></span><strong><?=$quiz['percentage']?>% <?=$quiz['passed']?'✅':'🔁'?></strong></div><?php endforeach;?></article><article class="card"><h2>⚡ Recent activity</h2><?php if(!$events):?><p class="muted">No activity recorded yet.</p><?php endif;foreach($events as $event):?><div class="timeline-item"><i></i><span><strong><?=e(ucwords(str_replace('_',' ',$event['event_type'])))?></strong><span><?=e(mb_strimwidth($event['detail'],0,95,'…'))?></span><small><?=e(date('d M Y, g:i A',strtotime($event['event_time'])))?></small></span></div><?php endforeach;?></article></section>
<?php include __DIR__.'/../includes/footer.php';
