<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_login();
$gradeId=(int)user()['grade_id'];$subjectRows=[];$lessonRows=[];$contentError=false;
$medium=(string)user()['medium'];$s=db()->prepare("SELECT DISTINCT s.id,s.name_en,s.name_si,s.name_ta FROM subjects s JOIN lessons l ON l.subject_id=s.id AND l.grade_id=s.grade_id AND l.status='active' AND l.content_source='textbook' AND (l.medium='All' OR l.medium=?) WHERE s.grade_id=? AND s.status='active' ORDER BY s.name_en");if($s){$s->bind_param('si',$medium,$gradeId);if($s->execute())$subjectRows=$s->get_result()->fetch_all(MYSQLI_ASSOC);else$contentError=true;$s->close();}else$contentError=true;
$s=db()->prepare("SELECT id,subject_id,title_en,title_si,title_ta FROM lessons WHERE grade_id=? AND status='active' AND content_source='textbook' AND (medium='All' OR medium=?) ORDER BY display_order");if($s){$s->bind_param('is',$gradeId,$medium);if($s->execute())$lessonRows=$s->get_result()->fetch_all(MYSQLI_ASSOC);else$contentError=true;$s->close();}else$contentError=true;
$selectedLesson=filter_input(INPUT_GET,'lesson_id',FILTER_VALIDATE_INT)?:0;
$chatLanguage=['Sinhala'=>'si','Tamil'=>'ta','English'=>'en'][user()['medium']]??'en';
$gradeNumber=user_grade_number();
$chatText=['en'=>['title'=>'AI Tutor','clear'=>'Clear chat','free'=>'Free: 5 messages per day','paid'=>'Unlimited Premium','error'=>'Lesson choices could not be loaded. You can still send a question.','subjects'=>'All subjects','lesson'=>'Select lesson','typing'=>'EduBuddy is thinking…','simple'=>'Explain more simply','example'=>'Give me an example','quiz'=>'Create a quiz','translate'=>'Translate answer','placeholder'=>'Ask your Grade '.$gradeNumber.' question…','send'=>'Send'],'si'=>['title'=>'අලුත් සර්','clear'=>'සංවාදය මකන්න','free'=>'නොමිලේ: දිනකට පණිවිඩ 5ක්','paid'=>'අසීමිත වාරික සේවාව','error'=>'පාඩම් තේරීම් පූරණය කළ නොහැකි විය. ඔබට තවමත් ප්‍රශ්නයක් යැවිය හැක.','subjects'=>'සියලු විෂයයන්','lesson'=>'පාඩමක් තෝරන්න','typing'=>'EduBuddy සිතමින් සිටී…','simple'=>'තවත් සරලව පැහැදිලි කරන්න','example'=>'උදාහරණයක් දෙන්න','quiz'=>'කෙටි ප්‍රශ්නාවලියක් සාදන්න','translate'=>'පිළිතුර පරිවර්තනය කරන්න','placeholder'=>'ඔබේ '.$gradeNumber.' ශ්‍රේණියේ ප්‍රශ්නය අසන්න…','send'=>'යවන්න'],'ta'=>['title'=>'AI ஆசிரியர்','clear'=>'உரையாடலை அழி','free'=>'இலவசம்: நாளுக்கு 5 செய்திகள்','paid'=>'வரம்பற்ற பிரீமியம்','error'=>'பாடத் தேர்வுகளை ஏற்ற முடியவில்லை. நீங்கள் இன்னும் கேள்வியை அனுப்பலாம்.','subjects'=>'அனைத்து பாடங்களும்','lesson'=>'பாடத்தைத் தேர்ந்தெடுக்கவும்','typing'=>'EduBuddy சிந்திக்கிறது…','simple'=>'இன்னும் எளிமையாக விளக்கவும்','example'=>'ஓர் உதாரணம் தரவும்','quiz'=>'சிறு வினாடி வினா உருவாக்கவும்','translate'=>'பதிலை மொழிபெயர்க்கவும்','placeholder'=>'உங்கள் தரம் '.$gradeNumber.' கேள்வியைக் கேளுங்கள்…','send'=>'அனுப்பு']][$chatLanguage];
$chatText['typing']=str_replace('EduBuddy','K Education',$chatText['typing']);
if($chatLanguage==='en')$chatText['placeholder']='Ask your Grade '.$gradeNumber.' question…';
$pageTitle=$chatText['title'];include __DIR__.'/../includes/header.php';
?>
<style>
.tutor-shell{display:grid;grid-template-columns:285px minmax(0,1fr);min-height:690px;border-radius:30px;overflow:hidden;background:#fff;border:1px solid rgba(219,226,241,.9);box-shadow:0 25px 70px rgba(40,52,105,.16)}
.tutor-side{position:relative;padding:24px;background:linear-gradient(165deg,#241d69 0%,#4d3dcc 52%,#126fa5 100%);color:#fff;overflow:hidden}.tutor-side:before,.tutor-side:after{content:"";position:absolute;border-radius:50%;background:rgba(255,255,255,.08)}.tutor-side:before{width:230px;height:230px;right:-130px;top:-70px}.tutor-side:after{width:170px;height:170px;left:-95px;bottom:35px}.tutor-brand,.picker,.side-actions{position:relative;z-index:1}.tutor-brand{display:flex;gap:13px;align-items:center;margin-bottom:28px}.tutor-avatar{display:grid;place-items:center;flex:0 0 50px;width:50px;height:50px;border-radius:17px;background:linear-gradient(135deg,#fff,#dceeff);color:#4939bc;font-size:1.55rem;box-shadow:0 10px 28px rgba(10,13,57,.25)}.tutor-brand h1{font-size:1.24rem;margin:0}.tutor-brand p{margin:3px 0 0;color:rgba(255,255,255,.72);font-size:.78rem}.online{display:inline-flex;align-items:center;gap:6px;font-size:.7rem;font-weight:800;color:#bfffe9}.online:before{content:"";width:7px;height:7px;border-radius:50%;background:#4ff0b8;box-shadow:0 0 0 4px rgba(79,240,184,.15)}
.picker-title{display:flex;align-items:center;gap:8px;margin:0 0 13px;font-size:.78rem;text-transform:uppercase;letter-spacing:.09em;color:rgba(255,255,255,.72)}.picker label{display:block;margin:0 0 13px;font-size:.72rem;color:rgba(255,255,255,.75)}.picker select{margin:5px 0 0;min-height:48px;background:rgba(255,255,255,.12);border-color:rgba(255,255,255,.22);color:#fff;box-shadow:none}.picker select:focus{background:rgba(255,255,255,.18);border-color:#b9deff}.picker select option{color:#18233f;background:#fff}.selection-note{display:flex;gap:9px;padding:12px;border-radius:15px;background:rgba(13,14,65,.23);font-size:.76rem;color:rgba(255,255,255,.78);line-height:1.45}.selection-note b{color:#fff;display:block}.side-actions{position:absolute;left:24px;right:24px;bottom:24px}.clear-chat{width:100%;min-height:44px;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.18);box-shadow:none;font-size:.8rem}.clear-chat:hover{background:rgba(255,255,255,.18);box-shadow:none}
.tutor-main{display:flex;min-width:0;flex-direction:column;background:linear-gradient(180deg,#fbfcff,#f4f7ff)}.tutor-top{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:17px 21px;background:rgba(255,255,255,.88);border-bottom:1px solid #e7ebf4}.tutor-top strong{display:block;font-size:.92rem}.tutor-top small{display:block;color:var(--muted)}.plan-chip{padding:7px 11px;border-radius:999px;background:#eeeaff;color:#5544cb;font-size:.7rem;font-weight:900;white-space:nowrap}
#messages{flex:1;height:475px;overflow:auto;padding:23px;scroll-behavior:smooth}.chat-welcome{max-width:570px;margin:55px auto;text-align:center}.welcome-orb{display:grid;place-items:center;width:82px;height:82px;margin:auto;border-radius:27px;background:linear-gradient(135deg,#6554e8,#2588f6);box-shadow:0 18px 42px rgba(72,80,210,.28);font-size:2.3rem;transform:rotate(-3deg)}.chat-welcome h2{margin:21px 0 8px;font-size:1.55rem}.chat-welcome p{margin:0 auto 20px;color:var(--muted);max-width:430px}.starter-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.starter{min-height:54px;padding:10px 12px;border-radius:16px;background:#fff;border:1px solid #e2e7f2;box-shadow:0 7px 20px rgba(48,64,120,.07);color:#34415f;font-size:.78rem;text-align:left}.starter:hover{border-color:#bdb4ff;background:#f7f5ff;color:#4938bd;box-shadow:0 10px 24px rgba(65,63,150,.12)}
.message-row{display:flex;gap:10px;align-items:flex-end;margin:15px 0;animation:messageIn .3s ease}.message-row.user{justify-content:flex-end}.message-avatar{display:grid;place-items:center;flex:0 0 34px;width:34px;height:34px;border-radius:12px;background:linear-gradient(135deg,#edeaff,#e2f2ff);font-size:1rem}.chat-message{max-width:min(78%,680px);padding:13px 16px;border-radius:20px;line-height:1.65;box-shadow:0 8px 23px rgba(48,62,112,.08)}.message-row.user .chat-message{border-bottom-right-radius:6px;background:linear-gradient(135deg,#5445d6,#287eea);color:#fff}.message-row.assistant .chat-message{border-bottom-left-radius:6px;background:#fff;color:#17223b;border:1px solid #e3e8f3}.chat-message p{margin:0 0 10px}.chat-message p:last-child{margin-bottom:0}.chat-message h2,.chat-message h3,.chat-message h4{color:#4137a7;line-height:1.3;margin:18px 0 8px}.chat-message h2:first-child,.chat-message h3:first-child{margin-top:0}.chat-message h2{font-size:1.22rem;border-bottom:2px solid #eeeaff;padding-bottom:7px}.chat-message h3{font-size:1.06rem}.chat-message ul,.chat-message ol{margin:7px 0 12px;padding-left:24px}.chat-message li{margin:5px 0}.chat-message strong{color:#253d91}.message-row.user strong{color:#fff}.chat-message hr{border:0;height:2px;background:linear-gradient(90deg,#dcd7ff,transparent);margin:16px 0}.page-ref{display:inline-block;background:#eef4ff;color:#3156a6;border-radius:999px;padding:2px 8px;font-size:.78em;font-weight:800;white-space:nowrap}
#typing{display:flex;align-items:center;gap:10px;padding:4px 23px 13px;color:#5d6590;font-size:.78rem;font-weight:800}#typing[hidden]{display:none}.typing-bubble{display:flex;gap:4px;padding:11px 14px;border-radius:16px 16px 16px 5px;background:#fff;border:1px solid #e3e8f3}.typing-bubble i{width:6px;height:6px;border-radius:50%;background:#6c5ce3;animation:typingDot .8s infinite alternate}.typing-bubble i:nth-child(2){animation-delay:.18s}.typing-bubble i:nth-child(3){animation-delay:.36s}
.composer{padding:12px 18px 18px;background:rgba(255,255,255,.94);border-top:1px solid #e3e8f3}.suggestions{display:flex;gap:8px;overflow:auto;padding:0 0 10px;scrollbar-width:none}.suggestions::-webkit-scrollbar{display:none}.suggestions button{flex:0 0 auto;min-height:34px;padding:7px 11px;border-radius:999px;background:#f0efff;color:#5646c8;box-shadow:none;font-size:.72rem}.chat-send{display:grid;grid-template-columns:1fr auto;align-items:end;gap:10px;padding:7px 7px 7px 15px;border:1.5px solid #dfe5f1;border-radius:20px;background:#f9fbff;transition:.2s}.chat-send:focus-within{border-color:#7668ed;background:#fff;box-shadow:0 0 0 5px rgba(101,84,232,.08)}.chat-send textarea{min-height:44px;max-height:140px;margin:0;padding:10px 0;border:0;background:transparent;box-shadow:none;resize:none;line-height:1.45}.chat-send textarea:focus{box-shadow:none}.send-button{width:46px;height:46px;min-height:46px;padding:0;border-radius:15px;font-size:1.1rem}.composer-hint{display:flex;justify-content:space-between;margin:7px 4px 0;color:#8a94aa;font-size:.65rem}
@keyframes messageIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@keyframes typingDot{to{transform:translateY(-5px);opacity:.35}}
@media(max-width:800px){.tutor-shell{display:block;min-height:0}.tutor-side{padding:18px}.tutor-brand{margin-bottom:17px}.picker{display:grid;grid-template-columns:1fr 1fr;gap:10px}.picker-title,.selection-note{grid-column:1/-1}.picker label{margin:0}.side-actions{position:static;margin-top:12px}.clear-chat{width:auto}.tutor-main{min-height:640px}#messages{height:430px}.chat-welcome{margin:35px auto}.tutor-side:after{display:none}}
@media(max-width:520px){.wrap{padding-inline:8px}.tutor-shell{border-radius:23px}.picker{grid-template-columns:1fr}.picker-title,.selection-note{grid-column:auto}.tutor-top{padding:13px 15px}#messages{height:390px;padding:15px}.chat-message{max-width:88%;padding:12px 13px}.message-avatar{display:none}.starter-grid{grid-template-columns:1fr}.chat-welcome{margin:28px auto}.welcome-orb{width:68px;height:68px;border-radius:23px}.composer{padding:10px}.composer-hint span:first-child{display:none}}
.mobile-context-toggle,.mobile-clear{display:none}
@media(max-width:800px){.wrap{padding:8px 8px 88px}.tutor-shell{display:flex;flex-direction:column;height:calc(100dvh - 158px);min-height:540px;border-radius:23px}.tutor-side{flex:0 0 auto;padding:11px 13px;overflow:visible}.tutor-side:before,.tutor-side:after{display:none}.tutor-brand{margin:0;padding-right:50px}.tutor-avatar{width:40px;height:40px;flex-basis:40px;border-radius:13px;font-size:1.15rem}.tutor-brand h1{font-size:.96rem}.tutor-brand p{font-size:.68rem;white-space:nowrap;max-width:58vw;overflow:hidden;text-overflow:ellipsis}.online{display:none}.mobile-context-toggle{display:grid;place-items:center;position:absolute;z-index:4;right:12px;top:11px;width:40px;height:40px;min-height:40px;padding:0;border-radius:13px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.2);box-shadow:none}.mobile-context-toggle[aria-expanded="true"]{background:#fff;color:#4939bc}.picker{display:none;grid-template-columns:1fr 1fr;gap:9px;padding-top:13px}.tutor-side.context-open .picker{display:grid;animation:messageIn .2s ease}.picker-title,.selection-note{grid-column:1/-1}.picker-title{margin-bottom:0}.picker label{margin:0}.picker select{min-height:44px;margin-bottom:0;padding:10px;font-size:.8rem}.selection-note{padding:9px;font-size:.7rem}.side-actions{display:none}.tutor-main{flex:1;min-height:0}.tutor-top{flex:0 0 auto;padding:10px 13px}.tutor-top strong{max-width:58vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tutor-top small{font-size:.68rem}.plan-chip{display:none}.mobile-clear{display:grid;place-items:center;width:38px;height:38px;min-height:38px;padding:0;border-radius:12px;background:#f1efff;color:#5b49cd;box-shadow:none}.tutor-main #messages{flex:1;height:auto;min-height:0;padding:15px}.chat-welcome{margin:24px auto}.composer{flex:0 0 auto;padding:8px 10px 10px}.suggestions{padding-bottom:7px}.suggestions button{min-height:32px}.composer-hint{display:none}.chat-send{border-radius:18px}.send-button{width:44px;height:44px;min-height:44px}.message-row{margin:11px 0}}
@media(max-width:520px){.picker{grid-template-columns:1fr}.picker-title,.selection-note{grid-column:auto}.chat-message{max-width:90%;padding:11px 13px;font-size:.92rem}.starter-grid{gap:8px}.starter{min-height:48px}.chat-welcome h2{font-size:1.3rem}.chat-welcome p{font-size:.85rem}.welcome-orb{width:62px;height:62px;border-radius:20px;font-size:1.8rem}.tutor-main #messages{padding:12px}.suggestions button{font-size:.68rem}.chat-send textarea{font-size:16px}}
</style>
<section class="tutor-shell">
 <aside class="tutor-side">
  <div class="tutor-brand"><div class="tutor-avatar">🎓</div><div><span class="online">ONLINE</span><h1><?=e($chatText['title'])?></h1><p>Grade <?=$gradeNumber?> · <?=e(user()['medium'])?> medium</p></div></div><button class="mobile-context-toggle" id="mobileContextToggle" type="button" aria-expanded="false" aria-label="Choose lesson">📚</button>
  <div class="picker"><h2 class="picker-title">📚 Study context</h2>
   <label>Subject<select id="subject" required><option value=""><?=e($chatText['subjects'])?></option><?php foreach($subjectRows as $subject):?><option value="<?=(int)$subject['id']?>"><?=e(locale_value($subject,'name'))?></option><?php endforeach;?></select></label>
   <label>Textbook lesson<select id="lesson" required><option value=""><?=e($chatText['lesson'])?></option><?php foreach($lessonRows as $lesson):?><option data-subject="<?=(int)$lesson['subject_id']?>" data-lesson-id="<?=(int)$lesson['id']?>" value="lesson-<?=(int)$lesson['id']?>"<?=$selectedLesson===(int)$lesson['id']?' selected':''?>><?=e(locale_value($lesson,'title'))?></option><?php endforeach;?></select></label>
   <div class="selection-note"><span>🛡️</span><span><b>Textbook-grounded answers</b>Select a lesson and the tutor will answer from that exact Grade <?=$gradeNumber?> book.</span></div>
  </div>
  <div class="side-actions"><button class="clear-chat" id="clearChat" type="button">🗑️ <?=e($chatText['clear'])?></button></div>
 </aside>
 <div class="tutor-main">
  <header class="tutor-top"><div><strong id="conversationTitle">General education chat</strong><small id="conversationMeta">Ask any education-related question</small></div><?php if(is_premium()):?><span class="plan-chip"><?=e($chatText['paid'])?></span><?php else:$chatOffer=premium_offer_for_user((int)user()['id']);?><a class="plan-chip" href="<?=url('subscription.php')?>">Upgrade · Rs. <?=e(number_format($chatOffer['total'],0))?></a><?php endif;?><button class="mobile-clear" id="mobileClear" type="button" aria-label="Clear chat">🗑️</button></header>
  <?php if($contentError):?><div class="alert error"><?=e($chatText['error'])?></div><?php endif;?>
  <div id="messages"><div class="chat-welcome" id="chatWelcome"><div class="welcome-orb">✨</div><h2>What would you like to learn?</h2><p>Ask any educational question normally, or select a textbook lesson for lesson-specific help.</p><div class="starter-grid"><button class="starter" data-prompt="Explain a useful topic for my grade">🧠 Teach me something</button><button class="starter" data-prompt="Help me make a study plan">📝 Make a study plan</button><button class="starter" data-prompt="Give me a simple educational example">💡 Give an example</button><button class="starter" data-prompt="Create five general revision questions for my grade">🎯 Test my knowledge</button></div></div></div>
  <div id="typing" hidden><span class="typing-bubble"><i></i><i></i><i></i></span><span><?=e($chatText['typing'])?></span></div>
  <div class="composer"><div class="suggestions" id="suggestions"><?php foreach(['simple'=>'🪄','example'=>'💡','quiz'=>'🎯','translate'=>'🌐'] as $key=>$icon):?><button type="button" data-prompt="<?=e($chatText[$key])?>"><?=$icon?> <?=e($chatText[$key])?></button><?php endforeach;?></div><form id="chatForm" class="chat-send"><textarea id="message" maxlength="1000" rows="1" placeholder="<?=e($chatText['placeholder'])?>" required></textarea><button class="send-button" type="submit" aria-label="<?=e($chatText['send'])?>">➤</button></form><div class="composer-hint"><span>Enter to send · Shift + Enter for a new line</span><span id="charCount">0 / 1000</span></div></div>
 </div>
</section>
<script>window.EDU={send:<?=json_encode(url('chatbot/send.php'))?>,history:<?=json_encode(url('chatbot/history.php'))?>,csrf:<?=json_encode(csrf_token())?>};</script><script src="<?=url('assets/js/chatbot.js')?>?v=<?=filemtime(__DIR__.'/../assets/js/chatbot.js')?>"></script>
<?php include __DIR__.'/../includes/footer.php';?>
