<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_parent_guest();$error='';$email='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$email=strtolower(trim((string)($_POST['email']??'')));$password=(string)($_POST['password']??'');
 $p=query_one('SELECT * FROM parents WHERE email=? AND status="active"','s',[$email]);
 if($p&&password_verify($password,$p['password_hash'])){unset($p['password_hash']);session_regenerate_id(true);$_SESSION['parent']=$p;unset($_SESSION['user']);redirect('parent/dashboard.php');}
 $error='The email or password is incorrect.';
}
$pageTitle='Parent login';include __DIR__.'/../includes/header.php';
?>
<style>
.parent-login{display:grid;grid-template-columns:1.08fr .92fr;max-width:980px;min-height:650px;margin:18px auto;border-radius:32px;overflow:hidden;background:#fff;border:1px solid rgba(220,227,242,.9);box-shadow:0 28px 80px rgba(39,47,100,.18)}.login-story{position:relative;display:flex;flex-direction:column;justify-content:space-between;padding:42px;background:linear-gradient(145deg,#171147 0%,#4935be 53%,#087c9a 100%);color:#fff;overflow:hidden}.login-story:before,.login-story:after{content:"";position:absolute;border-radius:50%;background:rgba(255,255,255,.08)}.login-story:before{width:310px;height:310px;right:-145px;top:-120px}.login-story:after{width:210px;height:210px;left:-120px;bottom:-80px}.story-content,.trust-row{position:relative;z-index:1}.parent-mark{display:grid;place-items:center;width:64px;height:64px;border-radius:21px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.18);font-size:1.8rem;box-shadow:0 16px 35px rgba(7,10,44,.22)}.login-story .badge{margin-top:26px;background:rgba(255,255,255,.13);color:#fff}.login-story h1{max-width:520px;margin:16px 0 11px;font-size:clamp(2.1rem,5vw,3.35rem)}.login-story p{max-width:500px;color:rgba(255,255,255,.76)}.feature-list{display:grid;gap:12px;margin-top:28px}.feature{display:flex;align-items:center;gap:11px;padding:11px 13px;border-radius:15px;background:rgba(255,255,255,.09);font-size:.83rem;font-weight:750}.feature i{display:grid;place-items:center;width:32px;height:32px;border-radius:10px;background:rgba(255,255,255,.13);font-style:normal}.trust-row{display:flex;align-items:center;gap:9px;color:rgba(255,255,255,.68);font-size:.74rem}.trust-row span{color:#60f1c1}.login-panel{display:flex;align-items:center;padding:44px}.login-box{width:100%;max-width:390px;margin:auto}.login-box>span{font-size:2rem}.login-box h2{margin:12px 0 7px;font-size:1.85rem}.login-box .intro{margin:0 0 25px;color:var(--muted)}.login-box label{display:block;margin-top:10px}.field-wrap{position:relative}.field-wrap input{padding-left:45px;margin-bottom:12px}.field-icon{position:absolute;left:15px;top:19px;color:#78839c;pointer-events:none}.password-toggle{position:absolute;right:7px;top:12px;width:38px;height:38px;min-height:38px;padding:0;border-radius:11px;background:transparent;color:#68738c;box-shadow:none}.password-toggle:hover{background:#eeefff;box-shadow:none}.login-submit{width:100%;margin-top:9px}.login-meta{display:flex;align-items:center;justify-content:center;gap:8px;margin:19px 0;color:var(--muted);font-size:.78rem}.login-meta:before,.login-meta:after{content:"";height:1px;flex:1;background:var(--line)}.portal-links{display:grid;grid-template-columns:1fr 1fr;gap:9px}.portal-link{padding:12px;border-radius:14px;background:#f5f7fc;text-decoration:none;text-align:center;color:#505d78;font-size:.78rem;font-weight:850}.portal-link:hover{background:#eeeaff;color:#5544ca}.security-note{display:flex;justify-content:center;gap:6px;margin-top:20px;color:#8a94a8;font-size:.68rem}
@media(max-width:760px){.wrap{padding:10px 8px 92px}.parent-login{grid-template-columns:1fr;min-height:0;margin:0;border-radius:24px}.login-story{padding:24px}.login-story h1{font-size:1.85rem}.feature-list{grid-template-columns:1fr 1fr;margin-top:19px}.feature{padding:9px;font-size:.73rem}.trust-row{display:none}.login-panel{padding:28px 22px}}
@media(max-width:430px){.login-story{padding:20px}.parent-mark{width:51px;height:51px;border-radius:17px;font-size:1.4rem}.login-story .badge{margin-top:17px}.login-story h1{margin:11px 0 6px;font-size:1.6rem}.login-story p{font-size:.8rem;margin-bottom:0}.feature-list{gap:7px}.feature i{display:none}.login-panel{padding:24px 18px}.login-box h2{font-size:1.55rem}.portal-links{grid-template-columns:1fr}}
</style>
<section class="parent-login">
 <aside class="login-story"><div class="story-content"><div class="parent-mark">👪</div><span class="badge">K Education Parent Portal</span><h1>Stay connected to their learning.</h1><p>See meaningful progress, exact quiz results and live study updates—all in one safe parent dashboard.</p><div class="feature-list"><div class="feature"><i>🔔</i><span>Exact live activity alerts</span></div><div class="feature"><i>🏆</i><span>Current Grade ranking</span></div><div class="feature"><i>📊</i><span>Lessons and quiz progress</span></div><div class="feature"><i>🔐</i><span>Secure child linking</span></div></div></div><div class="trust-row"><span>●</span> Private monitoring access for linked parents and guardians</div></aside>
 <div class="login-panel"><div class="login-box"><span>👋</span><h2>Welcome back</h2><p class="intro">Sign in to open your parent monitoring dashboard.</p><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><form method="post"><?=csrf_field()?><label for="parentEmail">Email address</label><div class="field-wrap"><span class="field-icon">✉</span><input id="parentEmail" type="email" name="email" value="<?=e($email)?>" placeholder="parent@example.com" autocomplete="email" required></div><label for="parentPassword">Password</label><div class="field-wrap"><span class="field-icon">🔒</span><input id="parentPassword" type="password" name="password" placeholder="Enter your password" autocomplete="current-password" required><button class="password-toggle" id="passwordToggle" type="button" aria-label="Show password">👁</button></div><button class="login-submit" type="submit">Open Parent Dashboard →</button></form><div class="login-meta">or continue with</div><div class="portal-links"><a class="portal-link" href="register.php">＋ Create parent account</a><a class="portal-link" href="<?=url('login.php')?>">🎒 Student login</a></div><p class="security-note">🛡️ Your account and linked-child information stay private.</p></div></div>
</section>
<script>document.getElementById('passwordToggle').addEventListener('click',function(){const input=document.getElementById('parentPassword'),show=input.type==='password';input.type=show?'text':'password';this.textContent=show?'🙈':'👁';this.setAttribute('aria-label',show?'Hide password':'Show password')});</script>
<?php include __DIR__.'/../includes/footer.php';?>
