<?php
require_once __DIR__.'/../includes/auth.php';require_parent_guest();$errors=[];$name=trim((string)($_POST['full_name']??''));$email=strtolower(trim((string)($_POST['email']??'')));
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$password=(string)($_POST['password']??'');if(mb_strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<8||$password!==($_POST['confirm_password']??''))$errors[]='Please enter a valid name, email and matching password of at least 8 characters.';if(!$errors){$db=db();$s=$db->prepare('INSERT INTO parents(full_name,email,password_hash,status) VALUES(?,?,?,\'active\')');if(!$s){error_log('Parent registration prepare failed: '.$db->error);$errors[]='Parent registration is temporarily unavailable. Please try again shortly.';}else{$hash=password_hash($password,PASSWORD_DEFAULT);$s->bind_param('sss',$name,$email,$hash);if($s->execute()){flash('success','Parent account created. Please log in.');redirect('parent/login.php');}$errorNumber=$s->errno;$errorText=$s->error;$s->close();error_log('Parent registration insert failed: '.$errorNumber.' '.$errorText);$errors[]=$errorNumber===1062?'This email already has a parent account.':'Account could not be created. Please try again.';}}}
$pageTitle='Parent registration';include __DIR__.'/../includes/header.php';?>
<link rel="stylesheet" href="<?=url('assets/css/parent-portal.css')?>?v=<?=filemtime(__DIR__.'/../assets/css/parent-portal.css')?>">
<section class="parent-register">
<aside class="parent-register-art"><div><div class="parent-family-mark">&#128106;</div><h1>Be part of every learning milestone.</h1><p>Create your secure parent account, link your child with their one-time code, and turn learning activity into meaningful encouragement.</p><ul class="parent-benefits"><li><b>&#10003;</b> Live learning updates</li><li><b>&#10003;</b> Quiz and lesson insights</li><li><b>&#10003;</b> Grade ranking overview</li><li><b>&#10003;</b> Private child linking</li></ul></div><small>Protected access designed for parents and guardians.</small></aside>
<div class="parent-register-form"><div class="parent-register-box"><span class="eyebrow">K Education Parent Portal</span><h2>Create your account</h2><p class="muted">It takes less than a minute. You can link a student after signing in.</p><?php foreach($errors as $x):?><div class="alert error" role="alert"><?=e($x)?></div><?php endforeach;?>
<form method="post" id="parentRegisterForm"><?=csrf_field()?><label>Full name<input name="full_name" value="<?=e($name)?>" placeholder="Your full name" autocomplete="name" required></label><label>Email address<input type="email" name="email" value="<?=e($email)?>" placeholder="parent@example.com" autocomplete="email" required></label><div class="parent-field-grid"><label>Password<input type="password" name="password" minlength="8" placeholder="At least 8 characters" autocomplete="new-password" required></label><label>Confirm password<input type="password" name="confirm_password" minlength="8" placeholder="Repeat password" autocomplete="new-password" required></label></div><button class="parent-create-btn" type="submit">Create secure parent account &rarr;</button></form><p class="parent-signin-link">Already registered? <a href="login.php"><strong>Sign in to Parent Portal</strong></a></p></div></div>
</section>
<?php include __DIR__.'/../includes/footer.php'; ?>
