<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';require_referral_promoter();$promoter=referral_promoter_user();$id=(int)$promoter['id'];
$summary=query_one("SELECT COUNT(DISTINCT u.id) registrations,COUNT(DISTINCT CASE WHEN s.status='active' THEN u.id END) premium_students,COUNT(CASE WHEN s.status='pending' THEN 1 END) pending_payments,COALESCE(SUM(CASE WHEN s.status='active' THEN s.amount_lkr ELSE 0 END),0) paid_total FROM users u LEFT JOIN subscriptions s ON s.user_id=u.id AND s.referral_promoter_id=? WHERE u.referral_promoter_id=?",'ii',[$id,$id])??[];
$q=db()->prepare("SELECT u.full_name,u.phone,u.school_name,u.medium,u.created_at,g.grade_number,(SELECT COUNT(*) FROM subscriptions s WHERE s.user_id=u.id AND s.referral_promoter_id=? AND s.status='active') purchases,(SELECT MAX(s.starts_at) FROM subscriptions s WHERE s.user_id=u.id AND s.referral_promoter_id=? AND s.status='active') purchased_at,(SELECT MAX(s.amount_lkr) FROM subscriptions s WHERE s.user_id=u.id AND s.referral_promoter_id=? AND s.status='active') paid_amount,(SELECT COUNT(*) FROM subscriptions s WHERE s.user_id=u.id AND s.referral_promoter_id=? AND s.status='pending') pending FROM users u JOIN grades g ON g.id=u.grade_id WHERE u.referral_promoter_id=? ORDER BY u.created_at DESC");$q->bind_param('iiiii',$id,$id,$id,$id,$id);$q->execute();$students=$q->get_result()->fetch_all(MYSQLI_ASSOC);$registrationLink=((!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').url('register.php?ref='.rawurlencode((string)$promoter['referral_code']));$pageTitle='Referral dashboard';include __DIR__.'/../includes/header.php';
?>
<style>.ref-hero{display:flex;justify-content:space-between;gap:18px;align-items:center;background:linear-gradient(135deg,#171b4d,#5340cb 58%,#0785a0);color:#fff}.ref-hero p{color:rgba(255,255,255,.75)}.ref-code{padding:15px 20px;border-radius:18px;background:rgba(255,255,255,.13);font-size:1.35rem;font-weight:950;letter-spacing:.11em}.ref-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:17px}.ref-metrics .card{margin:0}.ref-metrics b{display:block;font-size:1.8rem;color:var(--violet)}@media(max-width:750px){.ref-hero{display:block}.ref-code{display:inline-block;margin-top:12px}.ref-metrics{grid-template-columns:1fr 1fr}}</style>
<section class="card ref-hero"><div><span class="badge">Referral partner</span><h1>Hello, <?=e($promoter['full_name'])?></h1><p>Share your code. Students receive Rs. <?=e(number_format(referral_discount_lkr(),0))?> off the Rs. <?=e(number_format(premium_base_price_lkr(),0))?> Premium plan.</p><button type="button" class="btn alt" id="copyReferralLink" data-link="<?=e($registrationLink)?>">Copy registration link</button></div><div class="ref-code"><?=e($promoter['referral_code'])?></div></section>
<section class="ref-metrics"><article class="card"><small>Joined with your code</small><b><?=intval($summary['registrations']??0)?></b></article><article class="card"><small>Premium students</small><b><?=intval($summary['premium_students']??0)?></b></article><article class="card"><small>Payments pending</small><b><?=intval($summary['pending_payments']??0)?></b></article><article class="card"><small>Verified payment value</small><b>Rs. <?=e(number_format((float)($summary['paid_total']??0),0))?></b></article></section>
<section class="card"><div class="row" style="justify-content:space-between"><div><h2>Referred students</h2><p class="muted">Only students registered using <?=e($promoter['referral_code'])?> are shown here.</p></div><a class="btn alt" href="logout.php">Log out</a></div><div class="scroll"><table><tr><th>Student</th><th>Grade</th><th>Joined</th><th>Premium purchase</th></tr><?php if(!$students):?><tr><td colspan="4" class="muted">No students have registered with your code yet.</td></tr><?php endif;foreach($students as $student):?><tr><td><strong><?=e($student['full_name'])?></strong><br><small><?=e($student['phone'])?> · <?=e($student['school_name']?:'School not provided')?></small></td><td>Grade <?=intval($student['grade_number'])?><br><small><?=e($student['medium'])?></small></td><td><?=e(date('d M Y, g:i A',strtotime($student['created_at'])))?></td><td><?php if((int)$student['purchases']>0):?><span class="badge">✓ Paid Rs. <?=e(number_format((float)$student['paid_amount'],0))?></span><br><small><?=e(date('d M Y, g:i A',strtotime($student['purchased_at'])))?></small><?php elseif((int)$student['pending']>0):?><span class="badge">Payment pending</span><?php else:?><span class="muted">Not purchased</span><?php endif;?></td></tr><?php endforeach;?></table></div></section>
<script>document.getElementById('copyReferralLink').addEventListener('click',async function(){await navigator.clipboard.writeText(this.dataset.link);this.textContent='✓ Registration link copied'});</script>
<?php include __DIR__.'/../includes/footer.php';?>
