<?php
declare(strict_types=1);
require_once __DIR__ . '/config.php';
$languages=['en'=>'English','si'=>'සිංහල','ta'=>'தமிழ்'];
if(isset($_GET['lang']) && isset($languages[$_GET['lang']])) $_SESSION['lang']=$_GET['lang'];
$_SESSION['lang']=$_SESSION['lang']??'en';
$T=[
'en'=>['welcome'=>'Welcome','login'=>'Log in','register'=>'Create account','logout'=>'Log out','home'=>'Home','learn'=>'Learn','chat'=>'AI Tutor','progress'=>'Progress','profile'=>'Profile','subjects'=>'Subjects','lessons'=>'Lessons','quizzes'=>'Quizzes','search'=>'Search lessons','email'=>'Email','username'=>'Username','password'=>'Password','confirm'=>'Confirm password','full_name'=>'Full name','grade'=>'Grade','medium'=>'Medium','language'=>'Language','save'=>'Save','continue'=>'Continue','premium'=>'Premium','subscribe'=>'Subscribe for LKR 250','sample'=>'Verified multilingual textbook learning content.','invalid'=>'Please check the information and try again.','required'=>'All required fields must be completed.','dashboard'=>'Dashboard','results'=>'Results','back'=>'Back','submit'=>'Submit','free'=>'Free','month'=>'30 days'],
'si'=>['welcome'=>'ආයුබෝවන්','login'=>'පිවිසෙන්න','register'=>'ගිණුම සාදන්න','logout'=>'ඉවත් වන්න','home'=>'මුල් පිටුව','learn'=>'ඉගෙන ගන්න','chat'=>'AI ගුරුවරයා','progress'=>'ප්‍රගතිය','profile'=>'පැතිකඩ','subjects'=>'විෂයයන්','lessons'=>'පාඩම්','quizzes'=>'ප්‍රශ්නාවලි','search'=>'පාඩම් සොයන්න','email'=>'විද්‍යුත් තැපෑල','username'=>'පරිශීලක නාමය','password'=>'මුරපදය','confirm'=>'මුරපදය තහවුරු කරන්න','full_name'=>'සම්පූර්ණ නම','grade'=>'ශ්‍රේණිය','medium'=>'මාධ්‍යය','language'=>'භාෂාව','save'=>'සුරකින්න','continue'=>'ඉදිරියට','premium'=>'වාරික','subscribe'=>'රු. 250කට දායක වන්න','sample'=>'සත්‍යාපිත 6 ශ්‍රේණියේ පෙළපොත් ඉගෙනුම් අන්තර්ගතය.','invalid'=>'තොරතුරු පරීක්ෂා කර නැවත උත්සාහ කරන්න.','required'=>'අවශ්‍ය සියලු කොටස් පුරවන්න.','dashboard'=>'උපකරණ පුවරුව','results'=>'ප්‍රතිඵල','back'=>'ආපසු','submit'=>'යවන්න','free'=>'නොමිලේ','month'=>'දින 30'],
'ta'=>['welcome'=>'வணக்கம்','login'=>'உள்நுழைய','register'=>'கணக்கை உருவாக்கு','logout'=>'வெளியேறு','home'=>'முகப்பு','learn'=>'கற்க','chat'=>'AI ஆசிரியர்','progress'=>'முன்னேற்றம்','profile'=>'சுயவிவரம்','subjects'=>'பாடங்கள்','lessons'=>'பாடங்கள்','quizzes'=>'வினாடி வினாக்கள்','search'=>'பாடங்களைத் தேடுங்கள்','email'=>'மின்னஞ்சல்','username'=>'பயனர் பெயர்','password'=>'கடவுச்சொல்','confirm'=>'கடவுச்சொல்லை உறுதிப்படுத்து','full_name'=>'முழு பெயர்','grade'=>'தரம்','medium'=>'மொழிமூலம்','language'=>'மொழி','save'=>'சேமி','continue'=>'தொடரவும்','premium'=>'பிரீமியம்','subscribe'=>'ரூ. 250க்கு சந்தா','sample'=>'இது மாதிரி பாடத்திட்ட உள்ளடக்கம் — நிர்வாகிகள் சரிபார்க்கப்பட்ட உள்ளடக்கத்தால் மாற்ற வேண்டும்.','invalid'=>'தகவலைச் சரிபார்த்து மீண்டும் முயலுங்கள்.','required'=>'தேவையான அனைத்து புலங்களையும் நிரப்பவும்.','dashboard'=>'முகப்புப் பலகை','results'=>'முடிவுகள்','back'=>'பின்செல்','submit'=>'சமர்ப்பி','free'=>'இலவசம்','month'=>'30 நாட்கள்']];
$T['si']['chat']='අලුත් සර්';
function tr(string $key):string { global $T; return $T[$_SESSION['lang']??'en'][$key]??$T['en'][$key]??$key; }
function lang_col(string $base):string { return $base.'_'.($_SESSION['lang']??'en'); }
